Ajout de la page /game-dev/asset
NotANameServer/Not-a-Hub pull request #1
Opened 2021-08-19 21:13 UTC by arkena00

L'idée serait d'avoir plusieurs format en fonction des pages de ressources, et des tags en fin de fichier, pour que les gens qui veulent en ajouter puisse se référencer aux tags existants, ce qui permet quand on cherche quelque chose de faire une recherche dans la page et de tomber sur ce qu'on cherche directement.
Par contre je sais pas trop vers quoi on pourrait faire pointer les tags, ptet faire un tag.md à part mais ça risque d'être galère à gérer, ou alors ajouer un #tag dans la page en haut ou en bas.

2021-08-22 19:37 UTC, Elanis commented
Perso j'aime bien les tableaux, et le layout en général.

Tu veux faire pointer les tags vers quelque part pour quoi ? Avoir une definition ? Une liste de tags pour savoir ce qu'il y a sur la page ?

2021-08-22 20:04 UTC, arkena00 commented
Juste pour pas avoir un 404 quand tu clics dessus :p

2021-08-23 08:48 UTC, Elanis commented
Je comprends pas, pourquoi avec un lien alors ? Pourquoi pas juste du texte ?

2021-08-23 15:25 UTC, arkena00 commented
Pour voir directement les tags accessibles et pouvoir faire une recherche sur ce tag dans la page

2021-08-23 16:33 UTC, Elanis commented
J'ai du mal à te comprendre 😄  Du coup ca serait un truc du genre:

> # Liste des tags
> 
> #### [HDRI](#HDRI)
> #### [Texture](#Texture) 
> ...

Avant, après le document ou dans un autre document; et les liens dans la colonne "Meta" mèneraient à cette liste ?
Si c'est pas ca, au pire fait un exemple, et on comprendra mieux.

Et sinon si j'ai bien compris, j'ai une preference pour le haut du fichier pour ce genre d'index perso.

2021-08-23 16:39 UTC, arkena00 commented
C'est ça. Comme ça quand les pages deviendront grandes ça sera plus simple de savoir ce qu on peut chercher. Meta c est pour les infos de la ressource. Tag, description, note spécifique etc..

2021-08-23 16:40 UTC, Elanis commented
Yes, du coup dans ce cas c'est une bonne idée ouaip :) Faudra juste mettre les tags (et si possible les ressources dans un tableau) par ordre alphabetique pour faciliter tout ca aussi

2021-08-23 17:00 UTC, Mesteery commented
Tu pourrais aussi peut-être ajouter une peu de texte description et titre plus complet (`game-dev` c'est beaucoup trop vaste), ...comme pour un article ?

2021-08-23 17:04 UTC, Mesteery commented on game-dev/asset.md
> +[Landscape]: #game-dev
ça sert un peu à rien de link vers le h1

2021-08-23 17:17 UTC, arkena00 commented on game-dev/asset.md
> +[Landscape]: #game-dev
Ca sert à remonter à la liste des tags, tu veux link vers quoi ?

2021-08-23 17:19 UTC, Elanis commented on game-dev/asset.md
> +[Landscape]: #game-dev
Avec le dernier commit, du coup ca mène aux tags, c'est cool

2021-08-23 17:20 UTC, Mesteery commented on game-dev/asset.md
> +[Landscape]: #game-dev
vers rien

2021-08-23 17:36 UTC, Elanis requested changes
Parce que je suis stressé par l'ordre alphabétique 😄

2021-08-23 17:36 UTC, Elanis commented on game-dev/asset.md
> +**Tags:** [HDRI] | [Texture] | [Modèle] | [Landscape]
```suggestion
**Tags:** [HDRI] | [Landscape] | [Modèle] | [Texture]
```

2021-08-23 17:36 UTC, Elanis commented on game-dev/asset.md
> +| Polyhaven        | [Link](https://polyhaven.com/) | [HDRI] / [Texture] / [Modèle]
```suggestion
| Polyhaven        | [Link](https://polyhaven.com/) | [HDRI] / [Modèle] / [Texture]
```

2021-08-23 17:36 UTC, Elanis commented on game-dev/asset.md
> +| Quixel mixer     | [Link](https://quixel.com/mixer)             | Permet de fusionner des [Texture]
```suggestion
| Quixel mixer     | [Link](https://quixel.com/mixer)             | Permet de fusionner des [Texture]
| Spacescape       | [Link](http://alexcpeterson.com/spacescape/) | Cubemap spatial
| World creator    | [Link](https://www.world-creator.com/)       | [Landscape]
```

2021-08-23 17:36 UTC, Elanis commented on game-dev/asset.md
> +[Landscape]: #game-dev
```suggestion
[HDRI]: #game-dev
[Landscape]: #game-dev
[Modèle]: #game-dev
[Texture]: #game-dev
```

2021-08-23 19:33 UTC, arkena00 commented
ça me parait bien comme ça

2021-08-23 19:48 UTC, Elanis approved these changes

2021-08-23 20:18 UTC, Elanis commented on game-dev/asset.md
> +| World creator    | [Link](https://www.world-creator.com/)       | [Landscape]
```suggestion
## Asset
|                  | Licence          | Prix             | Lien                           | Meta
| ---------------- | ---------------- | ---------------- | ------------------------------ | ---
| Polyhaven        | CC0              | Gratuit          | [Link](https://polyhaven.com/) | [HDRI] / [Modèle] / [Texture]

## Création d'assets
|                  | Licence          | Prix             | Lien                                         | Meta   
| ---------------- | ---------------- | ---------------- | -------------------------------------------- | ---
| Quixel mixer     | -                | Gratuit          | [Link](https://quixel.com/mixer)             | Permet de fusionner des [Texture]
| Spacescape       | -                | Gratuit          | [Link](http://alexcpeterson.com/spacescape/) | Cubemap spatial
| World creator    | -                | Payant (3 Tiers) | [Link](https://www.world-creator.com/)       | [Landscape]
```

Ajout de la notion de licence/prix

2021-08-23 20:50 UTC, Elanis commented on game-dev/asset.md
> +| **World creator** | -                | Payant (3 Tiers) | [Lien](https://www.world-creator.com/)       | [Landscape]
Avant: https://cdn.discordapp.com/attachments/878273796019216404/879460936019234877/unknown.png
Ce commentaire: https://cdn.discordapp.com/attachments/600774326047866881/879467709874733096/unknown.png

2021-08-23 20:55 UTC, Mesteery commented on game-dev/asset.md
> +| **World creator** | -                | Payant (3 Tiers) | [Lien](https://www.world-creator.com/)       | [Landscape]
Tiers -> tiers. Personnellement les espaces après le nom ne servent pas à grand chose, mais ce n'est pas très important.

2021-08-23 20:56 UTC, Elanis commented on game-dev/asset.md
> +| **World creator** | -                | Payant (3 Tiers) | [Lien](https://www.world-creator.com/)       | [Landscape]
J'ai modifié pour tiers 👌 

Pour les espaces, c'est selon le niveau d'alignement qu'on veut dans le document éditable 😄

2021-08-23 20:58 UTC, Mesteery commented on game-dev/asset.md
> +| **World creator** | -                | Payant (3 Tiers) | [Lien](https://www.world-creator.com/)       | [Landscape]
L'alignement dans le nom n'améliore pas la lisibilité imo

2021-08-30 16:06 UTC, Elanis approved these changes

2021-08-30 16:06 UTC, Elanis approved these changes

2021-09-03 13:16 UTC, Elanis approved these changes, later dismissed

2021-09-03 15:26 UTC, Mesteery requested changes, later dismissed
Ce serait pas possible d'avoir un meilleur titre que "game-dev". Ce titre sera affichée dans les index (l'index root y compris).
De plus, une description serait la bienvenue IMO.

2021-09-04 18:10 UTC, Elanis commented
@Mesteery Je vais integrer tes review à ma PR, je n'ai aucune marge de manoeuvre sur celle là ... Je ne peux plus suggerer de modifs de code.

2021-09-04 18:11 UTC, Elanis approved these changes

2021-09-04 18:42 UTC, Mesteery approved these changes

2021-09-04 20:20 UTC, Elanis commented
Remplacé par #9, j'ai récup les modifs et les auteurs

2021-09-04 20:20 UTC, closed without merging