add: various python articles
NotANameServer/Not-a-Hub pull request #2
Opened 2021-08-20 16:34 UTC by Julien00859

Various articles that have been living on my private blog for quite a
few years and that have been shared among various discord communities.

2021-08-20 16:36 UTC, Julien00859 commented
Je n'ai pas ajouté python_exe car je ne suis pas tout à fait satisfait de l'article. Le lien dans `ide.md` ne fonctionne peut-être pas correctement, je le changerai si il s'avère que le lien est cassé

2021-08-20 16:55 UTC, Mesteery commented
On est d'accord que c'est des articles ? Le nom des fichiers devrait plutôt être le titre slugifié (espaces, apostrophes, etc. remplacés par des tirets).
Aussi personnellement je ne pense pas que le dossier `assets` devrait être au même niveau des autres dossiers, ce n'est pas logique. Ces dossiers, au lieu d'être à la racine, pourraient être déplacé vers un dossier du genre `articles`.
De plus il devrait y avoir un fichier `index.md` à la racine, avec des liens vers les articles, et une petite présentation du serveur (le `/` du site). Mais ça c'est à faire dans une autre PR dont celle-ci dépendra.

2021-08-20 20:25 UTC, Julien00859 commented
> Le nom des fichiers devrait plutôt être le titre slugifié (espaces, apostrophes, etc. remplacés par des tirets).

Je préfère avoir un url cours /langages/python/ide.html qu'un truc "user-friendly", le titre ils peuvent le lire quand ils ouvrent la page

> De plus il devrait y avoir un fichier index.md à la racine, avec des liens vers les articles, et une petite présentation du serveur (le / du site). Mais ça c'est à faire dans une autre PR dont celle-ci dépendra.

Hors scope

> Aussi personnellement je ne pense pas que le dossier assets devrait être au même niveau des autres dossiers, ce n'est pas logique. Ces dossiers, au lieu d'être à la racine, pourraient être déplacé vers un dossier du genre articles.

Bof, l'important ce sont les articles, donc ça doit rester accessible depuis la racine du repos, mettre un dossier en plus juste pour que ce soit "propre" perso je trouve que c'est faire du zèle pour rien

2021-08-20 20:28 UTC, Mesteery commented
> Je préfère avoir un url cours /langages/python/ide.html qu'un truc "user-friendly", le titre ils peuvent le lire quand ils ouvrent la page

Dans cas peut-être un truc plus complet que `ide`, `awesome`, `graven` ?

2021-08-20 20:36 UTC, Mesteery commented on langages/python/awesome.md
> +Parmis la documentation, voici quelques pages que nous jugeons essentiel à lire:
Il manque des points en fin de phrases ? Espaces avant les points ?

2021-08-20 20:36 UTC, Mesteery commented on langages/python/awesome.md
> +# Apprendre Python, quoi lire, quoi regarder
Un meilleur titre ?

2021-08-20 20:36 UTC, Mesteery commented on langages/python/graven.md
> +Le cours intitulé "Apprendre le Python" est un cours proposé sur la chaîne youtube Gravenilvectuto. Le cours se présente comme un cours pour apprendre les fondamentaux du langage de programmation Pyt
```suggestion
Le cours intitulé "Apprendre le Python" est un cours proposé sur la chaîne YouTube Gravenilvectuto. Le cours se présente comme un cours pour apprendre les fondamentaux du langage de programmation Python. Il est constitué de 9 vidéos sur le langage d'une moyenne de 13 minutes et d'une vidéo sur la bibliothèque Tkinter de 40 minutes.
```
same pour le reste ?

2021-08-20 20:36 UTC, Mesteery commented on langages/python/graven.md
> +Il existe une [syntaxe dédié](https://www.python.org/dev/peps/pep-0308/) pour les ternaires depuis python 2.5 (sortie en 2006). La syntaxe est la suivante :
```suggestion
Il existe une [syntaxe dédiée](https://www.python.org/dev/peps/pep-0308/) pour les ternaires depuis python 2.5 (sortie en 2006). La syntaxe est la suivante : 
```

2021-08-20 20:36 UTC, Mesteery commented on langages/python/graven.md
> +Il existe une [syntaxe dédié](https://www.python.org/dev/peps/pep-0308/) pour les ternaires depuis python 2.5 (sortie en 2006). La syntaxe est la suivante :
```suggestion
Il existe une [syntaxe dédié](https://www.python.org/dev/peps/pep-0308/) pour les ternaires depuis Python 2.5 (sortie en 2006). La syntaxe est la suivante : 
```
Majuscules à python ?

2021-08-20 20:36 UTC, Mesteery commented on langages/python/graven.md
> +* L'expression `condition ? true_value : false_value` est une expression ternaire en Java, l'expression python `(false_value:true_value)[condition]` y ressemble fâcheusement (expressions finales d'un
```suggestion
* L'expression `condition ? true_value : false_value` est une expression ternaire en Java, l'expression python `(false_value, true_value)[condition]` y ressemble fâcheusement (expressions finales d'un côté, condition de l'autre) mais n'est pas une expression ternaire en Python ;
```
plutôt ?

2021-08-20 20:54 UTC, Mesteery commented on langages/python/ide.md
> +![langchar](/assets/images/py-ide-langchart.png)
```suggestion
![ide chart](/assets/images/py-ide-langchart.png)
```

2021-08-20 20:56 UTC, Mesteery commented on langages/python/ide.md
> +* [VS Code](https://code.visualstudio.com/) (pro: complet et extensible, con: lourd)
Je pense pas que VSCode est lourd. Il est certes plus lourd que par exemple, Sublime text, mais pas non plus très lourd. Peut-être `légèrement lourd` ou `lourd` convient ?

2021-08-20 21:06 UTC, Oedipsos commented on langages/python/ide.md
> +* [VS Code](https://code.visualstudio.com/) (pro: complet et extensible, con: lourd)
Cela reste un article écrit par Lazor, ce n'est pas nécéssaire à mon sens de corriger ce choix là, la différence est pas spécialement forte entre "lourd" et ce magnifique oxymore qu'est "légèrement lourd".

2021-08-20 21:08 UTC, Mesteery commented on langages/python/ide.md
> +* [VS Code](https://code.visualstudio.com/) (pro: complet et extensible, con: lourd)
Oui enfin c'est pas parce que c'est écrit par tel ou tel personne, qu'une information inexacte a le droit d'être présente. Mais `lourd` convient certes.

2021-08-20 22:17 UTC, Oedipsos requested changes
Correction globale de l'orthographe, de la ponctuation, des tournures de phrases, etc. J'ai peut-être raté quelques typos, une seconde vérification ne sera pas de trop ! J'ai essayé de conserver un maximum les mots utilisés, sauf si la phrase devenait grammaticalement douteuse où j'ai choisi un synonyme à la place.

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/awesome.md
> +Parmis la documentation, voici quelques pages que nous jugeons essentiel à lire :
```suggestion
Parmi la documentation, voici quelques pages que nous jugeons essentielles à lire :
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/awesome.md
> +* Un livre qui rentre en profondeur dans l'écosystème python et qui s'adresse à un publique plus confirmé : <https://www.packtpub.com/product/expert-python-programming-third-edition/9781789808896>
```suggestion
* Un livre reprenant des centaines de recettes de code pour explorer les possibilités de Python et de sa bibliothèque standard : <https://www.oreilly.com/library/view/python-cookbook/0596001673/>
* Un livre qui rentre en profondeur dans l'écosystème Python et qui s'adresse à un public plus confirmé : <https://www.packtpub.com/product/expert-python-programming-third-edition/9781789808896>
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/awesome.md
> +* Structurer et partager vos projet : <https://packaging.python.org/tutorials/packaging-projects/>
```suggestion
* Structurer et partager vos projets : <https://packaging.python.org/tutorials/packaging-projects/>
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +# Critique du cours vidéo sur python de Graven
```suggestion
# Critique du cours vidéo sur Python de Graven
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Contrairement à ce qui est présenté dans la vidéo, un IDE (environnement de développement intégré) n'est pas *nécessaire* pour développer. Il est d'ailleurs plus commun de croiser des développeurs py
```suggestion
Contrairement à ce qui est présenté dans la vidéo, un IDE (environnement de développement intégré) n'est pas *nécessaire* pour développer. Il est d'ailleurs plus commun de croiser des développeurs Python qui utilisent le combo éditeur de texte et terminal du fait de la légèreté du langage. [J'ai écrit un billet à ce sujet](https://docs.drlazor.be/python_ide.md).
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Lors de l'installation de python, l'attention du téléspectateur n'est pas attirée sur l'option "Add python to the PATH", il s'agit d'une case à cocher qui rend accessible les programmes `python`, `py
```suggestion
Lors de l'installation de Python, l'attention du téléspectateur n'est pas attirée sur l'option "Add python to the PATH", il s'agit d'une case à cocher qui rend accessible les programmes `python`, `py` et `pip` via la ligne de commande. Les débutants ne savent généralement pas comment changer les variables d'environnement sur Windows et se plaignent de ne pas réussir à lancer Python car `'python' n’est pas reconnu en tant que commande interne ou externe, un programme exécutable ou un fichier de commandes.`.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Je regrette également que la fonction `print` n'ait pas été utilisé correctement. La fonction peut prendre plusieurs arguments qui seront par tous caster en string et concaténés avec un espace. La so
```suggestion
Je regrette également que la fonction `print` n'ait pas été utilisé correctement. La fonction peut prendre plusieurs arguments qui seront tous castés en string et concaténés avec un espace. La solution proposée est de passer via le type `str` pour convertir le nombre en chaîne de caractères.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Il aurait été judicieux de présenter ces types plus tôt, à savoir les types `int()`, `str()`, `float()` et `bool()`, et de montrer qu'il peuvent être utiliser pour convertir les types entre eux. Les
```suggestion
Il aurait été judicieux de présenter ces types plus tôt, à savoir les types `int()`, `str()`, `float()` et `bool()`, et de montrer qu'il peuvent être utilisés pour convertir les types entre eux. Les explications de la conversion en booléen auraient par exemple pu servir de fondation pour l'épisode sur les conditions.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +La fonction `format` sera présenté dans la vidéo suivante pour faciliter l'insertion de données dans les chaînes de caractère.
```suggestion
La fonction `format` sera présentée dans la vidéo suivante pour faciliter l'insertion de données dans les chaînes de caractères.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Il existe une [syntaxe dédiée](https://www.python.org/dev/peps/pep-0308/) pour les ternaires depuis python 2.5 (sortie en 2006). La syntaxe est la suivante :
```suggestion
Il existe une [syntaxe dédiée](https://www.python.org/dev/peps/pep-0308/) pour les ternaires depuis Python 2.5 (sortie en 2006). La syntaxe est la suivante :
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +L'exemple d'expression ternaire présenté dans la vidéo, en plus d'être difficile à lire et obsolète, est faux. Le code montré réallise un accès dans un tuple littéral. Cet accès est possible car le t
```suggestion
L'exemple d'expression ternaire présenté dans la vidéo, en plus d'être difficile à lire et obsolète, est faux. Le code montré réalise un accès dans un tuple littéral. Cet accès est possible car le tuple possède deux éléments accessibles aux indices 0 et 1 et que les deux valeurs booléenes ont un équivalent entier : 0 pour False, 1 pour True. Il est dit dans la vidéo que le premier élément sera renvoyé si l'expression est vraie, or c'est le second qui sera renvoyé.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Si l'ensemble des opérations présentées sur les listes sont correctes, l'attention quant à la complexité de ces opérations n'est pas attiré. Bon nombre d'opération (`del`, `insert`, `remove`) sont en
```suggestion
Si l'ensemble des opérations présentées sur les listes sont correctes, l'attention quant à la complexité de ces opérations n'est pas attiré. Bon nombre d'opérations (`del`, `insert`, `remove`) sont en complexité linéaire et non pas constante. Utiliser ces opérations doit donc se faire avec parcimonie.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Les listes seront d'ailleurs les seules structures de données présentées dans la vidéo, pas un mot sur les dictionnaires, les sets ou la bibliothèque collections.
```suggestion
Les listes seront d'ailleurs les seules structures de données présentées dans la vidéo, pas un mot sur les dictionnaires, les sets ou la bibliothèque `collections`.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Le `for` traditionnellement utilisé dans les langages comme C, Java (`for (int x = 0; x < 5; x++)`) n'existe pas en Python. Python n'est capable que d'itérer sur des objets itérables (ceux qui défini
```suggestion
Le `for` traditionnellement utilisé dans les langages comme C, Java (`for (int x = 0; x < 5; x++)`) n'existe pas en Python. Python n'est capable d'itérer que sur des objets itérables (ceux qui définissent les méthodes magiques `__iter__` ou/et `__next__`). `range` est un de ces objets, bien qu'à l'utilisation il permet de simuler le `for` classique, il n'en reste pas moins un objet qui implémente ces deux méthodes.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +En programmation orienté-objet, lorsqu'un fonction nécessite un contexte pour fonctionner, on préférera utiliser un objet pour sauvegarder ce contexte et écrire une *méthode*.
```suggestion
Tout de suite après avoir montré comment définir et appeler des fonctions, l'auteur introduit les variables globales. Les variables globales font partie des techniques appelées de *mémoire partagée*, un ensemble de la mémoire qui est accessible et qui peut être modifié par plusieurs entités à la fois, ici les fonctions. Ces techniques sont connues pour mener à des programmes qui sont difficiles à maintenir, qui présentent plus de bug et qui empêchent l'exécution parallèle. Il est dangereux d'introduire ce mécanisme et on lui préférera systématiquement les fonctions paramétriques.

En programmation orientée-objet, lorsqu'une fonction nécessite un contexte pour fonctionner, on préférera utiliser un objet pour sauvegarder ce contexte et écrire une *méthode*.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Cependant, les bonnes pratiques de développement Python contrastent avec les bonnes pratiques d'autres langages de programmation orienté objet comme Java, C# ou PHP. En Python, la notion d'accessibil
```suggestion
Cependant, les bonnes pratiques de développement Python contrastent avec les bonnes pratiques d'autres langages de programmation orientée-objet comme Java, C# ou PHP. En Python, la notion d'accessibilité des variables n'existe pas, pas de mot clé `public` ou `private` pour définir la visibilité des attributs ou des méthodes. En réalité il s'agit d'un choix d'implémentation, en Python on accédera directement à l'attribut tant en lecture qu'en écriture sans passer par des méthodes `get_xyz()` ou `set_xyz()`. Si exécuter une fonction est nécessaire pour effectuer en traitement avant de renvoyer une valeur, on préférera utiliser une propriété.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Les seules structures de donnés présentées dans le cours sont les listes et les objets. Python est un langage très riche qui défini un foison de structures de données qu'il est nécessaire de connaitr
```suggestion
Les seules structures de données présentées dans le cours sont les listes et les objets. Python est un langage très riche qui définit une abondance de structures de données qu'il est nécessaire de connaître et de savoir exploiter.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Un ensemble mathématique est une structure de donnée où les éléments sont ou ne sont pas présents. D'un point de vue informatique, ils peuvent être considérés comme des listes non-ordonnées sans doub
```suggestion
Un ensemble mathématique est une structure de données où les éléments sont ou ne sont pas présents. D'un point de vue informatique, ils peuvent être considérés comme des listes non-ordonnées sans doublons. Ils sont implémentés en Python via l'objet `set`.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Un dictionnaire est un livre qui associe chaque mot d'une langue à une définition. Il existe aussi des dictionnaires de traduction où chaque mot d'une langue est associé au même mot dans une autre la
```suggestion
Un dictionnaire est un livre qui associe chaque mot d'une langue à une définition. Il existe aussi des dictionnaires de traduction où chaque mot d'une langue est associé au même mot dans une autre langue. En informatique, un dictionnaire (aussi appelé tableau associatif ou *map*) est une structure de données qui associe un élément quelconque à un autre élément quelconque. Ils sont implémentés en Python via l'objet `dict`. Les dictionnaires de base ne sont pas forcément triés (avant Python 3.7), leur équivalent trié est implémenté via `collections.OrderedDict`.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Une file ou une queue comme une file à la caisse est une autre structure de donnée où on ajoute des éléments d'un côté et où on retire les éléments depuis l'autre côté. Si ces opérations sont possibl
```suggestion
Une file ou une queue comme une file à la caisse est une autre structure de données où on ajoute des éléments d'un côté et où on retire les éléments depuis l'autre côté. Si ces opérations sont possible sur des listes classiques, ces opérations sont néanmoins non-optimisées. La structure optimisée pour gérer des files existe via l'objet `collections.deque`.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Les bibliothèques `collections`, `queue`, `bisect` et `heapq` regorgent d'autres structure de données qui ne sont pas reprises ici.
```suggestion
Les bibliothèques `collections`, `queue`, `bisect` et `heapq` regorgent d'autres structures de données qui ne sont pas reprises ici.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Ce qu'on appelle le *scope* est le niveau d'accessibilité des variables. Quant et comment les variables du programme sont accessibles
```suggestion
Ce qu'on appelle le *scope* est le niveau d'accessibilité des variables, c'est-à-dire quand et comment les variables du programme sont accessibles.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Lorsque Python tente d'accéder à une variable *en lecture*, il va consulter le scope de la fonction : il commence par consulter les variables locales à la fonction, s'il ne la trouve pas, il consulte
```suggestion
Lorsque Python tente d'accéder à une variable *en lecture*, il va consulter le scope de la fonction : il commence par consulter les variables locales à la fonction. S'il ne la trouve pas, il va consulter le scope de la fonction supérieure et ainsi de suite jusqu'à arriver au scope dit *global* qui correspond à la racine du module. Si la variable n'a été trouvée dans aucun scope, une erreur `NameError` sera remontée à l'utilisateur.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Si ce comportement est celui par défaut c'est qu'il est déconseillé de modifier les variables défini en dehors de sa propre fonction. En effet, pour un programme conséquent, il devient difficile de d
```suggestion
Si ce comportement est celui par défaut c'est qu'il est déconseillé de modifier les variables définies en dehors de sa propre fonction. En effet, pour un programme conséquent, il devient difficile de déterminer quels sont les fonctions qui modifient une variable, le développeur n'a pas d'autre solution que de scanner l'ensemble du programme pour déterminer quelle fonction lit / écrit cette variable ce qui pose des problèmes quant à la compréhension du programme en général.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Un autre problème survient lorsqu'on souhaite paralléliser un traitement sur plusieurs processeurs. Si un processeur lit le contenu d'une variable global en même temps qu'un autre processeur en chang
```suggestion
Un autre problème survient lorsqu'on souhaite paralléliser un traitement sur plusieurs processeurs. Si un processeur lit le contenu d'une variable globale en même temps qu'un autre processeur en change son contenu, on se retrouve dans une situation où *l'on ne sait pas* ce qui a été lu. La lecture a-t-elle eu lieu avant la modification ? Après ? Ou pire... Pendant ?
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Ces problèmes ne se produisent pas lorsqu'on utilise une stratégie d'implémentation claire ou l'utilisation des variables est clairement défini comme pour les fonctions paramétriques ou les objets.
```suggestion
Ces problèmes ne se produisent pas lorsqu'on utilise une stratégie d'implémentation claire ou l'utilisation des variables est clairement définie comme pour les fonctions paramétriques ou les objets.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +La visibilités en orienté objet est une notion qui permet de contrôler *qui* a accès (en lecture, en écriture ou en exécution) aux attributs et aux méthodes d'un objet. Cette notion est implémentée d
```suggestion
La visibilité en orienté-objet est une notion qui permet de contrôler *qui* a accès (en lecture, en écriture ou en exécution) aux attributs et aux méthodes d'un objet. Cette notion est implémentée dans nombre de langages orientés-objet statiques comme Java, C# et C++. Lorsqu'un attribut est déclaré avec `private` elle n'est accessible que par l'objet courant, il en va de même pour les méthodes. Au contraire lorsqu'un attribut/une méthode est déclarée publique, tout le monde peut y accéder.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Cette notion de visibilité est absente de Python qui préfère *faire confiance aux développeurs* qu'ils n'aillent pas toucher ce qu'ils ne devraient pas. Ainsi la seule notion qui sépare les attributs
```suggestion
Cette notion de visibilité est absente de Python qui préfère *faire confiance aux développeurs* qu'ils n'aillent pas toucher ce qu'ils ne devraient pas. Ainsi la seule notion qui sépare les attributs, propriétés et méthodes publiques de celles considérées comme "privées" est une convention d'écriture. On préfixera ce qui est privé par un underscore. Le développeur est libre de n'en faire qu'à sa tête de tout de même les utiliser même si c'est déconseillé.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Dans la même ligné qu'il n'y a pas de notion de visibilité en Python, les pratiques de développement Python conseillent de directement modifier les attributs des objets sans passer par des méthodes d
```suggestion
Dans la même lignée qu'il n'y a pas de notion de visibilité en Python, les pratiques de développement Python conseillent de directement modifier les attributs des objets sans passer par des méthodes de contrôle. Dit autrement, l'utilisation systématique d'accesseurs (*getter*) et de mutateurs (*setters*) est déconseillé.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Dans l'industrie ceci ne pose en réalité aucun soucis, les développeurs qui définissent les interfaces objets sont généralement également ceux qui les utiliseront ou qui seront charger de relire le c
```suggestion
Dans l'industrie ceci ne pose en réalité aucun souci, les développeurs qui définissent les interfaces objets sont généralement ceux qui les utiliseront ou qui seront chargés de relire le code des autres développeurs.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Cependant, il est parfois nécessaire d'effectuer des traitements à l'accès ou à la modification des attributs. Pour se faire, Python a opté pour les propriétés. Une propriété s'utilise comme une vari
```suggestion
Cependant, il est parfois nécessaire d'effectuer des traitements à l'accès ou à la modification des attributs. Pour ce faire, Python a opté pour les propriétés. Une propriété s'utilise comme une variable normale, on récupère la valeur en donnant uniquement le nom de la propriété et on modifie sa valeur comme une simple affectation. La différence est qu'au lieu d'être directement accédée ou modifiée, c'est une fonction de traitement qui sera chargée de renvoyer / modifier la variable.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Via ce mécanisme, il est possible de laisser un attribut "publique" (sans underscore en préfix) et s'il s'avère à l'utilisation qu'une fonction de traitement est nécessaire, il suffit de préfixer l'a
```suggestion
Via ce mécanisme, il est possible de laisser un attribut "public" (sans underscore en préfixe) et s'il s'avère à l'utilisation qu'une fonction de traitement est nécessaire, il suffit de préfixer l'attribut pour qu'il soit "privé" et de définir au niveau de la classe une propriété du même nom que l'ancien attribut public. Le code qui exploitait l'attribut exploite maintenant la propriété indifféremment.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +Si la qualité visuelle des vidéos et la dynamique du cours sont supérieures à bon nombres de cours en lignes (gratuit et payant), le côté technique est quant à lui approximatif. L'approche pédagogiqu
```suggestion
Si la qualité visuelle des vidéos et la dynamique du cours sont supérieures à bon nombre de cours en ligne (gratuit et payant), le côté technique est quant à lui approximatif. L'approche pédagogique de l'auteur souffre de nombreux biais qui sont communs aux développeurs Java qui s'essaient au langage Python.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +* L'expression `condition ? true_value : false_value` est une expression ternaire en Java, l'expression python `(false_value, true_value)[condition]` y ressemble fâcheusement (expressions finales d'u
```suggestion
* L'expression `condition ? true_value : false_value` est une expression ternaire en Java, l'expression Python `(false_value, true_value)[condition]` y ressemble fâcheusement (expressions finales d'un côté, condition de l'autre) mais n'est pas une expression ternaire en Python ;
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/graven.md
> +* Le *for* classique n'existe pas en Python, il est simulé par l'objet range mais il n'existe en Python bien que ce que les développeurs Java appellent le *for each* ;
```suggestion
* Le *for* classique n'existe pas en Python, il est simulé par l'objet `range` mais il n'existe bien en Python que ce que les développeurs Java appellent le *for each* ;
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/ide.md
> +Python est un langage suffisamment simple pour qu'un IDE complet ne soit pas *nécessaire* à avoir une bonne vélocité de développement. Contrairement des langages à la syntaxe plus lourde, il n'est pa
```suggestion
Python est un langage suffisamment simple pour qu'un IDE complet ne soit pas *nécessaire* à avoir une bonne vélocité de développement. Contrairement aux langages à la syntaxe plus lourde, il n'est pas forcément nécessaire d'avoir toute une série de patterns automatiquement générés par l'éditeur.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/ide.md
> +Python a un système de module léger : contrairement à Java où une classe = un fichier, il n'est pas rare d'avoir toute une série de classes liées définies au sain d'un même module. Ceci limite drasti
```suggestion
Python a un système de module léger : contrairement à Java où une classe = un fichier, il n'est pas rare d'avoir toute une série de classes liées définies au sein d'un même module. Ceci limite drastiquement la quantité d'`import` nécessaires en début de fichier et extensiblement la nécessité d'avoir ces lignes d'`import` faites automatiquement.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/ide.md
> +Python propose nativement un environnement REPL (Read-Eval-Print-Loop) via le terminal ou IDLE. Il est donc aisé de tester un bout de code, d'accéder à la documentation au moyen de la fonction `help`
```suggestion
Python propose nativement un environnement REPL (Read-Eval-Print-Loop) via le terminal ou IDLE. Il est donc aisé de tester un bout de code, d'accéder à la documentation au moyen de la fonction `help` ou de lister l'ensemble des méthodes/fonctions d'une classe ou d'un module via la fonction `dir`. Personnellement je trouve qu'il est tout aussi rapide d'ouvrir l'interpréteur et de taper `dir(list)` suivi de `help(list.extend)` que d'utiliser la documentation fournie par un IDE ou de laisser l'autocomplétion me faire des suggestions.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/ide.md
> +Python est dynamiquement typé. Bien qu'il existe des outils comme [mypy](mypy-lang.org) qui peuvent aider à la vérification des types, peu de modules tirent avantage de la bibliothèque `typing` et un
```suggestion
Python est dynamiquement typé. Bien qu'il existe des outils comme [mypy](mypy-lang.org) qui peuvent aider à la vérification des types, peu de modules tirent avantage de la bibliothèque `typing` et un IDE se retrouve fort peu utile pour lever des avertissemnts en cas d'incohérence de types.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/ide.md
> +Tout ceci explique pourquoi un IDE n'est pas *nécessaire* au développement en python. Un éditeur de texte plus léger reste un choix tout aussi viable.
```suggestion
Tout ceci explique pourquoi un IDE n'est pas *nécessaire* au développement en Python. Un éditeur de texte plus léger reste un choix tout aussi viable.
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/ide.md
> +La liste suivante présente une liste non exhaustive:
```suggestion
La liste suivante présente une liste non exhaustive :
```

2021-08-20 22:17 UTC, Oedipsos commented on langages/python/ide.md
> +# Programmer en Python, quel IDE choisir
```suggestion
# Programmer en Python, quel IDE choisir ?
```

2021-08-20 22:36 UTC, Oedipsos approved these changes

2021-08-20 22:39 UTC, Mesteery commented
https://github.com/NotANameServer/Not-a-Hub/pull/2#issuecomment-902939736 up

2021-08-20 23:31 UTC, Julien00859 commented
Pas besoin de up non plus, je vais pas merge dans l'état. Tu remarqueras qu'Oedipsos a également review et réagi à tes propositions. Il n'a pas donné suite à celle concernant les noms de fichiers, preuve qu'on s'en fou un peu et que les noms des fichiers sont ok dans l'état.

2021-08-21 13:16 UTC, Oedipsos commented
> 
> 
> [#2 (comment)](https://github.com/NotANameServer/Not-a-Hub/pull/2#issuecomment-902939736) up

Comme dit Lazor, pour l'URL ce n'est pas très important, tant qu'au niveau de l'interface les articles sont référencés avec leurs titres respectifs, c'est bon. Je ne pense pas que l'utilisateur random sera perdu en voyant un `ide.md` dans l'URL, s'il la regarde. Et c'est plus simple de les laisser tels quel, ainsi pas besoin de les changer et de potentiellement en oublier un quelque part...

2021-08-21 17:53 UTC, Julien00859 commented
> tant qu'au niveau de l'interface les articles sont référencés avec leurs titres respectifs

Ce ne sera pas le cas si on utilise un `autoindex: on;`

2021-08-23 09:29 UTC, Mesteery commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +# Critique du cours vidéo sur Python de Graven
il manque un n dans le slug

2021-08-23 12:22 UTC, Julien00859 commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +# Critique du cours vidéo sur Python de Graven
Ok, je résoud ça pour ce soir, est-ce qu'il y a autre chose ? Si tout le reste est bon tu veux bien mettre une review positive ? :D

2021-08-23 12:37 UTC, Elanis requested changes
Je n'ai pas la pretention de connaitre assez le python pour review tes commentaires. Mais j'ai eu quelques remarques de mise en forme pour les liens lors de ma relecture.

2021-08-23 12:37 UTC, Elanis commented on langages/python/apprendre-python-quoi-lire-quoi-regarder.md
> +* Expéditif (on a quelques [critiques](https://docs.drlazor.be/python_graven.md)) : <https://www.youtube.com/watch?v=psaDHhZ0cPs&list=PLMS9Cy4Enq5JmIZtKE5OHJCI3jZfpASbR>
Le lien de la critique sera a mettre a jour vers l'article sur not a hub je pense

2021-08-23 12:37 UTC, Elanis commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +Contrairement à ce qui est présenté dans la vidéo, un IDE (environnement de développement intégré) n'est pas *nécessaire* pour développer. Il est d'ailleurs plus commun de croiser des développeurs Py
Même remarque concernant le lien que plus haut, peut être linker la version NaH plutôt.

2021-08-23 12:37 UTC, Elanis commented on langages/python/programmer-en-python-quel-ide-choisir.md
> +Python est dynamiquement typé. Bien qu'il existe des outils comme [mypy](mypy-lang.org) qui peuvent aider à la vérification des types, peu de modules tirent avantage de la bibliothèque `typing` et un
```suggestion
Python est dynamiquement typé. Bien qu'il existe des outils comme [mypy](http://mypy-lang.org) qui peuvent aider à la vérification des types, peu de modules tirent avantage de la bibliothèque `typing` et un IDE se retrouve fort peu utile pour lever des warning en cas d'incohérence de types.
```

Le lien de mypy est cassé, il manque le http://

2021-08-23 12:37 UTC, Elanis commented on langages/python/programmer-en-python-quel-ide-choisir.md
> +* [Sublime text](https://www.sublimetext.com/3) (pro: léger et rapide, con: pas fort extensible)
```suggestion
* [Sublime text](https://www.sublimetext.com) (pro: léger et rapide, con: pas fort extensible)
```
Il est plus intéressant de conseiller Sublime Text 4 que 3. Tout est accessible sur la page d'accueil du site. Et je suis pas trop d'accord sur le contre, vu qu'il y a https://packagecontrol.io

2021-08-23 16:24 UTC, Mesteery commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +# Critique du cours vidéo sur Python de Graven
Bien sûr 😄

2021-08-23 16:26 UTC, Mesteery commented on langages/python/programmer-en-python-quel-ide-choisir.md
> +* [Sublime text](https://www.sublimetext.com/3) (pro: léger et rapide, con: pas fort extensible)
J'en profite pour le text -> Text

2021-08-23 16:55 UTC, Mesteery approved these changes
*attention, beaucoup de nits.*
D'ailleurs les chevrons (pour les liens) ne sont pas nécessaires.
Ça fait beaucoup, désolé, mais c'est la dernière :)

2021-08-23 16:55 UTC, Mesteery commented on langages/python/apprendre-python-quoi-lire-quoi-regarder.md
> +La documentation officielle, votre principale source de connaissance (aussi dispo en français) : <https://docs.python.org/3/>
```suggestion
La documentation officielle, votre principale source de connaissance (aussi disponible en français) : https://docs.python.org
```
Le site redirige automatiquement vers `/3`, soit la dernière version (cela éviterait une potentielle mise à jour).

2021-08-23 16:55 UTC, Mesteery commented on langages/python/apprendre-python-quoi-lire-quoi-regarder.md
> +* <https://docs.python.org/3/reference/datamodel.html>
```suggestion
* https://docs.python.org/library/functions.html
* https://docs.python.org/library/stdtypes.html
* https://docs.python.org/library/string.html
* https://docs.python.org/library/exceptions.html
* https://docs.python.org/reference/datamodel.html
```
cf plus haut

2021-08-23 16:55 UTC, Mesteery commented on langages/python/apprendre-python-quoi-lire-quoi-regarder.md
> +* Expéditif (on a quelques [critiques](https://docs.drlazor.be/python_graven.md)) : <https://www.youtube.com/watch?v=psaDHhZ0cPs&list=PLMS9Cy4Enq5JmIZtKE5OHJCI3jZfpASbR>
```suggestion
* Expéditif (nous avons quelques [critiques](https://docs.drlazor.be/python_graven.md)) : <https://www.youtube.com/watch?v=psaDHhZ0cPs&list=PLMS9Cy4Enq5JmIZtKE5OHJCI3jZfpASbR>
```
?

2021-08-23 16:55 UTC, Mesteery commented on langages/python/apprendre-python-quoi-lire-quoi-regarder.md
> +* La philosophie du langage (must read !): <https://www.python.org/dev/peps/pep-0020/>
```suggestion
* La philosophie du langage (must read !) : https://www.python.org/dev/peps/pep-0020/
```

2021-08-23 16:55 UTC, Mesteery commented on langages/python/apprendre-python-quoi-lire-quoi-regarder.md
> +* Classes, dundler, descripteurs, itérateurs : <https://zestedesavoir.com/tutoriels/954/notions-de-python-avancees/>
```suggestion
* Classes, dundler, descripteurs et itérateurs : <https://zestedesavoir.com/tutoriels/954/notions-de-python-avancees/>
```

2021-08-23 16:55 UTC, Mesteery commented on langages/python/apprendre-python-quoi-lire-quoi-regarder.md
> +En vrac quelques conférences que nous jugeons particulièrement intéressantes :
```suggestion
Quelques conférences que nous jugeons particulièrement intéressantes :
```

2021-08-23 16:55 UTC, Mesteery commented on langages/python/apprendre-python-quoi-lire-quoi-regarder.md
> +* [Transforming Code into Beautiful, Idiomatic Python](https://youtu.be/OSGv2VnC0go) (attention c'est du python2)
```suggestion
* [Transforming Code into Beautiful, Idiomatic Python](https://youtu.be/OSGv2VnC0go) (attention, c'est du Python 2)
```
(ou même l'enlever?)

2021-08-23 16:55 UTC, Mesteery commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +L'ensemble des vidéos sera capturé dans cet environnement. On peut regretter que le vidéaste ne désactive pas les différents linters et correcteurs orthographiques. Les démonstrations sont sans-cesse
Peut-être expliqué ce que c'est un linter en une court phrase entre parenthèse ? (je ne pense pas qu'un débutant saurait ce que c'est)

2021-08-23 16:55 UTC, Mesteery commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +Lors de l'installation de Python, l'attention du téléspectateur n'est pas attirée sur l'option "Add python to the PATH", il s'agit d'une case à cocher qui rend accessible les programmes `python`, `py
```suggestion
Lors de l'installation de Python, l'attention du téléspectateur n'est pas attirée sur l'option "Add Python to PATH", il s'agit d'une case à cocher qui rend accessible les programmes `python`, `py` et `pip` via la ligne de commande. Les débutants ne savent généralement pas comment changer les variables d'environnement sur Windows et se plaignent de ne pas réussir à lancer Python car `'python' n’est pas reconnu en tant que commande interne ou externe, un programme exécutable ou un fichier de commandes.`.
```

2021-08-23 16:55 UTC, Mesteery commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +Le tout premier snippet de code montré à l'écran est le suivant:
```suggestion
Le tout premier bout de code montré à l'écran est le suivant :
```

2021-08-23 16:55 UTC, Mesteery commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +Si il est commun de voir un `if __name__ == "__main__"` dans les projets Python, il n'est pas nécessaire et ne présente un intérêt qu'au moment où les modules sont introduits. Il aurait été plus judi
```suggestion
S'l est commun de voir un `if __name__ == "__main__"` dans les projets Python, il n'est pas nécessaire et ne présente un intérêt qu'au moment où les modules sont introduits. Il aurait été plus judicieux de ne pas l'introduire pour ne pas rajouter de la complexité inutile.
```

2021-08-23 16:55 UTC, Mesteery commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +Je regrette néanmoins que la fonction `type()` n'ait pas été introduite, elle aurait permis de construire la notion de type autrement que par la coloration syntaxique dans pycharm.
```suggestion
Je regrette néanmoins que la fonction `type()` n'ait pas été introduite, elle aurait permis de construire la notion de type autrement que par la coloration syntaxique.
```
ou de/dans Pycharm

2021-08-23 16:55 UTC, Mesteery commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +Les listes seront d'ailleurs les seules structures de données présentées dans la vidéo, pas un mot sur les dictionnaires, les sets ou la bibliothèque collections.
```suggestion
Les listes seront d'ailleurs les seules structures de données présentées dans la vidéo, pas un mot sur les dictionnaires, les sets ou la bibliothèque `collections`.
```

2021-08-23 16:55 UTC, Mesteery commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +Le `for` traditionnellement utilisé dans les langages comme C, Java (`for (int x = 0; x < 5; x++)`) n'existe pas en Python. Python n'est capable d'itérer que sur des objets itérables (ceux qui défini
```suggestion
Le `for` traditionnellement utilisé dans les langages comme C et Java (`for (int x = 0; x < 5; x++)`) n'existe pas en Python. Python n'est capable d'itérer que sur des objets itérables (ceux qui définissent les méthodes magiques `__iter__` ou/et `__next__`). `range` est un de ces objets, bien qu'à l'utilisation il permet de simuler le `for` classique, il n'en reste pas moins un objet qui implémente ces deux méthodes.
```

2021-08-23 16:55 UTC, Mesteery commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +En programmation orientée-objet, lorsqu'une fonction nécessite un contexte pour fonctionner, on préférera utiliser un objet pour sauvegarder ce contexte et écrire une *méthode*.
```suggestion
En programmation orientée objet, lorsqu'une fonction nécessite un contexte pour fonctionner, on préférera utiliser un objet pour sauvegarder ce contexte et écrire une *méthode*.
```

2021-08-23 16:55 UTC, Mesteery commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +L'auteur se trompe lorsqu'il dit qu'il est nécessaire de marquer les variables globales comme globales pour pouvoir y accéder. Il n'y a aucun problème à accéder en *lecture* (affichage, utilisation)
Personnellement j'ai pris du temps pour comprendre que tu parlais du mot-clé `global` dans une fonction

2021-08-23 16:55 UTC, Mesteery commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +Cependant, les bonnes pratiques de développement Python contrastent avec les bonnes pratiques d'autres langages de programmation orientée-objet comme Java, C# ou PHP. En Python, la notion d'accessibi
Peut-être utiliser un autre exemple que PHP ou l'enlever ? Disons que c'est pas aussi OOP que par exemple Java

2021-08-23 16:55 UTC, Mesteery commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +Les épisodes 8, 9 et 10 ne présentent pas de problème significatif.
```suggestion
Les épisodes 8, 9 et 10 ne présentent pas de problèmes significatifs.
```

2021-08-23 16:55 UTC, Mesteery commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +La visibilité en orienté-objet est une notion qui permet de contrôler *qui* a accès (en lecture, en écriture ou en exécution) aux attributs et aux méthodes d'un objet. Cette notion est implémentée da
```suggestion
La visibilité en orienté objet est une notion qui permet de contrôler *qui* a accès (en lecture, en écriture ou en exécution) aux attributs et aux méthodes d'un objet. Cette notion est implémentée dans nombre de langages orientés objet statiques comme Java, C# et C++. Lorsqu'un attribut est déclaré avec `private` elle n'est accessible que par l'objet courant, il en va de même pour les méthodes. Au contraire lorsqu'un attribut/une méthode est déclaré public, tout le monde peut y accéder.
```

2021-08-23 16:55 UTC, Mesteery commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +Dans la même lignée qu'il n'y a pas de notion de visibilité en Python, les pratiques de développement Python conseillent de directement modifier les attributs des objets sans passer par des méthodes
```suggestion
Dans la même lignée qu'il n'y a pas de notion de visibilité en Python, les pratiques de développement Python conseillent de directement modifier les attributs des objets sans passer par des méthodes de contrôle. Dit autrement, l'utilisation systématique d'accesseurs (*getters*) et de mutateurs (*setters*) est déconseillé.
```

2021-08-23 16:55 UTC, Mesteery commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +### Accesseurs, mutateur
```suggestion
### Accesseurs et mutateurs
```

2021-08-23 16:55 UTC, Mesteery commented on langages/python/critique-du-cours-video-sur-python-de-grave.md
> +Le cours est gangrené par les habitudes de développeur Java de l'auteur. Certains concepts essentiels dans le développement python sont complètements omis comme les dictionnaires, les sets, les génér
```suggestion
Le cours est gangrené par les habitudes de développeur Java de l'auteur. Certains concepts essentiels dans le développement Python sont complètements omis comme les dictionnaires, les sets, les générateurs ou la bibliothèque standard. Certains sont approximatifs comme les conditions ou les boucles. Les derniers introduisent des concepts qui vont à l'encontre des bonnes pratiques de développement en Python comme les fonctions ou les objets.
```

2021-08-23 16:55 UTC, Mesteery commented on langages/python/programmer-en-python-quel-ide-choisir.md
> +Python est dynamiquement typé. Bien qu'il existe des outils comme [mypy](mypy-lang.org) qui peuvent aider à la vérification des types, peu de modules tirent avantage de la bibliothèque `typing` et un
```suggestion
Python est dynamiquement typé. Bien qu'il existe des outils comme [mypy](mypy-lang.org) qui peuvent aider à la vérification des types, peu de modules tirent avantage de la bibliothèque `typing` et un IDE se retrouve fort peu utile pour avertir en cas d'incohérence de types.
```
ou s à warning

2021-08-23 19:52 UTC, Elanis commented on langages/python/programmer-en-python-quel-ide-choisir.md
> +* [Sublime text](https://www.sublimetext.com/3) (pro: léger et rapide, con: pas fort extensible)
J'ai update mon commentaire :)

2021-08-29 22:12 UTC, merged