Update issue templates
NotANameServer/Not-a-Hub pull request #28
Opened 2022-06-08 19:33 UTC by Elanis

2022-06-08 20:14 UTC, Equinox4 commented
Could we use a yaml file instead of markdown for "proposer-un-article"?
Yaml allows you to configure some things more finely, like adding a required field for example.

2022-06-10 07:51 UTC, Elanis commented
> Could we use a yaml file instead of markdown for "proposer-un-article"? Yaml allows you to configure some things more finely, like adding a required field for example.

Dunno how issues templates work tbh, used the default given thing.
I guess you're talking about [Issues forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) ?

I can convert existing templates in this PR to yaml I guess

2022-06-10 11:57 UTC, Equinox4 commented
Yes, I think you can just rename .md to .yml but I don't know yet how to preview the templates to check the rendering

2022-06-10 12:17 UTC, Elanis commented
I did switch to yaml, creating forms with https://issue-forms-creator.app/new

2022-06-10 12:27 UTC, Equinox4 requested changes
id is optionnal + automatically add labels on issue

2022-06-10 12:27 UTC, Equinox4 commented on .github/ISSUE_TEMPLATE/proposer-un-article.yaml
> +    id: sujet
```suggestion
```

2022-06-10 12:27 UTC, Equinox4 commented on .github/ISSUE_TEMPLATE/proposer-un-article.yaml
> +title: '[NOUVEL ARTICLE] '
```suggestion
title: '[NOUVEL ARTICLE] '
labels: ["article"]
```

2022-06-10 12:39 UTC, Equinox4 approved these changes

2022-06-10 12:41 UTC, Elanis commented
Thoughts @Julien00859 @arkena00 ?

2022-06-12 08:14 UTC, Elanis commented
If you feel there need another template, feel free to open an issue or a pull request

2022-06-12 08:15 UTC, merged