30 python module laz
NotANameServer/Not-a-Hub pull request #31
Opened 2022-06-20 23:52 UTC by Julien00859

Closes #30

2022-06-20 23:54 UTC, Julien00859 commented
Je n'ai pas encore pris le temps de squash mes commits ni de faire un beau message de commit. Je n'ai pas non plus pris le temps de hard-word-wrap les lignes sur 80 caractères. Je ferai tout ceci en fin de review, quand le texte sera plus stable.

2022-06-21 06:21 UTC, Elanis reviewed
Je ne peux pas review l'aspect technique très profondément n'étant pas dev python. Mais hormis les deux tournures de phrases que j'ai commenté, rien ne m'a sauté aux yeux.

2022-06-21 06:21 UTC, Elanis commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Dans cet article nous étudions les modules en python avec un regard poussé sur la notion de package. Nous étudions la manière de définir des modules et la manière de les importer de sorte à créer des
```suggestion
Dans cet article nous étudierons les modules en python avec un regard poussé sur la notion de package. Nous étudierons aussi la manière de définir des modules et la manière de les importer de sorte à créer des arborescences cohérentes et à prévenir certains problèmes, notamment les problèmes liés aux import relatifs.
```

2022-06-21 06:21 UTC, Elanis commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Le truc pourri en python par rapport aux packages est qu'un module python se trouvant dans un dossier n'aura pas forcément ce dossier comme package, même si le dossier en question possède un fichier
> Le truc pourri en python ...

Pas hyper fan de cette tournure de phrase, mais j'en ai pas d'autre en tête 😄

2022-06-21 07:54 UTC, ArthurVasseur commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Lorsqu'on est dans son propre logiciel, qu'on veut importer un fichier qui se trouve dans le même dossier, alors la question se pose. Mieux vaut-il préférer un import relatif ou bien un import absolu
```suggestion
Lorsqu'on est dans son propre logiciel, qu'on veut importer un fichier qui se trouve dans le même dossier, alors la question se pose. Mieux vaut-il préférer un import relatif ou bien un import absolu ? En fait, il n'y a pas de réponse définive à cette question, certains priviligeront des imports absolus, d'autres des imports relatifs, d'autres un judicieux mélange des deux en fonction des situations.
```

2022-06-21 08:19 UTC, ArthurVasseur reviewed
J'ai corrigé quelques fautes, mais sinon dans l'ensemble ça me parraît pas mal

2022-06-21 08:19 UTC, ArthurVasseur commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Il y a des situations où l'on n'a pas d'autre choix que d'utiliser un import absolu, par exemple lorsque ce qu'on importe ne se trouve pas dans le package courant ni dans le package parent. Par exemp
```suggestion
Il y a des situations où l'on n'a pas d'autre choix que d'utiliser un import absolu, par exemple lorsque ce qu'on importe ne se trouve pas dans le package courant ni dans le package parent. Par exemple, tous les modules de la bibliothèque standard ainsi que tous les modules qui ont été installés via pip ne peuvent être importés qu'avec un import absolu. Il n'y a pas d'autre moyen d'importer le module `random` que de taper `import random`.
```

2022-06-21 08:19 UTC, ArthurVasseur commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Le truc pourri en python par rapport aux packages est qu'un module python se trouvant dans un dossier n'aura pas forcément ce dossier comme package, même si le dossier en question possède un fichier
```suggestion
Le truc pourri en python par rapport aux packages est qu'un module python se trouvant dans un dossier n'aura pas forcément ce dossier comme package, même si le dossier en question possède un fichier `__init__.py`. En réalité, tout dépend de comment a été chargé le module en question. Nous avons vu plus haut, que les imports relatifs reposent sur le package du module courant et que ce nom de package était repris dans la variable magique `__package__` qui est propre à chaque module.
```

2022-06-21 08:19 UTC, ArthurVasseur commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Lorsqu'on est dans son propre logiciel, qu'on veut importer un fichier qui se trouve dans le même dossier, alors la question se pose. Mieux vaut-il préférer un import relatif ou bien un import absolu
```suggestion
Lorsqu'on est dans son propre logiciel, qu'on veut importer un fichier qui se trouve dans le même dossier, alors la question se pose. Mieux vaut-il préférer un import relatif ou bien un import absolu ? En fait, il n'y a pas de réponse définive à cette question, certains priviligeront des imports absolus, d'autres des imports relatifs, d'autres un judicieux mélange des deux en fonction des situations.
```

2022-06-21 08:19 UTC, ArthurVasseur commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Lorsqu'on est dans son propre logiciel, qu'on veut importer un fichier qui se trouve dans le même dossier, alors la question se pose. Mieux vaut-il préférer un import relatif ou bien un import absolu
Pour celle ci je suis pas sûr, c'est en fonction de la préférence de chacun

2022-06-21 08:19 UTC, ArthurVasseur commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Vous connaissez certainement les deux variables magiques `__file__` et `__name__`, ces deux variables sont définis automatiquement par python pour chaque module, la première contient le chemin comple
```suggestion
Vous connaissez certainement les deux variables magiques `__file__` et `__name__`, ces deux variables sont définies automatiquement par python pour chaque module, la première contient le chemin complet où se trouve le fichier sur le disque et la seconde contient le nom du module courant, relatif à la racine du projet.
```

2022-06-21 08:19 UTC, ArthurVasseur commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Il est rare de développer un projet qui ne va tenir que dans un seul module python, la plupart du temps un projet est implémenté au travers de plusieurs modules qui vont s'importer mutuellement et qu
```suggestion
Il est rare de développer un projet qui ne va tenir que dans un seul module python, la plupart du temps un projet est implémenté au travers de plusieurs modules qui vont s'importer mutuellement et qui sont regroupés dans différents dossiers. Tous ces modules regroupés en différents dossiers doivent pouvoir utiliser les fonctions et les classes qui sont définies dans les autres modules, il est donc important de pouvoir importer et de pouvoir être importé facilement. Python propose deux méchanismes pour importer des choses venant d'autres modules: les import relatifs (au package courant) et les import absolus (au `sys.path`).
```

2022-06-21 11:36 UTC, TitouanLMT reviewed
Au même titre que les autres, j'ai corrigé les fautes, sans répéter les corrections déjà relevées.

Je n'ai pas su trancher le fait qu'un manque de majuscule représente une faute ou non : `python` au lieu de `Python` par exemple. Je n'ai donc pas fait de remarque à ce sujet.

2022-06-21 11:36 UTC, TitouanLMT commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Dans le jargon python, un *package* est un dossier qui contient un fichier `__init__.py` et dans lequel se trouvent généralement d'autres modules python (des fichier se finissant en `.py`). Il n'y a
```suggestion
Dans le jargon python, un *package* est un dossier qui contient un fichier `__init__.py` et dans lequel se trouvent généralement d'autres modules python (des fichier se finissant en `.py`). Il n'y a qu'assez peu de packages dans la bibliothèque standard de python: `email`, `html`, `http`, `importlib`, `tkinter`, `unittest`, `urllib` et `xml`. Ils sont par contre très communs lorsqu'on regarde du côté des bilbiothèques hébergées sur pypi: `flask`, `numpy`, `matplotlib`, `requests`, `fastapi` et `sqlalchemy`; tous sont des packages où sont regroupés parfois jusqu'à plusieurs centaines de modules python.
```

2022-06-21 11:36 UTC, TitouanLMT commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Il est rare de développer un projet qui ne va tenir que dans un seul module python, la plupart du temps un projet est implémenté au travers de plusieurs modules qui vont s'importer mutuellement et qu
```suggestion
Il est rare de développer un projet qui ne va tenir que dans un seul module python, la plupart du temps un projet est implémenté au travers de plusieurs modules qui vont s'importer mutuellement et qui sont regroupés dans différents dossiers. Tous ces modules regroupés en différents dossiers doivent pouvoir utiliser les fonctions et les classes qui sont définis dans les autres modules, il est donc important de pouvoir importer et de pouvoir être importé facilement. Python propose deux méchanismes pour importer des choses venant d'autres modules : les import relatifs (au package courant) et les import absolus (au `sys.path`).
```

2022-06-21 11:36 UTC, TitouanLMT commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Lorsqu'on est dans son propre logiciel, qu'on veut importer un fichier qui se trouve dans le même dossier, alors la question se pose. Mieux vaut-il préférer un import relatif ou bien un import absolu
```suggestion
Lorsqu'on est dans son propre logiciel, qu'on veut importer un fichier qui se trouve dans le même dossier, alors la question se pose. Mieux vaut-il préférer un import relatif ou bien un import absolu ? Il n'y a en fait pas de réponse définitive à cette question, certains priviligeront des imports absolus, d'autres des imports relatifs, d'autres un judicieux mélange des deux en fonction des situations.
```

2022-06-21 11:36 UTC, TitouanLMT commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Le truc pourri en python par rapport aux packages est qu'un module python se trouvant dans un dossier n'aura pas forcément ce dossier comme package, même si le dossier en question possède un fichier
"L'inconvénient de la façon dont les imports des packages sont gérés en Python est..." peut-être ?

2022-06-21 11:36 UTC, TitouanLMT commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Il s'agit d'un package minimaliste, seulement deux fichiers: `__init__.py` et `__main__.py`, tous les deux exécutent la même instruction: afficher leur propre file, name et package. Petit rappel: lor
```suggestion
Il s'agit d'un package minimaliste, seulement deux fichiers : `__init__.py` et `__main__.py`, tous les deux exécutent la même instruction: afficher leur propre file, name et package. Petit rappel : lorsqu'un package est importé pour la première fois, son fichier `__init__.py` est exécuté. Deuxième petit rappel : lorsqu'un package ou un dossier est exécuté, son fichier `__main__.py` est exécuté.
```

2022-06-21 11:36 UTC, TitouanLMT commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Vous cherchiez une explication pourquoi dans vos propres projets vous aviez des erreurs du type "attempted relative import with no known parent package", ne cherchez plus. Parce que `__main__.py` a é
```suggestion
Vous cherchiez une explication sur pourquoi dans vos propres projets vous aviez des erreurs du type "attempted relative import with no known parent package", ne cherchez plus. Parce que `__main__.py` a été directement exécuté, python a décidé qu'il n'y avait pas de package et comme il n'y a pas de package il n'est pas possible de faire d'import relatif. Oui python est pourri à cet égard.
```

2022-06-21 11:36 UTC, TitouanLMT commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Vous cherchiez une explication pourquoi dans vos propres projets vous aviez des erreurs du type "attempted relative import with no known parent package", ne cherchez plus. Parce que `__main__.py` a é
> Oui python est pourri à cet égard.

Peut-être à reformuler au même titre qu'une remarque plus haut.

2022-06-21 11:36 UTC, TitouanLMT commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Dans ce second exemple, nous profitons du fait qu'il est possible d'exécuter un dossier via la ligne de commande. L'idée ici est de ne plus exécuter un fichier précis (ce qui mènerait à ce que ce fic
> On constate à nouveau que python est pourri à cet égard.

Même commentaire sur une potentielle reformulation.

2022-06-21 11:36 UTC, TitouanLMT commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Dans ce troisième exemple, nous ne lançons plus le programme directement via la ligne de commande, à la place nous invoquons l'interpréteur pour qu'il joue l'instruction `import monpkg.__main__`. L'i
```suggestion
Dans ce troisième exemple, nous ne lançons plus le programme directement via la ligne de commande, à la place nous invoquons l'interpréteur pour qu'il joue l'instruction `import monpkg.__main__`. L'idée ici est de contourner les bizzareries de la ligne de commande pour à la place `import` notre package. Nous constatons que grâce à cette petite astuce, cette fois-ci, le package est bien correctement chargé : les variables `__package__` contiennent ce qu'on s'attend à voir et les fichier `__init__.py` a été chargé à la volée. Le seul bémol est que le `__name__` du fichier `__main__.py` atteste `monpkg.__main__` et non pas simplement `__main__`. Ce comportement s'explique par le fait que ce qui s'appelle `__main__` dans ce contexte est ce qui a été exécuté en premier lieu : l'instruction contenue dans le `-c` de la ligne de commande.
```

2022-06-21 11:36 UTC, TitouanLMT commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Dans ce quatrième et dernier exemple, nous lançons le programme au moment de l'option `-m` de la ligne de commande. Cette option est succintement décrite comme "run library module as a script" dans l
```suggestion
Dans ce quatrième et dernier exemple, nous lançons le programme au moment de l'option `-m` de la ligne de commande. Cette option est succintement décrite comme "run library module as a script" dans le manuel de python. La réalité est beaucoup plus intéressante que ne le laisse entendre la toute petite phrase du manuel, on constate qu'en utilisant cette option le package est enfin chargé de la manière escompté : le package est chargé, les variables `__name__` et `__package__` sont justes et nous n'avons pas eu recours à un quelconque artifice (un module en plus dont le seul but était d'`import` notre main).
```

2022-06-21 11:36 UTC, TitouanLMT commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +La notion de *package* est une notion qui est mal comprise de la part des développeurs python, autant novices qu'avancés. Cette notion est cependant priomordiale pour correctement comprendre comment
```suggestion
La notion de *package* est une notion qui est mal comprise de la part des développeurs python, autant novices qu'avancés. Cette notion est cependant primordiale pour correctement comprendre comment fonctionnent les imports relatifs et donc comment structurer et exécuter ses projets.
```

2022-06-21 13:42 UTC, Julien00859 commented
Pour moi *pourri* et *bémol* doivent rester, je tiens à vraiment attirer l'attention sur ce sujet

2022-06-21 14:03 UTC, Julien00859 commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Le truc pourri en python par rapport aux packages est qu'un module python se trouvant dans un dossier n'aura pas forcément ce dossier comme package, même si le dossier en question possède un fichier
Nop, pas d'accord ici

2022-06-21 14:06 UTC, Julien00859 commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Dans ce troisième exemple, nous ne lançons plus le programme directement via la ligne de commande, à la place nous invoquons l'interpréteur pour qu'il joue l'instruction `import monpkg.__main__`. L'i
Ok pour contourner et les :, j'ai pas changé bémol

2022-06-21 14:08 UTC, Julien00859 commented
Alors j'ai bien lu votre avis à tous les trois à propos de "pourri" et "bémol". J'aimerais trouver une manière efficace pour marquer le coup que la manière intuitive (`python3 monpkg/__main__.py`) est un pitfall et qu'il faut absolument l'éviter.

2022-06-21 14:35 UTC, Nolent requested changes

2022-06-21 14:35 UTC, Nolent commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Il y a des situations où l'on n'a pas d'autre choix que d'utiliser un import absolu, par exemple lorsque ce qu'on importe ne se trouve pas dans le package courant ni dans le package parent. Par exemp
>ni dans le package parent

Pour être plus exacte, il faudrait plutot dire "l'un des parents". Rien empeche de faire `...un.autre.package.du.project`, en plus tu donnes un exemple de ce type plus bas.

2022-06-21 17:30 UTC, Equinox4 requested changes, later dismissed

2022-06-21 17:30 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Dans cet article nous étudierons les modules en python avec un regard poussé sur la notion de package. Nous étudierons aussi la manière de définir des modules et la manière de les importer de sorte à
```suggestion
Dans cet article, nous étudierons les modules en python avec un regard poussé sur la notion de package. Nous étudierons aussi la manière de définir des modules et la manière de les importer de sorte à créer des arborescences cohérentes et à prévenir certains problèmes, notamment les problèmes liés aux import relatifs.
```

2022-06-21 17:30 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Vous connaissez certainement les deux variables magiques `__file__` et `__name__`, ces deux variables sont définies automatiquement par python pour chaque module, la première contient le chemin compl
```suggestion
Vous connaissez certainement les deux variables magiques `__file__` et `__name__`. Ces deux variables sont définies automatiquement par python pour chaque module, la première contient le chemin complet où se trouve le fichier sur le disque et la seconde contient le nom du module courant, relatif à la racine du projet.
```

2022-06-21 17:30 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Dans le jargon python, un *package* est un dossier qui contient un fichier `__init__.py` et dans lequel se trouvent généralement d'autres modules python (des fichier se finissant en `.py`). Il n'y a
```suggestion
Dans le jargon python, un *package* est un dossier qui contient un fichier `__init__.py` et dans lequel se trouvent généralement d'autres modules python (des fichiers se finissant en `.py`). Il n'y a qu'assez peu de packages dans la bibliothèque standard de python: `email`, `html`, `http`, `importlib`, `tkinter`, `unittest`, `urllib` et `xml`. Ils sont par contre très communs lorsqu'on regarde du côté des bibliothèques hébergées sur pypi: `flask`, `numpy`, `matplotlib`, `requests`, `fastapi` et `sqlalchemy`; tous sont des packages où sont regroupés parfois jusqu'à plusieurs centaines de modules python.
```

2022-06-21 17:30 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Il est rare de développer un projet qui ne va tenir que dans un seul module python, la plupart du temps un projet est implémenté au travers de plusieurs modules qui vont s'importer mutuellement et qu
```suggestion
Il est rare de développer un projet qui ne va tenir que dans un seul module python, la plupart du temps un projet est implémenté au travers de plusieurs modules qui vont s'importer mutuellement et qui sont regroupés dans différents dossiers. Tous ces modules regroupés en différents dossiers doivent pouvoir utiliser les fonctions et les classes qui sont définies dans les autres modules, il est donc important de pouvoir importer et de pouvoir être importé facilement. Python propose deux méchanismes pour importer des choses venant d'autres modules : les imports relatifs (au package courant) et les imports absolus (au `sys.path`).
```
je mets un 's' ici, mais ça dépend de ce que tu veux dire, soit tu dis "import" à l'anglaise, soit tu utilises le nom import (qui s'accorde dans ce cas), les deux sont valides, mais j'ai une préférence personnelle pour ne pas mélanger les mots anglais et français
(d'ailleurs plus bas tu dis bien "les imports")

2022-06-21 17:30 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Dans ce troisième exemple, nous ne lançons plus le programme directement via la ligne de commande, à la place nous invoquons l'interpréteur pour qu'il joue l'instruction `import monpkg.__main__`. L'i
```suggestion
Dans ce troisième exemple, nous ne lançons plus le programme directement via la ligne de commande, à la place nous invoquons l'interpréteur pour qu'il joue l'instruction `import monpkg.__main__`. L'idée ici est de contourner les bizzareries de la ligne de commande pour à la place `import` notre package. Nous constatons que grâce à cette petite astuce, cette fois-ci, le package est bien correctement chargé : les variables `__package__` contiennent ce qu'on s'attend à voir et le fichier `__init__.py` a été chargé à la volée. Le seul bémol est que le `__name__` du fichier `__main__.py` atteste `monpkg.__main__` et non pas simplement `__main__`. Ce bémol s'explique par le fait que ce qui s'appelle `__main__` dans ce contexte est ce qui a été exécuté en premier lieu : l'instruction contenue dans le `-c` de la ligne de commande.
```

2022-06-21 17:30 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +La notion de *package* est une notion qui est mal comprise de la part des développeurs python, autant novices qu'avancés. Cette notion est cependant primordiale pour correctement comprendre comment f
```suggestion
La notion de *package* est mal comprise par les développeurs python, autant novices qu'avancés. Cette notion est cependant primordiale pour correctement comprendre comment fonctionnent les imports relatifs et donc comment structurer et exécuter ses projets.
```
pour éviter les répétitions du style "cette notion est une notion qui a une notion de"

2022-06-21 17:32 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Vous connaissez certainement les deux variables magiques `__file__` et `__name__`, ces deux variables sont définies automatiquement par python pour chaque module, la première contient le chemin compl
une petite pause car la phrase est vraiment longue avec 3 virgules

2022-06-21 17:42 UTC, Julien00859 commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Vous connaissez certainement les deux variables magiques `__file__` et `__name__`, ces deux variables sont définies automatiquement par python pour chaque module, la première contient le chemin compl
j'ai vu, je pense plutôt mettre le point à la place de la seconde virgule

2022-06-21 18:39 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Vous connaissez certainement les deux variables magiques `__file__` et `__name__`, ces deux variables sont définies automatiquement par python pour chaque module, la première contient le chemin compl
yep, ça fonctionne aussi

2022-06-21 18:45 UTC, Oedipsos reviewed
Corrections d'orthographe random. Rien de bien fameux, mais cependant nécéssaires à mes yeux :)

2022-06-21 18:45 UTC, Oedipsos commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Nous pouvons regretter que le chapitre qui aborde les modules dans [le tutoriel officielle][pydoc/tuto/module] de python soit approximatif. Nous pouvons aussi regretter que faute de resources complèt
> le tutoriel officielle

offic**iel**

> que de piètre informations

piètre**s**

>

2022-06-21 18:45 UTC, Oedipsos commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Dans ce quatrième et dernier exemple, nous lançons le programme au moment de l'option `-m` de la ligne de commande. Cette option est succintement décrite comme "run library module as a script" dans l
> de la manière escompté

escompté**e**

> un module en plus dont le seul but était d'`import` notre main

J'emploierais plutôt le conditionnel "serait" ici, vu que ce module n'a pas dû être créé.

2022-06-21 18:45 UTC, Oedipsos commented on langages/python/relatif-vs-absolu-demystifion-les-import-python.md
> +Lorsqu'on est dans son propre logiciel, qu'on veut importer un fichier qui se trouve dans le même dossier, alors la question se pose. Mieux vaut-il préférer un import relatif ou bien un import absolu
>  certains priviligeront des imports absolus

privil**égieront**

2022-06-22 21:32 UTC, Julien00859 commented
Avec la collaboration de @backjlack je me suis rendu compte que plein de choses n'allaient pas du coup je réécris tout :grimacing:

2022-06-27 16:36 UTC, Elanis commented on langages/python/relatif-vs-absolu-demystifions-les-imports-python.md
> +### Exécuter le package avec – m
```suggestion
### Exécuter le package avec –m
```

2022-06-27 16:38 UTC, Elanis reviewed
J'ai laissé un seul commentaire, et comme auparavant, j'ai pas la compétence pour juger du contenu concernant python, seulement de la logique générique et de la rédaction ;)

2022-06-27 16:47 UTC, Julien00859 commented
Un grand merci Elanis pour ta relecture, même si tu ne peux pas relire pour la technique ça en fait au moins un qui a relu pour l'orthographe et la typographie en général :)

2022-06-27 17:18 UTC, Equinox4 requested changes

2022-06-27 17:18 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifions-les-imports-python.md
> +Lorsque vous écrivez `import x` ou `from x import y`, vous faites un import absolu. La bibliothèque (le module ou le package) doit se trouver soit dans le *working-directory*, soit être installée dan
```suggestion
Lorsque vous écrivez `import x` ou `from x import y`, vous faites un import absolu. La bibliothèque (le module ou le package) doit se trouver soit dans le *working-directory*, soit être installée dans l'environnement virtuel courant, soit être installée au niveau de l'utilisateur, soit être installée au niveau du système. Python scanne ces différentes sources à la recherche de la bibliothèque demandée pour l'importer. Si après avoir scanné l'ensemble des sources possibles python ne trouve pas la bibliothèque demandée alors il lève une erreur du type `ModuleNotFoundError: No module named 'x'`.
```

2022-06-27 17:18 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifions-les-imports-python.md
> +Si au moment de jouer l'instruction `from . import x`, le moment courant n'était pas lié à un quelconque package (sa variable `__package__` était vide), l'erreur suivante se serait produite : `Import
```suggestion
Si au moment de jouer l'instruction `from . import x`, le module courant n'était pas lié à un quelconque package (sa variable `__package__` était vide), l'erreur suivante se serait produite : `ImportError: attempted relative import with no known parent package`. L'erreur dénote l'impossibilité de faire un import relatif du fait que le module courant n'est pas lié à un package.
```

2022-06-27 17:18 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifions-les-imports-python.md
> +Nous venons de voir les notions de package, d'import absolu et d'import relatif. Nous avons vu qu'un package était un dossier avec un fichier `__init__.py`, que les imports absolus reposaient sur le
```suggestion
Nous venons de voir les notions de package, d'import absolu et d'import relatif. Nous avons vu qu'un package est un dossier contenant un fichier `__init__.py`, que les imports absolus reposent sur le `sys.path` et que les imports relatifs reposent sur la variable `__package__`.
```

2022-06-27 17:18 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifions-les-imports-python.md
> +Nous venons de voir les notions de package, d'import absolu et d'import relatif. Nous avons vu qu'un package était un dossier avec un fichier `__init__.py`, que les imports absolus reposaient sur le
c'est toujours le cas actuellement, imo le présent est plus approprié ici

2022-06-27 17:18 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifions-les-imports-python.md
> +Notre intuition de développeur fait que nous pensons qu'un package est dossier contenant des modules python, avec un artefact supplémentaire : le fichier `__init__.py`. En suivant notre intuition nou
```suggestion
Notre intuition de développeur fait que nous pensons qu'un package est un dossier contenant des modules python, avec un artefact supplémentaire : le fichier `__init__.py`. En suivant notre intuition nous pensons donc qu'à partir du moment où un fichier se trouve dans un tel dossier, il aura forcément une variable `__package__` contenant le nom du dossier.
```

2022-06-27 17:18 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifions-les-imports-python.md
> +Il s'agit d'un package minimaliste, seulement trois fichiers : `__init__.py`, `__main__.py` et `tartempion.py`. Les trois fichiers exécutent la même instruction : afficher leurs propres variables fil
```suggestion
Il s'agit d'un package minimaliste, seulement trois fichiers : `__init__.py`, `__main__.py` et `tartempion.py`. Les trois fichiers exécutent la même instruction : afficher leurs propres variables `__file__`, `__name__` et `__package__`.
```

2022-06-27 17:18 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifions-les-imports-python.md
> +Il s'agit d'un package minimaliste, seulement trois fichiers : `__init__.py`, `__main__.py` et `tartempion.py`. Les trois fichiers exécutent la même instruction : afficher leurs propres variables fil
puisque ce sont des variables, autant conserver leurs noms exacts dans l'explication

2022-06-27 17:18 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifions-les-imports-python.md
> +Rappelons que lorsque un *package* est importé (lorsque vous faites `import monpkg`), le fichier `__init__.py` est automatiquement joué. Rappelons aussi que lorsqu'un *dossier* est exécuté (lorsque v
```suggestion
Rappelons que lorsqu'un *package* est importé (lorsque vous faites `import monpkg`), le fichier `__init__.py` est automatiquement joué. Rappelons aussi que lorsqu'un *dossier* est exécuté (lorsque vous faites `python3 monpkg`), le fichier `__main__.py` est automatiquement joué.
```

2022-06-27 17:18 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifions-les-imports-python.md
> +Nous constatons que ni le fichier `__init__.py` ni le fichier `__main__.py` n'ont été exécuté automatiquement. Le fichier `__init__.py` n'a pas été exécuté parce que le package n'a pas été importé. L
```suggestion
Nous constatons que ni le fichier `__init__.py` ni le fichier `__main__.py` n'ont été exécutés automatiquement. Le fichier `__init__.py` n'a pas été exécuté parce que le package n'a pas été importé. Le fichier `__main__.py` n'a pas été exécuté parce le dossier n'a pas été exécuté.
```

2022-06-27 17:18 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifions-les-imports-python.md
> +Nous constatons pour finir que le module n'est pas rattaché à un quelconque package comme le fichier `__init__.py` n'a pas été chargé. Les imports relatifs ne fonctionneront pas dans le cas présent p
```suggestion
Nous constatons pour finir que le module n'est pas rattaché à un quelconque package puisque le fichier `__init__.py` n'a pas été chargé. Les imports relatifs ne fonctionneront pas dans le cas présent pour le module tartempion.
```
je trouve la formulation avec 'comme' un peu chelou

2022-06-27 17:18 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifions-les-imports-python.md
> +Il nous est forcé de constater, qu'encore une fois le fichier `__init__.py` n'a pas été automatiquement chargé. De ce fait la variable `__package__` est vide et les imports relatifs ne fonctionneront
```suggestion
Force nous est de constater qu'encore une fois le fichier `__init__.py` n'a pas été automatiquement chargé. De ce fait la variable `__package__` est vide et les imports relatifs ne fonctionneront toujours pas.
```
l'expression c'est "force est de constater" et non pas "forcé de constater" (et btw c'est plutot soutenu comme parler mais bon x))

2022-06-27 17:18 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifions-les-imports-python.md
> +Nous constatons cette fois-ci que les deux fichiers `__init__.py` et `__main__.py` ont bien chacun été chargé et exécuté. Nous constatons également que chacun des deux modules partagent une variable
```suggestion
Nous constatons cette fois-ci que les deux fichiers `__init__.py` et `__main__.py` ont bien chacun été chargés et exécutés. Nous constatons également que chacun des deux modules partagent une variable `__package__` défini au nom du dossier. Nous sommes enfin dans une situation où les imports relatifs vont fonctionner.
```

2022-06-27 17:18 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifions-les-imports-python.md
> +Nous constatons cette fois-ci que les deux fichiers `__init__.py` et `__main__.py` ont bien chacun été chargé et exécuté. Nous constatons également que chacun des deux modules partagent une variable
"ont été", verbe être -> accord

2022-06-27 17:18 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifions-les-imports-python.md
> +Notez que la ligne `import monpkg.__main__` fait un import absolu. Il fonctionne dans le cas présent car le package `monpkg` se trouve dans le working directory. Pour que le fichier `run.py` puisse ê
```suggestion
Notez que la ligne `import monpkg.__main__` fait un import absolu. Il fonctionne dans le cas présent car le package `monpkg` se trouve dans le working directory. Pour que le fichier `run.py` puisse être exécuté de partout, même depuis un dossier différent ce celui où ce fichier se trouve, il faut modifier le `sys.path` manuellement *avant* d'importer le package :
```

2022-06-27 17:18 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifions-les-imports-python.md
> +    ~ $ python3 – m monpkg
```suggestion
    ~ $ python3 –m monpkg
```

2022-06-27 17:18 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifions-les-imports-python.md
> +    ~ $ python3 – m monpkg
attention ici, en plus de l'espace, il s'agit du caractère "–" (tiret, ou en-dash) au lieu du caractère "-"  (moins)
vérifier aussi les autres endroits de l'article où on montre des options
dans le cas où c'est voulu, j'ai simplement retiré l'espace sans remplacer le caractère

2022-06-27 17:18 UTC, Equinox4 commented on langages/python/relatif-vs-absolu-demystifions-les-imports-python.md
> +Dans ce tout dernier exemple nous constatons à nouveau que les deux fichiers ont été chargés et exécutés. Nous constatons à nouveau que la variable `__package__` est correctement défini et que donc l
```suggestion
Dans ce tout dernier exemple nous constatons à nouveau que les deux fichiers ont été chargés et exécutés. Nous constatons à nouveau que la variable `__package__` est correctement définie et donc que les imports relatifs vont fonctionner. En bonus par rapport à la solution précédente, nous n'avons pas dû recourir à artifice supplémentaire dont le seul rôle était d'importer notre programme.
```

2022-06-27 17:23 UTC, Elanis commented
Mjölnir a plus vu que moi ahah ... Pas bon de relire en fin de journée x)

2022-06-27 18:45 UTC, Equinox4 approved these changes

2022-06-27 19:27 UTC, Elanis approved these changes

2022-06-27 19:45 UTC, merged