Programmer en Scala 3: Types et variables
NotANameServer/Not-a-Hub pull request #36
Opened 2022-07-27 13:04 UTC by Iltotore

Introduction to variables and basic data types in Scala

2022-08-01 09:15 UTC, Julien00859 commented
Hello, je lire une première fois et donner un premier retour dans l'après-midi/la soirée :)

2022-08-01 09:16 UTC, Julien00859 commented
Btw, pour citer quelqu'un sur git tu peux ajouter ceci à ton message de commit:

    Co-Authored-By: name <email>

2022-08-01 16:25 UTC, Julien00859 reviewed
Pour moi l'audience n'est pas correctement identifiée. Soit l'audience est des parfaits débutants et alors cet article leur fait se poser beaucoup plus de questions qu'il n'en vient en répondre. Soit l'audience est des utilisateurs plus confirmés et alors il serait judicieux de faire des parallèles avec d'autres langages existants.

https://github.com/NotANameServer/Not-a-Hub/issues/35#issuecomment-1201424674

2022-08-01 16:25 UTC, Julien00859 commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +Le langage met à notre disposition plusieurs types "de base":
C'est bien de parler de types mais c'est peut-être mieux d'introduire la notion de mémoire au préalable. On ne manipule pas des types pour le plaisir, on veut en fait sauvegarder et manipuler des données en mémoire. Que lorsqu'on peut juste faire la différence entre "basse-tension" (0) et "haut-tension" (1), on a du être malin et *inventer* une manière de *représenter* de l'information en utilisant juste du binaire.

2022-08-01 16:25 UTC, Julien00859 commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +| Double  | Un nombre à virgule sur huit octets   | Entre 4.94065645841246544e-324 et 1.79769313486231570e+308, type décimal par défaut |
Il faut rester cohérent, pour byte tu as donné les limites exactes, pour short/int/long tu as exprimé le nombre en terme de puissance de 2, pour float/double tu as exprimé le nombre en terme de puissance de 10. Aussi je me permets de poser la question sur l'utilité de présenter tous les types numériques, au final seuls Int et Double sont généralement utilisés. Ne donner qu'un type pour les entiers et un type pour les flottants permet de ne pas avoir à répondre à la question "dans quels cas je dois utiliser Byte plutôt que Int ?", "c'est grave si on gaspille de la mémoire et qu'on utilise Int partout ?".

2022-08-01 16:25 UTC, Julien00859 commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +### Opérations arithmétiques
C'est peut-être moi qui ai une vision très *dynamique* (par opposition à statique) mais pour exécuter les quelques lignes de code ci-dessous je ne pense pas qu'on a besoin de connaitre Int Boolean Double ou String. Tu dis "`println` ça affiche en console" et puis tu fais `1 + 1`, mis à part si le gars est totalement teubé, il comprendra qu'on fait un calcul et qu'on affiche le résultat.

Les seules choses importantes à expliquer c'est que le texte doit être entre `"` et que `true` et `false` représentent vrai et faux et qu'on peut faire des maths (booléenne) sur ça aussi.

Attention, concernant les Booleans, c'est pas forcément évident pour tout le monde de mélanger `et` et `ou`. En français courant l'un et l'autre sont parfois mélangés et le parfait débutant peut être dérouté par l'arithmétique booléenne. Peut-être réserver ce type lorsque les conditions seront introduites.

2022-08-01 16:25 UTC, Julien00859 commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +### Muabilité et immuabilité
Attention à ne pas introduire trop de vocabulaire, j'ai pas besoin de savoir que ça s'appelle "mutable" et "immuable", j'ai juste besoin de savoir que `var` je peux changer, `val` c'est constant.

> Les variables nous permettent de palier à ce problème en stockant des valeurs que nous pouvons réutiliser.

C'est beaucoup trop court comme introduction de ce qu'est une variable. La notion de "variable" est crucial et élémentaire en informatique, surtout dans un langage qui peut s'utiliser au travers des paradigmes orienté objet et impératif.

2022-08-01 16:25 UTC, Julien00859 commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +En général, on utilise `val` sauf si on a une bonne raison de modifier la variable plus tard, auquel cas on utilise `var`.
Si on utilise pas `var`, à quoi ça sert de le montrer ? Encore une fois, montrer que le choix est possible va forcer l'étudiant à se poser systématiquement la question "ici, je dois utiliser `val` ou `var` ?". Construisez votre cours/tutoriel de manière à systématiquement privilégier l'un ou l'autre pour pouvoir décaler le moment fatidique où il faudra monter *l'autre* que bien plus tard : lorsque l'étudiant aura bien compris ce qu'est qu'une variable et comment s'en servir.

2022-08-01 16:27 UTC, Julien00859 commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +Le langage met à notre disposition plusieurs types "de base":
Pas besoin de faire hyper-compliqué, juste dire qu'un type c'est une manière de représenter de l'info en mémoire est suffisant. Montrer un exemple avec des nombres entiers et un autre exemple avec la table ascii c'est parfait.

2022-08-05 10:38 UTC, Iltotore commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +Le langage met à notre disposition plusieurs types "de base":
> C'est bien de parler de types mais c'est peut-être mieux d'introduire la notion de mémoire au préalable

Donc tu verrais la notion de type après les variables ? Même dans un typage statique comme en Scala c'est loin d'être aberrant étant donné qu'on a de l'inférence de type.

2022-08-05 16:18 UTC, Julien00859 commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +Le langage met à notre disposition plusieurs types "de base":
Je ne sais pas trop... propose quelque chose on verra bien :D

2022-08-06 16:18 UTC, Equinox4 commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +- `println` qui sert à afficher un texte
peut être préciser que ça affiche un texte en y ajoutant un retour à la ligne (d'ou le ln) ?

2022-08-06 16:18 UTC, Equinox4 commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +| Double  | Un nombre à virgule sur huit octets   | Entre 4.94065645841246544e-324 et 1.79769313486231570e+308, type décimal par défaut |
Je suis d'accord, on pourra éventuellement préciser qu'il existe d'autres types mais sans forcément tous les énumérer. D'ailleurs, ce tableau n'est déjà pas exhaustif si j'en crois la doc https://docs.scala-lang.org/scala3/book/first-look-at-types.html

2022-08-06 16:18 UTC, Equinox4 commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +Le "non" booléen bascule simplement la valeur de notre booléen :
bascule ?
j'aurais plutôt dis "inverse"

2022-08-06 16:18 UTC, Equinox4 commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +println("1+2 = " + (1+2)) // 1+2 = 3
```suggestion
println("1+2 = " + (1 + 2)) // 1+2 = 3
```

2022-08-06 16:18 UTC, Equinox4 commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +Ces variables ont la capacité de pouvoir être changées :
```suggestion
La valeur de ces variables peut être changée :
```

2022-08-06 16:18 UTC, Equinox4 commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +Les variables _immuables_ se déclarent avec le mot-clé `val`. Elles ne peuvent pas être modifiées.
```suggestion
Les variables _immuables_ se déclarent avec le mot-clé `val`. Leur valeur ne peut pas être modifiée.
```
je pense qu'il faut utiliser un vocabulaire aussi précis que possible pour éviter toute confusion.

2022-08-06 16:18 UTC, Equinox4 commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +Les variables ne font pas exception à cette règle ! Elles ont toutes un type. Il est interdit d'assigner à une variable muable une valeur du mauvais type.
> une valeur du mauvais type
vague, c'est quoi un mauvais type ?
pourrait être reformulé, plutôt dire qu'un variable déclarée comme étant d'un certain type ne peut pas se voir assigner une valeur d'un type différent de ce qui a été déclaré.

2022-08-06 16:18 UTC, Equinox4 commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +Le compilateur trouve tout seul le type des variables, on dit qu'il _infère_ leur type. On  peut aussi expliciter le type avec la syntaxe suivante :
```suggestion
Le compilateur trouve tout seul le type des variables, on dit qu'il _infère_ leur type. On peut aussi expliciter le type avec la syntaxe suivante :
```
pour le coups j'aurais présenté l'inférence de type après la déclaration explicite, ça me semble plus logique

2022-08-06 16:18 UTC, Equinox4 commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +### Opérations arithmétiques
concernant les sections ci-dessous, je n'ai pas lu une seule fois le mot "opérateur", qui me semble pourtant essentiel et que l'on retrouve dans la plupart des documentions, je ne sais pas si c'est voulu.
Perso si j'étais débutant j'aurais aimé savoir comment ça s'appelle tout ça "+-*/|&||&&!"

2022-08-07 12:06 UTC, TheElectronWill commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +Les variables ne font pas exception à cette règle ! Elles ont toutes un type. Il est interdit d'assigner à une variable muable une valeur du mauvais type.
Ce serait inexact de dire ça, on peut assigner une valeur d'un sous-type ^^

"mauvais type" c'est imprécis mais c'est la bonne idée ; "incompatible" serait peut-être mieux.

2022-08-13 10:10 UTC, TheElectronWill commented
Il faut sauter une ligne avant `Co-authored-by` apparemment :) @Iltotore

2022-08-13 15:46 UTC, TheElectronWill commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +### Opérations arithmétiques
ajouté

2022-08-13 16:50 UTC, Iltotore commented
L'article a complètement été réécrit avec @TheElectronWill pour être plus adapté aux néophytes complets (qui sont la cible principale de cette suite d'articles).

- Il y a maintenant en introduction une explication sur le fonctionnement de la mémoire, son importance, et l'utilité des variables.
- Les booléens ont été reportés au prochain article sur les conditions, là où ils commenceront à être utiles
- Parmi les types numériques, seuls les principaux (Int et Double) sont gardés
- @TheElectronWill a fait deux illustrations pour expliquer le fonctionnement (en surface) de la mémoire et l'utilité des variables. Notons que je les ai nommées sur le repo assez génériquement pour permettre leur réutilisation pour l'introduction aux variables dans d'autres langages.

2022-08-13 16:53 UTC, Iltotore commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +- `println` qui sert à afficher un texte
Ca ne m'a pas traversé l'esprit mais je ne pense pas que ce soit nécessaire. Cette partie a de toute façon été enlevée dans la nouvelle version. Je préciserai quand on reparlera des fonctions.

2022-08-13 16:54 UTC, Iltotore commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +Le "non" booléen bascule simplement la valeur de notre booléen :
Reporté aux conditions

2022-08-13 16:54 UTC, Iltotore commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +Les variables _immuables_ se déclarent avec le mot-clé `val`. Elles ne peuvent pas être modifiées.
Reporté à quand elles deviendront utiles.

2022-08-13 16:56 UTC, TheElectronWill commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +- `println` qui sert à afficher un texte
je l'ai ajouté :)

2022-08-13 16:58 UTC, Iltotore commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +Le compilateur trouve tout seul le type des variables, on dit qu'il _infère_ leur type. On  peut aussi expliciter le type avec la syntaxe suivante :
C'est ce qui m'a paru avant d'écrire l'article mais comme finalement on omet très souvent le type de la variable en Scala plutôt que de l'expliciter, j'ai préféré le mettre après.

Notons aussi qu'un débutant n'a pas forcément besoin de savoir tout de suite que l'on peut expliciter le type, notamment parce que nous n'avons pas introduit pour l'instant les variables muables.

2022-08-13 17:04 UTC, TheElectronWill commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +![variables typées](https://i.imgur.com/JeUaAxO.png)
il reste un lien imgur ici :)

2022-08-13 18:39 UTC, Iltotore commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +![variables typées](https://i.imgur.com/JeUaAxO.png)
Fait

2022-08-14 16:07 UTC, Julien00859 approved these changes
J'ai un bien meilleur feeling avec ce qui est écrit maintenant :)

2022-08-14 17:43 UTC, Iltotore commented
J'attend @Equinox4 avant de merge étant donné qu'il a aussi relevé plusieurs points à améliorer sur l'ancien jet.

2022-08-15 11:12 UTC, Equinox4 requested changes

2022-08-15 11:12 UTC, Equinox4 commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +Nous aborderons dans le cours suivant qui portera sur les conditions.
problème de formulation, je pense qu'il doit manquer des mots ici

2022-08-15 12:02 UTC, Iltotore commented on langages/scala/programmer-en-scala-3-types-et-variables.md
> +Nous aborderons dans le cours suivant qui portera sur les conditions.
Je m'en occupe

2022-08-15 12:05 UTC, Equinox4 approved these changes

2022-08-15 12:05 UTC, Equinox4 commented
c'est good pour moi :)

2022-08-15 12:17 UTC, merged