add: les idées reçues sur C
NotANameServer/Not-a-Hub pull request #42
Opened 2022-10-15 16:32 UTC by AllanBlanchard

2022-10-15 18:44 UTC, Equinox4 commented on langages/c/debunk-c.md
> +Quel est maintenant le rapport avec C ? Et, bien tristement, il y en a assez peu.
```suggestion
Quel est maintenant le rapport avec C ? Et bien, tristement, il y en a assez peu.
```

2022-10-15 18:44 UTC, Equinox4 commented on langages/c/debunk-c.md
> +d'y voir un peu plus clair dans tout ça, cet article propose de passer en revue
Je pense qu'on peut reformuler pour éviter la répétition "tout ça" "tout cela"

2022-10-15 18:44 UTC, Equinox4 commented on langages/c/debunk-c.md
> +Commençons par une mauvaise métaphore (il n'y a pas de raison que je n'ai pas le
Effectivement, c'est une mauvaise métaphore 😄

2022-10-15 18:44 UTC, Equinox4 commented on langages/c/debunk-c.md
> +Le précédent point nous amène au fait que C serait un très bon langage pour
```suggestion
Le précédent point nous amène à l'affirmation selon laquelle C serait un très bon langage pour
```
Combiner le mot "fait", qui indique qq chose de factuel avec du conditionnel "serait", je trouve ça bizarre

2022-10-15 18:44 UTC, Equinox4 commented on langages/c/debunk-c.md
> +Des fonctionnalités aussi basiques que la saisie de valeur entière n'est pas si
```suggestion
Une fonctionnalité aussi basique que la saisie d'une valeur entière n'est pas si
```

2022-10-15 18:44 UTC, Equinox4 commented on langages/c/debunk-c.md
> +dans quel état. Et les cours sont généralement très évasifs à ce sujet parce que
```suggestion
des flux pose énormément de problèmes. Notamment pour connaître l'état du flux à un instant donné. Et les cours sont généralement très évasifs à ce sujet parce que
```
j'ai un doute sur le sens du mot "quand" ici
"quand" dans le sens "quand-est ce que" ou "quand" dans le sens "lorsqu'il est dans tel état" ?

2022-10-15 18:44 UTC, Equinox4 commented on langages/c/debunk-c.md
> +comprendre. Au contact de débutants, on constate d'ailleurs que la manipulation
peut-être ajouter une ligne ou deux pour expliquer quelle est l'erreur ici ?

2022-10-15 18:44 UTC, Equinox4 commented on langages/c/debunk-c.md
> +Un autre exemple est la gestion des erreurs, qui est traitée de manière très
Utiliser une autre transition que "Un autre exemple" qui est déjà utilisé  dans le paragraphe précédent

2022-10-15 18:44 UTC, Equinox4 commented on langages/c/debunk-c.md
> +de ce type de comparaison, il y a par exemple [cet article](https://haslab.github.io/SAFER/scp21.pdf).
```suggestion
par C++ et Rust (avec des différences de 5% dans les pires cas). Pour un exemple
de ce type de comparaison, il y a [cet article](https://haslab.github.io/SAFER/scp21.pdf).
```

2022-10-15 18:44 UTC, Equinox4 commented on langages/c/debunk-c.md
> +reste du développement en C en termes de coût.
```suggestion
reste du développement en C en termes de coûts.
```
ou "terme de coût"

2022-10-15 18:44 UTC, Equinox4 commented on langages/c/debunk-c.md
> +fait partie du paysage dans l'enseignement. Il y a donc une très forte raison
```suggestion
projets qui ont perduré jusqu'à aujourd'hui. Il a également fait très tôt partie du paysage dans l'enseignement. Il y a donc une très forte raison
```

2022-10-15 18:44 UTC, Equinox4 commented on langages/c/debunk-c.md
> +experts du langage. Mais également sur le plan de l'outillage. Tout d'abord sur
```suggestion
experts du langage, mais également sur le plan de l'outillage. Tout d'abord sur
```

2022-10-15 18:44 UTC, Equinox4 commented on langages/c/debunk-c.md
> +[MSVC](https://fr.wikipedia.org/wiki/Visual_C%2B%2B) pour ne citer que les plus
```suggestion
[MSVC](https://fr.wikipedia.org/wiki/Visual_C++) pour ne citer que les plus
```

2022-10-15 18:44 UTC, Equinox4 commented on langages/c/debunk-c.md
> +(comme [Astrée](https://en.wikipedia.org/wiki/Astr%C3%A9e_(static_analysis)),
```suggestion
(comme [Astrée](https://en.wikipedia.org/wiki/Astrée_(static_analysis)),
```

2022-10-15 18:44 UTC, Equinox4 commented on langages/c/debunk-c.md
> +des logiciels développés en C. Seulement, on est en droit de se demander la part
```suggestion
des logiciels développés en C. Seulement, on est en droit de se demander quelle est la part
```

2022-10-15 18:52 UTC, Equinox4 commented
éventuellement ajouter des liens à la fin de l'article pour que l'on puisse télécharger les fichiers C ?

2022-10-16 08:58 UTC, AllanBlanchard commented on langages/c/debunk-c.md
> +reste du développement en C en termes de coût.
Pour le coup, il semblerait selon mon correcteur que "en termes de" est une formulation invariable.

2022-10-16 09:25 UTC, AllanBlanchard commented on langages/c/debunk-c.md
> +Quel est maintenant le rapport avec C ? Et, bien tristement, il y en a assez peu.
C'était bien ce que je voulais dire, mais j'ai reformulé autrement.

2022-10-16 09:25 UTC, AllanBlanchard commented on langages/c/debunk-c.md
> +d'y voir un peu plus clair dans tout ça, cet article propose de passer en revue
Done

2022-10-16 09:26 UTC, AllanBlanchard commented on langages/c/debunk-c.md
> +Commençons par une mauvaise métaphore (il n'y a pas de raison que je n'ai pas le
J'ai rejoué un peu le truc, mais je garde la mauvaise métaphore.

2022-10-16 09:26 UTC, AllanBlanchard commented on langages/c/debunk-c.md
> +Le précédent point nous amène au fait que C serait un très bon langage pour
Changé

2022-10-16 09:27 UTC, AllanBlanchard commented on langages/c/debunk-c.md
> +dans quel état. Et les cours sont généralement très évasifs à ce sujet parce que
Clarifié

2022-10-16 09:27 UTC, AllanBlanchard commented on langages/c/debunk-c.md
> +Un autre exemple est la gestion des erreurs, qui est traitée de manière très
Changé

2022-10-16 09:27 UTC, AllanBlanchard commented on langages/c/debunk-c.md
> +comprendre. Au contact de débutants, on constate d'ailleurs que la manipulation
J'ai ajouté un petit bout, mais je ne veux pas rentrer dans les détails.

2022-10-16 09:28 UTC, AllanBlanchard commented
> éventuellement ajouter des liens à la fin de l'article pour que l'on puisse télécharger les fichiers C ?

Je les ai mis au fil de l'eau. (C'est naze de ne pas pouvoir répondre directement à un commentaire dans cette interface pourrie)

2022-10-16 09:29 UTC, AllanBlanchard commented
Merci pour la review

2022-10-16 17:44 UTC, Equinox4 commented on langages/c/debunk-c.md
> +reste du développement en C en termes de coût.
en effet, termes s'écrit avec un "s", mais il doit être suivie d'un ensemble de choses, donc il faudrait mettre "coût" au pluriel

2022-10-16 17:54 UTC, Equinox4 approved these changes

2022-10-17 11:46 UTC, Elanis reviewed
Voilà voilà, j'ai lu et laissé quelques rares remarques.
Une remarque qui n'est pas listé, auquel j'ai pensé au cours de ma lecture: je pense qu'il serait intéressant d'avoir une table des matières en début d'article, pour pouvoir aller à une partie qui nous intéresse direct et link sur NaN au besoin (je sens que ca va arriver assez souvent :smile:).

Très intéressant comme article, merci Peuk pour ton travail !

2022-10-17 11:46 UTC, Elanis commented on langages/c/debunk-c.md
> +d'y voir un peu plus clair, cet article propose de passer en revue quelques une
```suggestion
d'y voir un peu plus clair, cet article propose de passer en revue quelques-unes
```
J'ai eu un doute pour celle là, j'ai été check ici: https://fr.wiktionary.org/wiki/quelques-unes

2022-10-17 11:46 UTC, Elanis commented on langages/c/debunk-c.md
> +directement accessible. Le peu de contrôle que l'on peut obtenir a ce sujet
```suggestion
directement accessible. Le peu de contrôle que l'on peut obtenir à ce sujet
```

2022-10-17 11:46 UTC, Elanis commented on langages/c/debunk-c.md
> +détails sur ce sujet, je vous conseille
```suggestion
détails à ce sujet, je vous conseille
```

2022-10-17 11:46 UTC, Elanis commented on langages/c/debunk-c.md
> +amener à ce type de comportements (cf. Annexe J dans la norme C11 par exemple).
Peut être ajouter un lien vers cette annexe ? Histoire que les curieux puissent voir d'un coup d'œil quelques exemples

2022-10-18 07:02 UTC, AllanBlanchard commented on langages/c/debunk-c.md
> +amener à ce type de comportements (cf. Annexe J dans la norme C11 par exemple).
Je fais ça un peu plus tard.

2022-10-21 19:14 UTC, AllanBlanchard commented on langages/c/debunk-c.md
> +amener à ce type de comportements (cf. Annexe J dans la norme C11 par exemple).
Done

2022-10-28 15:35 UTC, AllanBlanchard commented
Ping ?

2022-10-28 15:39 UTC, Elanis commented
Merci du rappel :smile:

Que penses tu de l'idée d'ajouter un table des matières rapides avec les differents points principaux au début ?

Sinon, hormis ce point, rien a redire de plus

2022-10-28 18:08 UTC, AllanBlanchard commented
Ok. Je fais ça demain.

2022-10-29 11:45 UTC, AllanBlanchard commented
Done

2022-10-29 17:04 UTC, Elanis commented
Super ! Merci !

2022-10-29 17:04 UTC, Elanis approved these changes

2022-10-29 17:44 UTC, Equinox4 approved these changes

2022-10-30 07:33 UTC, Iltotore requested changes
J'ai relu l'article de "Si j'apprend C, c'est facile d'apprendre les autres langages" à la conclusion de "C est un bon langage pour débutant"

2022-10-30 07:33 UTC, Iltotore commented on langages/c/debunk-c.md
> +langage de programmation n'est pas si direct, cependant il est déjà bien de
Comme "langues naturelles" est au pluriel, "langage de programmation" devrait aussi l'être

2022-10-30 07:33 UTC, Iltotore commented on langages/c/debunk-c.md
> +[Closure](https://fr.wikipedia.org/wiki/Clojure) sont encore en usage, mais qui
Petite typo à "Clo**j**ure"

2022-10-30 07:33 UTC, Iltotore commented on langages/c/debunk-c.md
> +syntaxes et la sémantique de ce sous-ensemble de syntaxes. Et de manière très
"syntaxes" devrait-être au singulier

2022-10-30 07:33 UTC, Iltotore commented on langages/c/debunk-c.md
> +simplement dues au fait qu'une saisie peut échouer et que l'on doit le vérifier.
"le vérifier" devrait être "la vérifier" si on parle de vérifier l'entrée. "le vérifier" marche si on le rapport à l'échec/le fait que ça peut échouer mais ça me semble moins fluent.

2022-10-30 07:33 UTC, Iltotore commented on langages/c/debunk-c.md
> +des codes qui contiennent des nombreuses erreurs qu'il ne pourra jamais corriger
"des nombreuses" devrait être "de nombreuses" dans ce contexte.

2022-10-30 07:33 UTC, Iltotore commented on langages/c/debunk-c.md
> +en C, car ces affichages peuvent changer le comportement d'un programme qui
J'ai un doute sur "ces affichages" ou "ses affichages". Est-ce que tu veux parler de l'affichage produit par `print` ou de la fonction `print` en elle-même ?

2022-10-30 09:30 UTC, AllanBlanchard commented on langages/c/debunk-c.md
> +langage de programmation n'est pas si direct, cependant il est déjà bien de
Done

2022-10-30 09:30 UTC, AllanBlanchard commented on langages/c/debunk-c.md
> +[Closure](https://fr.wikipedia.org/wiki/Clojure) sont encore en usage, mais qui
Done

2022-10-30 09:30 UTC, AllanBlanchard commented on langages/c/debunk-c.md
> +syntaxes et la sémantique de ce sous-ensemble de syntaxes. Et de manière très
Done

2022-10-30 09:31 UTC, AllanBlanchard commented on langages/c/debunk-c.md
> +simplement dues au fait qu'une saisie peut échouer et que l'on doit le vérifier.
Je ne trouve pas, mais vu que ça change pas grand chose, j'ai fait le changement.

2022-10-30 09:31 UTC, AllanBlanchard commented on langages/c/debunk-c.md
> +des codes qui contiennent des nombreuses erreurs qu'il ne pourra jamais corriger
Done

2022-10-30 09:31 UTC, AllanBlanchard commented on langages/c/debunk-c.md
> +en C, car ces affichages peuvent changer le comportement d'un programme qui
C'est bien ce que j'ai voulu dire.

2022-10-30 10:55 UTC, Equinox4 approved these changes

2022-10-30 11:00 UTC, Elanis approved these changes

2022-10-30 13:14 UTC, Iltotore approved these changes

2022-10-30 13:28 UTC, merged