Scala comme premier langage de programmation
NotANameServer/Not-a-Hub pull request #45
Opened 2023-02-18 10:59 UTC by Iltotore

Voici un article qui passe en revue les atouts de Scala pour enseigner l'algorithmie/les bases de la programmation à des novices.

Le but (comme précisé dans l'introduction) est de ne pas mettre en concurrence directe/casser les autres langages utilisés (Python, C...) mais de montrer ce qui fait de Scala un bon candidat. À noter qu'il y a quand même certaines comparaisons.

Un petit peu inspiré du récent article de @AllanBlanchard sur les idées reçues sur le C et co-écrit avec @TheElectronWill.

2023-02-20 14:20 UTC, Equinox4 commented
Salut, merci pour ce nouvel article, je ferai une relecture prochainement.
En attendant, pourrais-tu corriger les liens des images pour avoir des urls relatives (cf a8b1c71) et rapatrier les images hébergées sur imgur pour les mettre dans le dépôt ?
merci :)

2023-02-20 14:34 UTC, TheElectronWill commented on langages/scala/scala-comme-premier-langage.md
> +- Les opérateurs sont des fonctions comme les autres, par exemple `def +`. On ne définit pas de méthode magique (comme `__add__` en Python) mais qui s'utilise finalement `+`.
```suggestion
- Les opérateurs sont des fonctions comme les autres, par exemple `def +`. On ne définit pas de méthode "magique" (comme `__add__` en Python mais qui s'utilise finalement `+`).
```

2023-02-20 14:35 UTC, Iltotore commented
> Salut, merci pour ce nouvel article, je ferai une relecture prochainement. En attendant, pourrais-tu corriger les liens des images pour avoir des urls relatives (cf [a8b1c71](https://github.com/NotANameServer/Not-a-Hub/commit/a8b1c71c663772253273200b426d550799335503)) et rapatrier les images hébergées sur imgur pour les mettre dans le dépôt ? merci :)

Oups un oubli. Je fais ça dès que possible.

2023-02-20 17:58 UTC, Julien00859 commented on langages/scala/scala-comme-premier-langage.md
> +- Les opérateurs sont des fonctions comme les autres, par exemple `def +`. On ne définit pas de méthode magique (comme `__add__` en Python) mais qui s'utilise finalement `+`.
À noter que la documentation officielle ne parle jamais de "méthode magique", en fait il n'y a pas de nom officiel pour les méthodes entourées d'un double underscore. Plusieurs personnes dans la communauté (dont moi) aimons parler du *modèle de donnée* du fait que l'ensemble de ces fonctions sont définies dans le document [Data Model](https://docs.python.org/3/reference/datamodel.html) de la documentation officielle. Voila, c'est mon petit pipi dont tout le monde s'en fou :D

2023-02-20 20:43 UTC, TheElectronWill commented on langages/scala/scala-comme-premier-langage.md
> +- Les opérateurs sont des fonctions comme les autres, par exemple `def +`. On ne définit pas de méthode magique (comme `__add__` en Python) mais qui s'utilise finalement `+`.
oui c'est un nom officieux donnés par certains ^^

2023-02-21 00:55 UTC, Julien00859 commented
On a réécrit l'historique sur master parce qu'on est des *****|, du coup vous devez rebase 😬

2023-02-21 06:20 UTC, Iltotore commented
> On a réécrit l'historique sur master parce qu'on est des *****|, du coup vous devez rebase 😬

Oui j'ai vu tout à l'heure 👍 . Je ferai ça en même temps que les autres modifications

2023-02-21 07:29 UTC, Iltotore commented on langages/scala/scala-comme-premier-langage.md
> +- Les opérateurs sont des fonctions comme les autres, par exemple `def +`. On ne définit pas de méthode magique (comme `__add__` en Python) mais qui s'utilise finalement `+`.
J'ai gardé magique et ajouté les guillemets comme proposé par ElectronWill

2023-02-23 13:19 UTC, Elanis commented on langages/scala/scala-comme-premier-langage.md
> +Enfin, Scala est un [langage plutôt populaire](https://redmonk.com/rstephens/2022/10/20/top20-jun2022/) qui dispose d'une communauté active (notamment sur les plateformes [Scala Users Forum](https://
```suggestion
Enfin, Scala est un [langage plutôt populaire](https://redmonk.com/rstephens/2022/10/20/top20-jun2022/) qui dispose d'une communauté active (notamment sur les plateformes [Scala Users Forum](https://users.scala-lang.org/), [Discord](https://discord.gg/scala)) ainsi que de nombreuses [ressources en ligne (cours vidéo, livres, articles, etc.)](https://docs.scala-lang.org/learn.html). Non seulement le débutant peut apprendre en autonomie, mais il peut aussi obtenir de l'aide quand il en a besoin.
```

2023-02-23 13:20 UTC, Elanis commented
Je ne connais pas scala, mais voilà la seule chose qui m'a sauté aux yeux dans ma lecture rapide :)

2023-02-23 15:03 UTC, Iltotore commented on langages/scala/scala-comme-premier-langage.md
> +Enfin, Scala est un [langage plutôt populaire](https://redmonk.com/rstephens/2022/10/20/top20-jun2022/) qui dispose d'une communauté active (notamment sur les plateformes [Scala Users Forum](https://
Je trouve que "ainsi que" ici fait un peu trop ampoulé/comme dirait ma prof de français : pachydermique.

2023-02-23 15:08 UTC, Elanis commented on langages/scala/scala-comme-premier-langage.md
> +Enfin, Scala est un [langage plutôt populaire](https://redmonk.com/rstephens/2022/10/20/top20-jun2022/) qui dispose d'une communauté active (notamment sur les plateformes [Scala Users Forum](https://
Le double "et" me semblait bizarre, mais on peut peut-être trouver une autre solution :)

2023-02-23 15:11 UTC, Iltotore commented on langages/scala/scala-comme-premier-langage.md
> +Enfin, Scala est un [langage plutôt populaire](https://redmonk.com/rstephens/2022/10/20/top20-jun2022/) qui dispose d'une communauté active (notamment sur les plateformes [Scala Users Forum](https://
J'irai relire tranquillement une fois chez moi

2023-02-23 16:30 UTC, Iltotore commented on langages/scala/scala-comme-premier-langage.md
> +Enfin, Scala est un [langage plutôt populaire](https://redmonk.com/rstephens/2022/10/20/top20-jun2022/) qui dispose d'une communauté active (notamment sur les plateformes [Scala Users Forum](https://
Effectivement: ça fait un peu moche à l'oreille. Je pense que je vais retaper ça en
> (notamment sur les plateformes Scala Users et Discord) ainsi que de ...

2023-02-24 12:55 UTC, Julien00859 approved these changes
J'ai pris plaisir à lire cet article :)

Ma seule suggestion serait de peut-être rajouter quelques références de cours francophones sur le langage, c'est histoire de donner du matériel pédagogique concret au prof qui aura été convaincu par vos arguments :p

2023-02-24 13:53 UTC, Equinox4 requested changes

2023-02-24 13:53 UTC, Equinox4 commented on langages/scala/scala-comme-premier-langage.md
> +Notons que cette interface interactive embarque de la coloration syntaxique et de l'autocomplétion ! Elle permet de facilement tester de petits fragments de code. À l'opposé, un éditeur comme Visual
```suggestion
Notons que cette interface interactive embarque de la coloration syntaxique et de l'autocomplétion ! Elle permet de facilement tester de petits fragments de code. À l'opposé, un éditeur comme Visual Studio Code couplé avec un outil de build convient pour des scripts et des projets de plusieurs fichiers. Il existe plusieurs outils, mais le plus accessible est certainement [Scala CLI](https://scala-cli.virtuslab.org/), qui se veut plus simple que Maven, Gradle, etc.
```

2023-02-24 13:53 UTC, Equinox4 commented on langages/scala/scala-comme-premier-langage.md
> +Enfin, Scala est un [langage plutôt populaire](https://redmonk.com/rstephens/2022/10/20/top20-jun2022/) qui dispose d'une communauté active (notamment sur les plateformes [Scala Users Forum](https://
```suggestion
Enfin, Scala est un [langage plutôt populaire](https://redmonk.com/rstephens/2022/10/20/top20-jun2022/) qui dispose d'une communauté active (notamment sur les plateformes [Scala Users Forum](https://users.scala-lang.org/) et [Discord](https://discord.gg/scala)) ainsi que de nombreuses [ressources en ligne](https://docs.scala-lang.org/learn.html) (cours vidéo, livres, articles, etc). Non seulement le débutant peut apprendre en autonomie, mais il peut aussi obtenir de l'aide quand il en a besoin.
```

2023-02-24 13:53 UTC, Equinox4 commented on langages/scala/scala-comme-premier-langage.md
> +Le nom "Scala" est la contraction de "Scalable language", que l'on peut traduire par "langage capable de passer à l'échelle". En d'autres termes, Scala se veut aussi bien adapté pour de petits script
la traduction de "scalable" ce serait plutôt "évolutif", "passer à l'échelle" ça fait un peu bizarre je trouve

2023-02-24 13:53 UTC, Equinox4 commented on langages/scala/scala-comme-premier-langage.md
> +Scala combine la programmation orientée objet et la programmation fonctionnelle. Cela peut paraître étrange, mais force est de constater que de nombreux langages orientés objet incorporent aujourd'hu
```suggestion
Scala combine la programmation orientée objet et la programmation fonctionnelle. Cela peut paraître étrange, mais force est de constater que de nombreux langages orientés objet incorporent aujourd'hui des éléments de programmation fonctionnelle : Java possède des "lambdas" depuis plusieurs années, Python propose depuis peu des "dataclasses", etc... Cette combinaison n'est pas forcée : le langage met simplement les outils à disposition du programmeur. Cela permet au débutant de travailler chaque paradigme séparément et de manière progressive, sans avoir besoin d'apprendre une nouvelle syntaxe et de nouveaux outils. C'est aussi un gain de temps pour l'enseignant, qui peut se concentrer sur les concepts et non sur les détails d'un langage supplémentaire.
```

2023-02-24 13:53 UTC, Equinox4 commented on langages/scala/scala-comme-premier-langage.md
> +Le choix du premier langage est important : il doit inculquer aux élèves les paradigmes, modes de pensées et bonnes habitudes générales, réutilisables dans les autres langages.
```suggestion
Le choix du premier langage est important : il doit inculquer aux élèves les paradigmes, modes de pensée et bonnes habitudes générales, réutilisables dans les autres langages.
```
les modes de la pensée ou les pensées, il faut choisir

2023-02-24 13:53 UTC, Equinox4 commented on langages/scala/scala-comme-premier-langage.md
> +Bien que Scala soit statiquement typé, il est possible d'omettre les annotations de types dans de nombreux cas. Dans l'exemple ci-dessus, nous aurions pu écrire `val friends: List[User]`, mais Scala
```suggestion
Bien que Scala soit statiquement typé, il est possible d'omettre les annotations de type dans de nombreux cas. Dans l'exemple ci-dessus, nous aurions pu écrire `val friends: List[User]`, mais Scala l'a inféré pour nous.
```
vu qu'on parle du type d'un variable en général, je mettrais singulier ici

2023-02-24 13:53 UTC, Equinox4 commented on langages/scala/scala-comme-premier-langage.md
> +En plus du fait d'avoir une syntaxe lisible, le langage est également très cohérent et régulier.
```suggestion
En plus de la lisibilité de sa syntaxe, le langage est également très cohérent et régulier.
```

2023-02-24 13:53 UTC, Equinox4 commented on langages/scala/scala-comme-premier-langage.md
> +Il y a plusieurs moyen d'utiliser `Option` mais une méthode courante est d'utiliser le [pattern matching](https://docs.scala-lang.org/tour/pattern-matching.html) :
```suggestion
Il y a plusieurs moyens d'utiliser `Option` mais une méthode courante est d'utiliser le [pattern matching](https://docs.scala-lang.org/tour/pattern-matching.html) :
```

2023-02-24 13:53 UTC, Equinox4 commented on langages/scala/scala-comme-premier-langage.md
> +*Est-ce qu'à la fin de ce programme `l` a changé ? Si oui où ça ? Est-ce que l'ordre à de l'importance ?* Ces problèmes sont prévenus par l'immuabilité
```suggestion
*Est-ce qu'à la fin de ce programme `l` a changé ? Si oui où ça ? Est-ce que l'ordre à de l'importance ?* Ces problèmes sont prévenus par l'immuabilité.
```

2023-02-24 13:53 UTC, Equinox4 commented on langages/scala/scala-comme-premier-langage.md
> +Ici nous savons que `list` n'a pas été modifiée donc nous n'avons pas à nous poser les questions ci-dessus. Nous pouvons ainsi nous focaliser localement, sans nous préoccuper de notre `doSomething` e
```suggestion
Ici nous savons que `list` n'a pas été modifiée donc nous n'avons pas à nous poser les questions ci-dessus. Nous pouvons ainsi nous focaliser localement, sans nous préoccuper de nos `doSomething` et `doAnotherThing`.
```

2023-02-24 13:53 UTC, Equinox4 commented
bon article, quelques fautes d'ortho à corriger

2023-02-24 14:01 UTC, Equinox4 commented on langages/scala/scala-comme-premier-langage.md
> +*Est-ce qu'à la fin de ce programme `l` a changé ? Si oui où ça ? Est-ce que l'ordre à de l'importance ?* Ces problèmes sont prévenus par l'immuabilité
ou deux-points, à vous de voir

2023-02-24 15:58 UTC, TheElectronWill commented on langages/scala/scala-comme-premier-langage.md
> +Le nom "Scala" est la contraction de "Scalable language", que l'on peut traduire par "langage capable de passer à l'échelle". En d'autres termes, Scala se veut aussi bien adapté pour de petits script
extensif / évolutif oui pourquoi pas si ça semble + clair ^^ 
"passer à l'échelle" ne me dérange pas trop, je l'ai entendu dans plusieurs contextes (il est cité ici https://fr.wikipedia.org/wiki/Extensibilité)

2023-02-24 15:59 UTC, TheElectronWill commented on langages/scala/scala-comme-premier-langage.md
> +En plus du fait d'avoir une syntaxe lisible, le langage est également très cohérent et régulier.
ou alors "En plus d'avoir une syntaxe lisible, le langage est ..." ? Comme ça on a bien un verbe :)

2023-02-24 16:38 UTC, Julien00859 commented on langages/scala/scala-comme-premier-langage.md
> +Le nom "Scala" est la contraction de "Scalable language", que l'on peut traduire par "langage capable de passer à l'échelle". En d'autres termes, Scala se veut aussi bien adapté pour de petits script
Attention à bien diffencier `scale (nun)` de `scalable (adj.)` de `scaling (adj.)` de `to scale (verb)`, aussi il faut comprendre il y a plus de nuance en français qu'en anglais, d'où les multiples traductions possibles.

"mettre à l'échelle" c'est pour traduire "to scale" dans le sens de"augmenter la capacité d'un système à absorber la charge de travail à l'échelle de la charge de travail à absorber", ce n'est pas la bonne traduction ici :p

2023-02-24 16:41 UTC, TheElectronWill commented on langages/scala/scala-comme-premier-langage.md
> +Le nom "Scala" est la contraction de "Scalable language", que l'on peut traduire par "langage capable de passer à l'échelle". En d'autres termes, Scala se veut aussi bien adapté pour de petits script
Mais est-ce qu' "augmenter / diminuer la taille du système pour s'adapter au travail" ne convient pas aussi pour quelque chose qui s'adapte à de petits comme à de grands projets ? :thinking:

2023-02-24 22:48 UTC, Equinox4 commented on langages/scala/scala-comme-premier-langage.md
> +En plus du fait d'avoir une syntaxe lisible, le langage est également très cohérent et régulier.
c'est good

2023-02-25 15:43 UTC, Julien00859 commented on langages/scala/scala-comme-premier-langage.md
> +Le nom "Scala" est la contraction de "Scalable language", que l'on peut traduire par "langage capable de passer à l'échelle". En d'autres termes, Scala se veut aussi bien adapté pour de petits script
votre article, vous décidez ;)

2023-02-26 07:41 UTC, Iltotore commented on langages/scala/scala-comme-premier-langage.md
> +Le nom "Scala" est la contraction de "Scalable language", que l'on peut traduire par "langage capable de passer à l'échelle". En d'autres termes, Scala se veut aussi bien adapté pour de petits script
Je propose:
> Le nom "Scala" est la contraction de "Scalable language", que l'on peut traduire littéralement par "langage capable de passer à l'échelle" ou, en meilleur français, "langage évolutif"

2023-02-26 07:46 UTC, Iltotore commented on langages/scala/scala-comme-premier-langage.md
> +En plus du fait d'avoir une syntaxe lisible, le langage est également très cohérent et régulier.
> En plus d'avoir une syntaxe lisible, le langage est ...

Ca me parait mal sonner à l'oreille mais c'est peut-être que moi.

2023-02-26 09:21 UTC, TheElectronWill commented on langages/scala/scala-comme-premier-langage.md
> +Le nom "Scala" est la contraction de "Scalable language", que l'on peut traduire par "langage capable de passer à l'échelle". En d'autres termes, Scala se veut aussi bien adapté pour de petits script
extensible j'aime bien :)

2023-03-04 14:11 UTC, Equinox4 approved these changes

2023-03-04 15:15 UTC, merged