site local
NotANameServer/Not-a-Hub pull request #50
Opened 2023-02-20 20:05 UTC by luc-git

Là y a deux commits je sais pas ce qui se passe

2023-02-20 20:07 UTC, luc-git commented
Si y a une erreur ça ne sert à rien de fermer la PR il suffit juste de modifier la branche du fork

2023-02-20 20:14 UTC, Julien00859 commented
Salut Luc, ta branche master a divergé de notre branche master, voici ce que tu peux faire sur ta machine pour régler le problème

    git switch master
    git remote add upstream https://github.com/NotANameServer/Not-a-Hub.git
    git fetch upstream
    git reset origin/master
    git switch site-local
    git reset master
    git add .
    git commit
    git push --force-with-lease

2023-02-20 20:17 UTC, luc-git commented
ok merci c'est fait

2023-02-20 20:41 UTC, Julien00859 reviewed
Merci d'avoir résolu le problème, désolé de ne pas avoir pu le faire moi-même :/ Mes commentaires sur l'autre PR ont été perdu du coup je les remets ici :)

Déjà comme note générale je pense que ces étapes devraient être intégrées au `CONTRIBUTING.md` plutôt qu'être directement dans le README. Il manque les étapes pour Linux (on aussi nombreux sur Linux que sur Windows). Aussi l'enchainement du texte et des titres est bizarre

2023-02-21 16:57 UTC, luc-git commented
j'ai bougé le tout dans CONTRIBUTING.md. J'ai ajouté les instructions d'installation pour ubuntu en recopiant ici:
https://github.com/jekyll/jekyll/blob/master/docs/_docs/installation/ubuntu.md

2023-02-21 16:57 UTC, luc-git commented
La license de jekyll est la license MIT donc ça doit pas vraiment poser problème de piquer du code

2023-02-21 17:00 UTC, Elanis commented on CONTRIBUTING.md
> +	ruby -v
Peut être ajouter le retour attendu après cette commande ?

2023-02-21 17:00 UTC, Elanis commented on CONTRIBUTING.md
> +## Installer jekyll sur linux ubuntu
```suggestion
## Installer jekyll sur Debian/Ubuntu
```

2023-02-21 17:06 UTC, Equinox4 requested changes

2023-02-21 17:06 UTC, Equinox4 commented on CONTRIBUTING.md
> +# Comment tester le site web en local?
```suggestion
# Comment tester le site web en local ?
```

2023-02-21 17:06 UTC, Equinox4 commented on CONTRIBUTING.md
> +https://jekyllrb.com/docs/installation/windows/
```suggestion

https://jekyllrb.com/docs/installation/windows/
```

2023-02-21 17:06 UTC, Equinox4 commented on CONTRIBUTING.md
> +## Installer jekyll sur linux ubuntu
```suggestion
## Installer jekyll sur linux
```

2023-02-21 17:06 UTC, Equinox4 commented on CONTRIBUTING.md
> +sudo apt-get install ruby-full build-essential zlib1g-dev
```suggestion
sudo apt install ruby-full build-essential zlib1g-dev
```

2023-02-21 17:06 UTC, Equinox4 commented on CONTRIBUTING.md
> +Utilisez un dossier d'installation pour votre user.
```suggestion
Utilisez un dossier d'installation pour votre utilisateur.
```

2023-02-21 17:06 UTC, Equinox4 commented on CONTRIBUTING.md
> +Installez jekyll et bundler:
```suggestion
Installer jekyll et bundler:
```

2023-02-21 17:06 UTC, Equinox4 commented on CONTRIBUTING.md
> +Un serveur web sera alors lancé et votre site est disponible en localhost sur le port 4000.
```suggestion
Un serveur web sera alors lancé et votre site sera disponible en local sur le port 4000.
```

2023-02-21 17:06 UTC, Equinox4 commented on CONTRIBUTING.md
> +Ouvrez votre navigateur internet préféré entrez l'adresse 127.0.0.1:4000 et voilà le résultat
```suggestion
Ouvrez votre navigateur internet préféré entrez l'adresse `localhost:4000` et voilà le résultat
```

2023-02-21 17:06 UTC, Equinox4 commented on Gemfile
> +
```suggestion
```

2023-02-21 17:06 UTC, Equinox4 commented on README.md
> +Vous pouvez vous referrer au [Guide de contribution](https://github.com/NotANameServer/Not-a-Hub/blob/master/CONTRIBUTING.md).
```suggestion
Vous pouvez vous réferrer au [Guide de contribution](https://github.com/NotANameServer/Not-a-Hub/blob/master/CONTRIBUTING.md).
```

2023-02-21 17:16 UTC, luc-git commented
ça fait beaucoup de commit là

2023-02-21 17:26 UTC, Equinox4 commented
pas grave on va squash après

2023-02-22 09:45 UTC, Julien00859 commented on CONTRIBUTING.md
> +Ouvrez votre navigateur internet préféré entrez l'adresse `localhost:4000` et voilà le résultat
`<rant>`
Jekyll donne l'impression d'être vraiment mal intégré

1. Wtf installer ruby-dev et build-essentials ?!?!
2. Wtf faire modifier le `.bashrc` pour casser le PATH ?!?!
3. Wtf tout installer via le bundle de ruby ?!?!

Je constate que toutes ces étapes sont ce qui est recommandé à la fois sur github et sur le site officiel de Jekyll. Je ne connais pas ni ruby ni son environnement et là je me retrouve dans une situation où il n'y a pas d'autres alternatives que d'installer `bundle` ou `gem` et qui vont eux-mêmes installer toute une série de logiciels.

On ne parle pas du support pour Windows qui est inexistant alors que Ruby est multi-plateforme
`</rant>`

Ce message ne t'est pas destiné, je râle juste sur le fait que j'ai perdu 2h ce matin à essayer de simplifier cette installation.

Still je trouve toutes ces étapes trop compliquées. Je comprend qu'il n'y a pas d'alternative mais je me demande du coup si ce ne serait pas mieux de se contenter de link une ressource externe, e.g. le [tuto sur github](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll)

2023-02-22 18:35 UTC, Equinox4 requested changes, later dismissed

2023-02-22 18:35 UTC, Equinox4 commented on Gemfile
> +gem "github-pages", group: :jekyll_plugins
```suggestion
source "https://rubygems.org"
gem "github-pages", group: :jekyll_plugins
```

2023-02-23 13:48 UTC, Julien00859 commented on CONTRIBUTING.md
> +Ouvrez votre navigateur internet préféré entrez l'adresse `localhost:4000` et voilà le résultat
> Still je trouve toutes ces étapes trop compliquées. Je comprend qu'il n'y a pas d'alternative mais je me demande du coup si ce ne serait pas mieux de se contenter de link une ressource externe, e.g. le tuto sur github

Up

2023-02-23 15:36 UTC, luc-git commented on CONTRIBUTING.md
> +Ouvrez votre navigateur internet préféré entrez l'adresse `localhost:4000` et voilà le résultat
J'ai mis le lien de l'installation de jekyll du site directement.
Je pense que mettre le lien pour le tuto github n'est pas nécessaire car il a lui même les liens pour installer jekyll sur leur site et pour build le site web y a juste besoin de 3 commandes.

2023-02-24 22:44 UTC, luc-git commented
Visiblement Julien préfère mettre le tuto de github https://github.com/NotANameServer/Not-a-Hub/pull/51/commits/23aa8246c2b4410603f53aa053a6b674a8841ef0#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R5

Donc le mieux serait peut-être de tout merge sauf le CONTRIBUTING.md

2023-02-25 15:42 UTC, Julien00859 commented
J'ai ouvert une autre PR pour qu'on ait un point de comparaison, je laisse les autres décider de l'approcher à avoir

2023-02-25 15:53 UTC, luc-git commented
https://github.com/NotANameServer/Not-a-Hub/pull/51

Cette pull request ?

2023-02-25 16:00 UTC, luc-git commented
Normalement y a besoin d’un gemfile pour utiliser la commande bundle.
Y a besoin des fichiers que j’ai ajouté pour pas qu’on ait besoin de le faire manuellement.

2023-03-06 12:00 UTC, Julien00859 approved these changes

2023-03-06 12:01 UTC, merged