référencement articles
NotANameServer/Not-a-Hub pull request #52
Opened 2023-03-01 22:19 UTC by luc-git

J'ai ajouté un sitemap pour pouvoir permettre d'indexer plus de pages à google:

J'ai suivi ce lien: https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap?hl=fr#addsitemap

Parce que comme vous pouvez le voir ici site:https://hub.notaname.fr seulement deux pages sont indexées sur google.

J'ai aussi fait en sorte d'empêcher le script index.py d'ajouter le lien des articles une seconde fois
https://github.com/NotANameServer/Not-a-Hub/compare/master...luc-git:Not-a-Hub:sitemap?expand=1#diff-d568ca4e7eadfe7422397de0ed9269419d690f632aeb3e13826faefc79826ec9R134

Le soucis étant que si vous utilisez le script en local il va automatiquement chercher dans le sous dossier "_site".

2023-03-01 23:37 UTC, Equinox4 commented
En principe un sitemap c'est un fichier xml, et je ne suis pas certain que nous en ayons besoin, cf https://developers.google.com/search/docs/crawling-indexing/sitemaps/overview?hl=fr
Tous les articles sont accessibles depuis la page d'accueil donc ils devraient être indexés la prochaine fois qu'un bot de google passera, il n'y a normalement rien à faire de plus.
Par contre ce qui pourrait être bien ce serait d'ajouter une balise meta pour que la description du résultat de recherche soit correcte
```
<meta name="description" content="Un super article"/>
```
puisque les moteurs de recherche ne semblent pas prendre en compte Open Graph

2023-03-01 23:49 UTC, luc-git commented
Ça je l’avais fait aussi faudrait que je push

2023-03-01 23:51 UTC, luc-git commented
Tu peux ajouter la description dans le markdown

2023-03-01 23:57 UTC, luc-git commented
C’est aussi possible de le faire en txt https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap?hl=fr#text. Pour le référencement y a la google search console où il est possible de pouvoir voir les problèmes qu’il y a sur le site. Par contre faut un compte google.

2023-03-03 19:46 UTC, Julien00859 requested changes
Rien ne va avec les modifications apportées au fichier `index.py`.

2023-03-03 19:46 UTC, Julien00859 commented on index.py
> +SKIP_DIRECTORY = Path('_site').resolve()
```suggestion
SKIP_DIRECTORY = ROOT / '_site'
```

Sinon ça ne fonctionne plus si on lance le programme sans être dans le même dossier que lui, c'est justement à ça que `ROOT` sert

2023-03-03 19:46 UTC, Julien00859 commented on index.py
> +        next(add_to_sitemap(uri) for uri in self.uris if uri.startswith(root))
Donc on avait une fonction pure qui ne faisait que ce que la docstring disait sans aucun effet de bord et maintenant on a effet de bord non documenté qui se met à réécrire des fichiers de nul le part ?!

2023-03-03 19:46 UTC, Julien00859 commented on index.py
> +SKIP_DIRECTORY = Path('_site').resolve()
Mais en fait, c'est quoi ce dossier `_site` ? Il y a des fichiers markdown dedans ?!

2023-03-03 19:46 UTC, Julien00859 commented on index.py
> +            rejected_files.append(i)
Pas besoin de recalculer la liste pour chaque fichier
```suggestion
    for i in directories.glob('**/*.md'):
        rejected_files.append(i)
    for path in root.glob('**/*.md'):
```

2023-03-03 19:46 UTC, Julien00859 commented on index.py
> +        articles[path.name].paths.append(path)
Code dupliqué avec la fonction `get_url`

2023-03-03 19:46 UTC, Julien00859 commented on index.py
> +        articles[path.name].paths.append(path)
Surtout que tu n'utilises que le `path.name` donc tout ceci ne sert à rien

2023-03-03 19:46 UTC, Julien00859 commented on index.py
> +
Si on retire un article, celui restera référencé dans la sitemap.

2023-03-03 19:46 UTC, Julien00859 commented on index.py
>      walk('', index, rewrite=True)
Ce serait peut-être plus malin de générer la sitemap sur base de l'index calculé par `discover_articles` que de faire tout le foin plus haut

2023-03-03 19:50 UTC, Julien00859 commented
Les messages de commits c'est pas fait pour tenir sur une seule ligne et d'ailleurs l'issue #46 n'est pas correctement liée, tu peux lire à ce propos [ici](https://github.com/Julien00859/teaching-git/wiki/explain-commit-message)

2023-03-03 19:51 UTC, luc-git commented on index.py
> +SKIP_DIRECTORY = Path('_site').resolve()
Le dossier _site c'est le dossier dans lequel les fichiers html générés par jekyll se trouvent. Cependant je trouve également les fichiers markdowns

2023-03-03 19:52 UTC, luc-git commented on index.py
> +SKIP_DIRECTORY = Path('_site').resolve()
Y a peut-être moyen d'empêcher jekyll de faire une copie des markdowns dans ce dossier j'avais pas regardé à ce moment là

2023-03-03 19:53 UTC, Julien00859 commented on index.py
> +SKIP_DIRECTORY = Path('_site').resolve()
En fait on dirait une sorte d'optimisation pour ne pas indexer les fichiers qui se trouve dans le dossier `_site`. Ces changements auraient du être discuté d'abord dans une issue et être faits dans un commit à part. D'ailleurs je ne suis même pas sur qu'on en a besoin parce que je ne pense pas qu'il y a de fichiers json dans ce dossier.

2023-03-03 20:00 UTC, Julien00859 commented on index.py
> +SKIP_DIRECTORY = Path('_site').resolve()
edit: j'ai pas du la réponse, ok donc il y a bel et bien un problème pour ceux qui lancent ce script en ayant jekyll sur leur machine. c'est un bug qui doit être discuté à part de cette PR

2023-03-03 20:06 UTC, luc-git commented on index.py
> +SKIP_DIRECTORY = Path('_site').resolve()
Quel problème les markdowns dans _site? Sinon oui j'ai modifié discover_articles pour pas indexer les markdowns qui sont dans _site

2023-03-03 20:14 UTC, Julien00859 commented on index.py
> +SKIP_DIRECTORY = Path('_site').resolve()
> Sinon oui j'ai modifié discover_articles pour pas indexer les markdowns qui sont dans _site

Le problème c'est que ces modifications ne sont documentées nul le part, on doit le deviner de notre cul pourquoi tu as fait ces modifications

2023-03-03 20:15 UTC, Julien00859 commented on index.py
> +SKIP_DIRECTORY = Path('_site').resolve()
et aussi que le code est dégueulasse

2023-03-03 20:15 UTC, luc-git commented on index.py
> +SKIP_DIRECTORY = Path('_site').resolve()
Ah j'aurais peut-être dû mettre des commentaires c'est vrai

2023-03-03 20:16 UTC, luc-git commented on index.py
> +SKIP_DIRECTORY = Path('_site').resolve()
> et aussi que le code est dégueulasse

C'est vrai que j'ai plus essayé de faire un truc fonctionnel que propre

2023-03-03 20:26 UTC, Julien00859 commented on index.py
> +SKIP_DIRECTORY = Path('_site').resolve()
> Ah j'aurais peut-être dû mettre des commentaires c'est vrai

Non, c'est changements auraient du être dans un commit à part et correctement documentés dans le message de commit

2023-03-03 20:27 UTC, Julien00859 commented on index.py
> +SKIP_DIRECTORY = Path('_site').resolve()
https://github.com/Julien00859/teaching-git/wiki/explain-commit-message

2023-03-04 01:07 UTC, luc-git commented
Cette PR est meilleure je pense que je vais fermer cette PR https://github.com/NotANameServer/Not-a-Hub/pull/53

2023-03-04 17:18 UTC, luc-git commented
Je ferme cette PR car julien a fait la même chose que moi mais en mieux ici #53

2023-03-04 17:18 UTC, closed without merging