add: discussion around git commit messages
NotANameServer/Not-a-Hub pull request #56
Opened 2023-03-11 15:45 UTC by Julien00859

I wrote this article for the class I teach at the university because most students don't understand what commit messages are for. I decided to include it via a submodule to keep track of the editions on my other repository.

    git -C teaching-git.wiki pull --ff-only
    git add teaching-git.wiki
    git commit -m "edit: update git-commit-message to latest revision"

2023-03-11 15:45 UTC, Julien00859 commented on architecture/git-commit-message.md
> +../teaching-git.wiki/explain-commit-message.md
this is a symbolic link, windows users are gonna hate me

2023-03-12 11:04 UTC, Elanis commented on architecture/git-commit-message.md
> +projet et comment l'améliorer.
La répétition du mot "partie" ici me gène un peu perso.

2023-03-12 11:04 UTC, Elanis commented on architecture/git-commit-message.md
> +systématiquement écris. Par exemple en suivant la convention de [contentional
(Je ne peux pas suggérer de changement de code, donc je vais juste devoir commenter)

contentional => conventional

2023-03-12 11:04 UTC, Elanis commented on architecture/git-commit-message.md
> +[contentional commits]: https://www.conventionalcommits.org/en/v1.0.0/
J'aurais plutôt mis ces deux liens à avant le titre "### Corps"

2023-03-12 11:04 UTC, Elanis commented on architecture/git-commit-message.md
> +	Corps avec plusieurs paragraphes, chaque ligne sous 72 caractères et...
Question peut être débile, mais ca a encore une utilité cette limite de caractères par lignes ? La plupart des outils sont capables de bien gérer l'affichage, non ?

2023-03-12 11:04 UTC, Elanis commented on architecture/git-commit-message.md
> +in *shit* companies": <https://youtube.com/shorts/0xB3T4MPEr0>.
shit => shitty ?

2023-03-12 11:04 UTC, Elanis commented on architecture/git-commit-message.md
> +# Message de commit
Peut être plutôt en pluriel ? "Messages de commit" ? Et aussi peut être spécifier qu'on parle de Git.

(Vu que ce titre est réutilisé partout, vaut mieux qu'il soit explicite imo)

2023-03-12 12:56 UTC, Julien00859 commented on architecture/git-commit-message.md
> +	Corps avec plusieurs paragraphes, chaque ligne sous 72 caractères et...
pas le terminal

2023-03-12 13:27 UTC, Julien00859 commented on architecture/git-commit-message.md
> +	Corps avec plusieurs paragraphes, chaque ligne sous 72 caractères et...
d'ailleurs si ton titre dépasse 72 caractères (oui 72, pas 50) il s'affiche mal sur github

2023-03-12 13:29 UTC, Elanis commented on architecture/git-commit-message.md
> +	Corps avec plusieurs paragraphes, chaque ligne sous 72 caractères et...
Pour le titre ouai, ca fait sens, ma question était surtout pour le commentaire. Mais si les terminaux ne savent pas revenir à la ligne tout seul, c'est donc valide :)

2023-03-12 13:31 UTC, Elanis approved these changes
LGTM, à voir ce que les autres verront que j'ai raté

2023-03-12 15:16 UTC, Equinox4 requested changes

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Ce document se découpe en plusieurs partie. La première est consacrée à expliquer l'origine des messages de commit et leurs liens avec les emails échangés entre les contributeurs au kernel Linux. La
```suggestion
Ce document se découpe en plusieurs parties. La première est consacrée à expliquer l'origine des messages de commit et leurs liens avec les emails échangés entre les contributeurs au kernel Linux. La seconde découpe la structure d'un message de commit et explique quoi mettre à quel endroit. La troisième explique où et quand sont lus les messages de commit et explicite pourquoi il est important de prendre du temps à rédiger des bons messages de commit. Pour finir une quatrième est plus succincte et donne quelques pistes pour évaluer la qualité des commits et de l'historique git d'un projet et comment l'améliorer.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Git a été développé afin de rendre possible la collaboration à grande échelle sur le noyau Linux. Avant d'utiliser git, les développeurs du noyau collaboraient à l'aide de mailing-list, ils discutaie
```suggestion
Git a été développé afin de rendre possible la collaboration à grande échelle sur le noyau Linux. Avant d'utiliser git, les développeurs du noyau collaboraient à l'aide de mailing lists, ils discutaient des changements à venir ou en cours via mail et s'échangeaient du code en pièce jointe.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Le développement d'une nouvelle fonctionnalité commençait par envoyer un email à tout le monde qui avait souscrit à la mailing-list pour décrire les nouveaux besoins. Si vous trouviez un bug dans le
```suggestion
Le développement d'une nouvelle fonctionnalité commençait par l'envoi d'un e-mail à tous les inscrits de la mailing list pour décrire les nouveaux besoins. Si vous trouviez un bug dans le noyau, vous pouviez envoyer un mail à cette mailing list pour décrire le bug et demander à ce qu'il soit corrigé. Quiconque intéressé pouvait alors "répondre à tous" sur cet e-mail et ouvrir une discussion autours de la fonctionnalité à développer ou du bug à corriger. Après quelques jours, quelqu'un répondait à la suite d'e-mails avec un *patch*, c'est à dire une archive compressée contenant l'ensemble des *diff* à appliquer aux fichiers sources du noyau. Les autres développeurs répondaient avec cet e-mail pour donner leur avis sur les changements dans le but d'arriver à la meilleure solution. Une fois le patch approuvé par tout le monde (enfin surtout par Linus), il pouvait être appliqué sur le noyau et inclus dans les nouvelles versions.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Dans le lot, le développeur qui avait pris la peine de proposer un patch ne devait pas se contenter de répondre un email vide avec le code en pièce jointe. Il avait aussi la responsabilité de résumer
```suggestion
Dans le lot, le développeur qui avait pris la peine de proposer un patch ne devait pas se contenter de répondre un e-mail vide avec le code en pièce jointe. Il avait aussi la responsabilité de résumer les discussions préalables et d'apporter des possibles éclaircissements sur son code. L'idée générale étant de faire gagner du temps à tout le monde (et surtout à Linus) en rappelant le contexte, les besoins et en apportant des explications quant à l'implémentation si ce n'était pas trivial.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Comme git a été développé avec comme objectif d'être utilisé par les contributeurs du kernel Linux, cette idée d'accompagner chaque contribution par un message explicatif a été reprise et a donné les
```suggestion
Comme git a été développé avec comme objectif d'être utilisé par les contributeurs du noyau Linux, cette idée d'accompagner chaque contribution par un message explicatif a été reprise et a donné les messages de commit.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +À la manière des emails dont les messages sont inspirés, un message de commit se décompose en 2 parties: le titre et un corps. Le titre s'inspire des sujets pour les emails tandis que le corps s'insp
```suggestion
À la manière des e-mails dont les messages sont inspirés, un message de commit se compose en 2 parties: le titre et le corps. Le titre s'inspire des sujets pour les e-mails tandis que le corps s'inspire du corps des e-mails. Le corps du message peut contenir plusieurs paragraphes de texte qui apportent toutes les infos nécessaires à la compréhension du commit. Le corps du message peut se terminer par un pied de page où sont repris différentes méta-informations, par exemple une liste de co-contributeurs, des notes de bas de page ou encore des références vers des numéros de tickets ou des issues.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +
c'est normal les points ?

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Il est inutile de répéter dans le message de commit ce qui peut être appris en lisant soit le titre soit la diff. Ceci implique qu'un effort a été réalisé pour rédiger du code propre et correctement
```suggestion
Il est inutile de répéter dans le message de commit ce qui peut être appris en lisant soit le titre soit la diff. Ceci implique qu'un effort a été réalisé pour rédiger du code propre et correctement documenté avec des docstrings et des commentaires. Il est parfois judicieux de profiter du message de commit pour rappeler comment une fonctionnalité a évolué au fil du temps, pour justifier l'état actuel du code source avec des explications historiques qui n'ont pas vraiment leur place ni en docstring ni en commentaire mais il ne faut pas expliquer le code. Lorsqu'on ressent le besoin d'expliquer la diff, c'est peut-être une indication que le code n'est pas très propre.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +* Les références vers les tâches ou les tickets dans les autres logiciels de   gestion.
```suggestion
* Les références vers les tâches ou les tickets dans les autres logiciels de gestion.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +* Le nom des co-auteurs et de ceux qui ont review.
```suggestion
* Le nom des co-auteurs et de ceux qui ont effectué une relecture (*review*).
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +	JRA-123
Note: pour `JRA-123`, la notation dépend des entreprises en réalité

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Dans le cas où notre collègue John Doe nous a beaucoup aidé dans la conception ou la réalisation du travail et qu'on souhaiter l'accréditer, on écrira:
```suggestion
Dans le cas où notre collègue John Doe nous a beaucoup aidé dans la conception ou la réalisation du travail et qu'on souhaiter le créditer, on écrira:
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Comme ces champs sont libres, il n'existe pas de registre officiel où l'ensemble des clés possibles sont regroupés. Ces quelques précédents exemples ne sont que quelques exemples assez répandu.
```suggestion
Comme ces champs sont libres, il n'existe pas de registre officiel où l'ensemble des clés possibles sont regroupées. Ces quelques précédents exemples ne sont que des exemples assez répandus.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Nous pouvons aussi citer `Helper-By`, `Acked-By` et `Signed-off-by` pour respectivement accréditer quelqu'un qui a aidé pendant le développement, ceux qui ont review la PR et celui qui prend la respo
```suggestion
Nous pouvons aussi citer `Helper-By`, `Acked-By` et `Signed-off-by` pour respectivement créditer quelqu'un qui a aidé pendant le développement, ceux qui ont review la pull request et celui qui prend la responsabilité légale des changements.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Les commits et leurs messages sont lus à trois occasions différentes. Lors de la review par les reviewers, par intérêt général par les curieux qui lisent régulièrement l'historique pour se tenir au c
```suggestion
Les commits et leurs messages sont lus à trois occasions différentes. Lors de la review par les reviewers, par intérêt général par les curieux qui lisent régulièrement l'historique pour se tenir au courant des modifications et au final par les collègues qui se creusent la tête au moment de debugger un bout de code qu'ils ne comprennent pas.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Lors de la review, les reviewers doivent comprendre l'ensemble des changements et les valider quant aux fonctionnalités qui étaient spécifiées. Ils étudient les changement en lisant scrupuleusement c
```suggestion
Lors de la review, les reviewers doivent comprendre l'ensemble des changements et les valider quant aux fonctionnalités qui étaient spécifiées. Ils étudient les changements en lisant scrupuleusement chaque ligne de code et en testant les nouvelles fonctionnalités. Le but de la review est de s'assurer que le travail est bien fait, de vérifier qu'il n'y a pas de bug et d'ouvrir une discussion pour proposer des améliorations avant que le code ne soit validé et fusionné.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Ceci implique que le code doit être soigné et correctement structuré pour inviter des commentaires plus de font que de formes. Ceci implique aussi que les reviewers doivent avoir une vue d'ensemble d
```suggestion
Ceci implique que le code doit être soigné et correctement structuré pour inviter des commentaires plus de fonds que de formes. Ceci implique aussi que les reviewers doivent avoir une vue d'ensemble de ce qui est modifié et comprendre les décisions qui ont été prises au moment du développement. C'est ici qu'intervient le message de commit. En rappelant le contexte générale et en justifiant les choix techniques.
```
j'ai un léger doute sur l'utilisation de "ceci" au lieu de "cela"

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Lorsque le message de commit est manquant, incomplet ou qu'il n'est correctement rédigé, les reviewers se retrouvent alors dans une situation où ils doivent beaucoup plus travailler pour comprendre c
```suggestion
Lorsque le message de commit est manquant, incomplet ou qu'il n'est pas correctement rédigé, les reviewers se retrouvent alors dans une situation où ils doivent beaucoup plus travailler pour comprendre ce qu'il se passe. Ils doivent relire l'ensemble des discussions autours de la spécification originale (si une telle spécification existe) et passer beaucoup plus de temps sur le code. Il y a alors un risque non négligeable que le reviewer ne prenne pas ce temps nécessaire et se contente d'une review minimale... avec son lot de répercutions sur la dette technique. Cette situation est bien reprise dans le short suivant, même s'il devrait plutôt être labellisé "how we write/review code in *shitty* companies": <https://youtube.com/shorts/0xB3T4MPEr0>.
```
btw, selon le degré de "françisation" que tu souhaites apporter à ton texte, tu peux remplacer "reviewer" par "relecteur".
A ta guise

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Le second moment où les messages de commit s'avèrent utiles est lorsqu'il s'agit d'étudier un bout de code, de comprendre le fonctionnement d'un fonction au travers du `git blame`.
```suggestion
Le second moment où les messages de commit s'avèrent utiles est lorsqu'il s'agit d'étudier un bout de code, de comprendre le fonctionnement d'une fonction au travers du `git blame`.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +`git blame` est une commande qui permet d'associer chaque ligne de code d'un fichier avec le commit qui en dernier a modifié la ligne. Il est alors possible d'étudier les changements qui ont été opér
```suggestion
`git blame` est une commande qui permet d'associer chaque ligne de code d'un fichier avec le commit qui en dernier a modifié la ligne. Il est alors possible d'étudier les changements qui ont été opérés sur une fonction pour mieux en comprendre le fonctionnement.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Le plus souvent cet outil est utilisé lorsqu'un bout de code est "WTF?!", que quelques lignes de codes sortent de l'ordinaire, contrastent avec le reste d'une fonction sans qu'aucun commentaire/docst
```suggestion
Le plus souvent cet outil est utilisé lorsqu'un bout de code est "WTF?!", que quelques lignes de code sortent de l'ordinaire, contrastent avec le reste d'une fonction sans qu'aucun commentaire/docstring ne l'explique, ou bien qu'il y a bel et bien un commentaire mais que celui-ci reste trop succin.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Le moment où une personne étudiera l'historique au travers du `git blame` sera souvent complètement déconnecté du moment où les changements auront été commités. On peut parler ici d'une différence al
```suggestion
Le moment où une personne étudiera l'historique au travers du `git blame` sera souvent complètement déconnecté du moment où les changements auront été commités. On peut parler ici d'une différence allant même jusqu'à plusieurs années. Il est donc important de s'assurer au moment de créer les commits que chaque ligne dans la diff puisse être comprise via le message de commit. Il faut donc résister à l'envie de créer un seul gros commit pour plusieurs changements orthogonaux (des changements qui n'ont pas grand chose à voir les uns avec les autres) et au besoin isoler chaque groupe de changements dans des commits séparés. Il est d'ailleurs tout à fait acceptable d'avoir plusieurs commits dans une même pull request pour profiter d'une seule review pour l'ensemble des changements mais de tout de même correctement segmenter le travail en prévision d'un futur `git blame`.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Le dernier moment où quelqu'un est susceptible de lire les message de commit est lorsque cette personne s'intéresse à l'historique en générale pour se tenir au courant des changement récent. C'est pr
```suggestion
Le dernier moment où quelqu'un est susceptible de lire les messages de commit est lorsque cette personne s'intéresse à l'historique en générale pour se tenir au courant des changements récents. C'est principalement le cas dans les petites équipes, lorsqu'il y est encore humainement faisable de se tenir au courant de l'ensemble des modifications apportées au projet. La plupart des bibliothèques open-source évoluent d'ailleurs suffisamment lentement pour qu'il soit possible de se tenir à jour des changements d'API.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Déterminer la qualité générale d'un message de commit ou plus généralement d'un historique git est assez subjectif. Il n'y a pas de recette miracle pour améliorer sa rédaction en dehors de pratiquer
```suggestion
Déterminer la qualité d'un message de commit ou plus généralement d'un historique git est assez subjectif. Il n'y a pas de recette miracle pour améliorer sa rédaction en dehors de pratiquer régulièrement et de prendre la peine de s'auto-évaluer. Un exercice utile peut être de se porter régulièrement volontaire pour faire des reviews de pull requests et de porter un regard attentif au message de commit. À force de faire des reviews, vous apprendrez à reconnaitre ce qui est utile, nécessaire, voir même précieux dans l'ensemble de la paperasse (spec, message de commit, documentation, docstrings, commentaires, ...) et à reprendre les bons exemples et éviter les mauvais.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Vous pouvez vous poser la question quant à la fréquence à laquelle vous arrivez à travailler en autonomie en parcourant l'historique à travers de `git blame` ou de vous maintenir à jour en lisant le
> Vous pouvez vous poser la question quant à la fréquence à laquelle vous arrivez à travailler en autonomie en parcourant l'historique à travers de `git blame` ou de vous maintenir à jour en lisant le `git log`.

C'est un peu alambiqué comme phrase. à reformuler

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +La rédaction des messages de commit fait parti intégrante du métier de développeurs et vient, à l'instar de l'écriture des tests unitaires, différencier le développeur amateur du développeur professi
```suggestion
La rédaction des messages de commit fait parti intégrante du métier de développeur et vient, à l'instar de l'écriture des tests unitaires, différencier le développeur amateur du développeur professionnel.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Les messages de commit sont le cœur de la documentation technique à destination des mainteneurs. Ils sont écris pour les collègues d'aujourd'hui qui devront aussi bien valider notre travail via les p
```suggestion
Les messages de commit sont le cœur de la documentation technique à destination des mainteneurs. Ils sont écris pour les collègues d'aujourd'hui qui devront aussi bien valider notre travail via les pull requests, ils sont aussi écrits pour les collègues de demain qui devront étudier notre code pour le faire évoluer.
```

2023-03-12 15:16 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Grâce aux messages de commit, il est possible de retracer l'évolution d'un logiciel et de développer sa propre compréhension des différentes étapes qui l'ont mener à être ce qu'il est aujourd'hui. Il
```suggestion
Grâce aux messages de commit, il est possible de retracer l'évolution d'un logiciel et de développer sa propre compréhension des différentes étapes qui l'ont mené à être ce qu'il est aujourd'hui. Il s'agit d'un atout précieux qui renforce la confiance des développeurs quant aux changements qu'ils apportent au logiciel.
```

2023-03-12 15:27 UTC, Julien00859 commented on architecture/les-messages-de-commit-dans-git.md
> +
c'est pour montrer jusqu'où va les 72 caractères

2023-03-12 15:31 UTC, Julien00859 commented on architecture/les-messages-de-commit-dans-git.md
> +`git blame` est une commande qui permet d'associer chaque ligne de code d'un fichier avec le commit qui en dernier a modifié la ligne. Il est alors possible d'étudier les changements qui ont été opér
j'ai gardé opérés mais j'ai laissé "son"

2023-03-12 15:33 UTC, Julien00859 commented on architecture/les-messages-de-commit-dans-git.md
> +Vous pouvez vous poser la question quant à la fréquence à laquelle vous arrivez à travailler en autonomie en parcourant l'historique à travers de `git blame` ou de vous maintenir à jour en lisant le
> Vous pouvez vous poser la question quant à la fréquence à laquelle vous lisez les messages de commit. Que ce soit pendant les reviews, avec `git blame` ou avec `git log`.

Qu'en penses-tu ?

2023-03-12 15:35 UTC, Julien00859 commented on architecture/les-messages-de-commit-dans-git.md
> +	JRA-123
Oui, chez nous c'est par exemple `owp-<numero du ticket>` avec opw en minuscule

2023-03-12 15:37 UTC, Julien00859 commented on architecture/les-messages-de-commit-dans-git.md
> +Ceci implique que le code doit être soigné et correctement structuré pour inviter des commentaires plus de font que de formes. Ceci implique aussi que les reviewers doivent avoir une vue d'ensemble d
Pour ceci vs cela je pense que ce n'est pas bien grave

2023-03-12 15:38 UTC, Julien00859 commented on architecture/les-messages-de-commit-dans-git.md
> +Lorsque le message de commit est manquant, incomplet ou qu'il n'est correctement rédigé, les reviewers se retrouvent alors dans une situation où ils doivent beaucoup plus travailler pour comprendre c
En Belgique on francise très très peu, tu l'auras remarqué lors de ta première lecture, du coup je suis team "reviewer" plutôt que "relecteur". Je n'ai pour ainsi dire jamais entendu dire "relecteur" dans ma carrière pro

2023-03-12 16:07 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +Vous pouvez vous poser la question quant à la fréquence à laquelle vous arrivez à travailler en autonomie en parcourant l'historique à travers de `git blame` ou de vous maintenir à jour en lisant le
good

2023-03-12 16:11 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +
ok

2023-03-12 16:12 UTC, Equinox4 commented on architecture/les-messages-de-commit-dans-git.md
> +`git blame` est une commande qui permet d'associer chaque ligne de code d'un fichier avec le commit qui en dernier a modifié la ligne. Il est alors possible d'étudier les changements qui ont été opér
en fait tu ne peux pas dire "mieux en comprendre son fonctionnement"
c'est soit "mieux en comprendre le fonctionnement" soit "mieux comprendre son fonctionnement"

2023-03-12 16:22 UTC, Elanis commented on architecture/les-messages-de-commit-dans-git.md
> +	JRA-123
Chez nous c'est dans le titre du commit mais c'est aussi <id projet>-<numero>, pour ca que j'ai pas relevé :)

2023-03-12 16:41 UTC, Equinox4 approved these changes

2023-03-12 16:46 UTC, merged