Lazor/py project
NotANameServer/Not-a-Hub pull request #58
Opened 2023-03-17 03:15 UTC by Julien00859

2023-04-05 05:58 UTC, Iltotore requested changes
Je n'ai lu que jusqu'à la section "utiliser un environnement virtuel" faute de temps mais voici déjà ma review pour le reste.

2023-04-05 05:58 UTC, Iltotore commented on langages/python/comment-structurer-un-projet-python.md
> +Il existe en ligne une pléthore de tutoriels[^4] [^5] [^6] sur comment structurer son projet et comment le déployer. Cependant l'éco-système de Python a tellement évolué depuis 2018 sur tout ce qui e
Le dernier "a" est en trop :

> Python a tellement évolué sur tout ce qui est relatif au packaging ~~a~~ qu’il a rendu bon nombre de ces tutoriels caduque

2023-04-05 05:58 UTC, Iltotore commented on langages/python/comment-structurer-un-projet-python.md
> +Le fichier `__main__.py` est le point d'entré de votre application, il contient le code qui sera exécuté (après `__init__.py`) lorsque vous allez lancer votre programme. Ce fichier n'est pas nécessai
Si vous comptez*

2023-04-05 05:58 UTC, Iltotore commented on langages/python/comment-structurer-un-projet-python.md
> +Pour constater que cette structure minimale fonctionne correctement, vous pouvez écrire ceci dans le fichier `__init__.py`:
J'aurai employé "vérifier" au lieu de "constater" ici

2023-04-05 05:58 UTC, Iltotore commented on langages/python/comment-structurer-un-projet-python.md
> +Une fois que vous avez vérifier que votre programme fonctionnait bien, vous pouvez vider les deux fichiers, c'est-à-dire retirer tous les prints. Ne supprimez pas les fichiers.
avez vérifié*

2023-04-05 05:58 UTC, Iltotore commented on langages/python/comment-structurer-un-projet-python.md
> +*Vous avez besoin de cette étape si vous aviez déjà commencé à faire un programme mais qu'il n'était pas correctement structuré.*
J'aurais employé du passé composé ici plutôt que du plus que parfait.

2023-04-05 05:58 UTC, Iltotore commented on langages/python/comment-structurer-un-projet-python.md
> +Si la structure de votre projet actuel ne ressemble pas à celle décrite ici ou bien si vous n'êtes pas sur alors venez nous demander de l'aide sur Discord. Faites bien attention à nous expliquer comm
sûr* au lieu de "sur" dans "n'êtes pas sur".

2023-04-05 05:58 UTC, Iltotore commented on langages/python/comment-structurer-un-projet-python.md
> +Au terme de cette étape, votre projet ressemble à ceci:
J'aurais utilisé du conditionnel ici ou alors une tournure comme "doit ressembler"/"devrait ressembler".

2023-04-05 05:58 UTC, Iltotore commented on langages/python/comment-structurer-un-projet-python.md
> +Ouvrez un terminal et entrez la commande `python3 -m pip list` (sur windows, remplacez `python3` par `py`). Le résultat de cette commande devrait lister tous les bibliothèques supplémentaires qui son
bibliothèques supplémentaires qui sont installées*

2023-04-05 05:58 UTC, Iltotore commented on langages/python/comment-structurer-un-projet-python.md
> +Lorsque vous développez un nouveau projet, il est important d'isoler les bibliothèques utilisés pour ce projet du reste des bibliothèques de votre système. Vous ne voudriez pas écraser une bibliothèq
utilisés -> utilisées

2023-04-05 05:58 UTC, Iltotore commented on langages/python/comment-structurer-un-projet-python.md
> +En Python, pour isoler les bibliothèques utilisées d'un un endroit à autre, nous utilisons des environnement virtuel.
Il y a un "un" mal positionné vers "d'un un endroit à autre".

Il manque aussi le pluriel à "des environnement virtuel".

2023-04-05 18:39 UTC, Equinox4 requested changes
Petite passe rapide concernant essentiellement l'orthographe.
Article très intéressant, certains passage mériteraient d'être un peu reformulés pour moins ressembler à du parler.

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +===================================
```suggestion
# Comment structurer un projet Python
```
je préfèrerais que l'on évite de mélanger les styles `#` `=` et `-`

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +------------
```suggestion
## Introduction
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Il existe en ligne une pléthore de tutoriels[^4] [^5] [^6] sur comment structurer son projet et comment le déployer. Cependant l'éco-système de Python a tellement évolué depuis 2018 sur tout ce qui e
```suggestion
Il existe en ligne une pléthore de tutoriels[^4] [^5] [^6] sur comment structurer son projet et comment le déployer. Cependant l'éco-système de Python a tellement évolué depuis 2018 sur tout ce qui est relatif au *packaging* qu'il a rendu bon nombre de ces tutoriels caduc[^7] [^8].
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Cet article a donc pour objectif de guider les lecteurs vers une structure de projet adaptée aux usages de 2023. Parmi les usages communs, nous avons retenu pour cet article: comment [tester son appl
```suggestion
Cet article a donc pour objectif de guider les lecteurs vers une structure de projet adaptée aux usages de 2023. Parmi les usages communs, nous avons retenu pour cet article: comment [tester son application] et comment [partager son programme avec autrui].
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +[dernier chapitre]: #choix-des-technologies
intéressante cette idée de séparer les liens du paragraphe, je connaissais pas

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +------------------------------------
```suggestion
## Mise en place du squelette du projet
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +    Copyright (c) votre nom et prénom
Pas tout à fait d'accord avec ce passage, les notions de droit d'auteur et de copyright sont différentes, de plus, le copyright n'est techniquement pas reconnu en France (ni en Belgique).

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Si vous voulez plutôt rendre votre projet open-source, avec plus ou moins de conditions, vous pouvez copier/coller le texte d'une licence existante. Vous trouverez une liste de licence communes sur l
Note: l'open source ne retire pas la paternité d'un projet, ni le droit droit d'auteur (en France), ce passage donne l'impression que le droit d'auteur serait opposé à l'open source

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Ce second dossier contiendra votre programme, c'est-à-dire tous vos fichiers python (à l'exception des tests automatiques). Pour différencier les deux dossiers, nous appellerons le 1e dossier (celui
```suggestion
Ce second dossier contiendra votre programme, c'est-à-dire tous vos fichiers python (à l'exception des tests automatiques). Pour différencier les deux dossiers, nous appellerons le premier dossier (celui qui contient le fichier `README.md`) la *racine du projet* (*project root*).
```
ou `1er`, mais pas `1e`

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Le fichier `__init__.py` fait en sorte que le dossier soit reconnu comme un module par python et sera automatiquement exécuté à chaque fois que le projet sera importé et/ou exécuté.
```suggestion
Le fichier `__init__.py` permet à python de reconnaitre le dossier comme un module et sera automatiquement exécuté à chaque fois que le projet sera importé et/ou exécuté.
```
j'aime pas les "fait en sorte de..." et autres paraphrases

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Le fichier `__main__.py` est le point d'entré de votre application, il contient le code qui sera exécuté (après `__init__.py`) lorsque vous allez lancer votre programme. Ce fichier n'est pas nécessai
```suggestion
Le fichier `__main__.py` est le point d'entrée de votre application, il contient le code qui sera exécuté (après `__init__.py`) lorsque vous lancerez votre programme. Ce fichier n'est pas nécessaire si vous comptez développer une bibliothèque de fonctions et non pas un programme exécutable.
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Au terme de cette étape, votre projet ressemble à ceci:
```suggestion
Au terme de cette étape, votre projet devrait ressembler à ceci:
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Ouvrez alors un terminal à la *racine du projet* (le 1e dossier `tartempion`) et exécutez la commande suivante pour constater qu'il est possible d'*importer* votre projet comme une *bibliothèque de f
```suggestion
Ouvrez alors un terminal à la *racine du projet* (le 1er dossier `tartempion`) et exécutez la commande suivante pour constater qu'il est possible d'*importer* votre projet comme une *bibliothèque de fonctions* (sur windows, remplacez `python3` par `py`):
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Au terme de cette étape, votre projet ressemble à ceci:
d'autant plus que le conditionnel est utilisé plus loin

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Une fois que vous avez vérifier que votre programme fonctionnait bien, vous pouvez vider les deux fichiers, c'est-à-dire retirer tous les prints. Ne supprimez pas les fichiers.
```suggestion
Une fois que vous avez vérifié que votre programme fonctionne bien, vous pouvez vider les deux fichiers, c'est-à-dire retirer tous les `print`. Ne supprimez pas les fichiers.
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +----------------------------------
```suggestion
## Adaptation d'un programme existant
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +### Structure dans l'ancien projet
```suggestion
### Structure de l'ancien projet
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +### Structure dans l'ancien projet
le projet, c'est l'ensemble des fichiers/dossiers

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +D'un point de vu des imports, le contenu de vos fichiers doit certainement ressembler à quelque chose dans le genre de:
```suggestion
Du point de vu des imports, le contenu de vos fichiers doit certainement ressembler à quelque chose dans ce genre:
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Vous devez certainement lancer votre programme soit en faisant `python3 tartempion.py` depuis votre terminal soit en cliquant sur le bouton "run" tout en étant sur le fichier `tartempion.py` dans vot
```suggestion
Vous devrez certainement lancer votre programme soit en faisant `python3 tartempion.py` depuis votre terminal soit en cliquant sur le bouton "run" tout en étant sur le fichier `tartempion.py` dans votre IDE.
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Si la structure de votre projet actuel ne ressemble pas à celle décrite ici ou bien si vous n'êtes pas sur alors venez nous demander de l'aide sur Discord. Faites bien attention à nous expliquer comm
```suggestion
Si la structure de votre projet actuel ne ressemble pas à celle décrite ici ou bien si vous n'êtes pas sûr alors venez nous demander de l'aide sur Discord. Faites bien attention à nous expliquer comment vos fichiers sont structurés, comment vous faites vos imports et surtout comment vous lancez votre programme.
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +### Structure dans le nouveau projet
```suggestion
### Structure du nouveau projet
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Le fichier `tartempions.py` est devenu le fichier `__main__.py` qui se trouve à l'intérieur du module `tartempion`. Un fichier (vide) `__init__.py` a été rajoute à côté. Le module `tartes` a été dépl
```suggestion
Le fichier `tartempions.py` est devenu le fichier `__main__.py` qui se trouve à l'intérieur du module `tartempion`. Un fichier (vide) `__init__.py` a été rajouté à côté. Le module `tartes` a été déplacé à l'intérieur du module `tartempion`.
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Niveau imports dans vos fichiers, vous devez corriger toutes vos lignes où vous avez importés des modules de votre projet à l'aide d'un import absolu. Un import est absolu lorsque ce que vous importe
```suggestion
Niveau imports dans vos fichiers, vous devez corriger toutes vos lignes où vous avez importé des modules de votre projet à l'aide d'un import absolu. Un import est absolu lorsque ce que vos imports ne commencent pas par un point. 
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +---------------------------------------
```suggestion
## Isolation dans un environnement virtuel
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Ouvrez un terminal et entrez la commande `python3 -m pip list` (sur windows, remplacez `python3` par `py`). Le résultat de cette commande devrait lister tous les bibliothèques supplémentaires qui son
```suggestion
Ouvrez un terminal et entrez la commande `python3 -m pip list` (sur windows, remplacez `python3` par `py`). Le résultat de cette commande devrait lister tous les bibliothèques supplémentaires qui sont installées pour Python sur votre machine.
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Lorsque vous développez un nouveau projet, il est important d'isoler les bibliothèques utilisés pour ce projet du reste des bibliothèques de votre système. Vous ne voudriez pas écraser une bibliothèq
```suggestion
Lorsque vous développez un nouveau projet, il est important d'isoler les bibliothèques utilisées pour ce projet du reste des bibliothèques de votre système. Vous ne voudriez pas écraser une bibliothèque utilisée par votre système par une version trop récente/ancienne dans votre projet et ainsi compromettre le bon fonctionnement de votre système.
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +En Python, pour isoler les bibliothèques utilisées d'un un endroit à autre, nous utilisons des environnement virtuel.
```suggestion
En Python, pour isoler les bibliothèques utilisées d'un un endroit à autre, nous utilisons des environnements virtuels.
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Vous pouvez aussi lister les modules supplémentaires qui sont installés dans cet environnement virtuel en faisant `./.env/bin/pip list` (`.\.env\Scripts\` sur Windows), vous devriez constater que seu
```suggestion
Vous pouvez aussi lister les modules supplémentaires qui sont installés dans cet environnement virtuel en faisant `./.env/bin/pip list` (`.\.env\Scripts\` sur Windows), vous devriez constater que seul `pip` (et peut-être aussi `setuptools`) est installé malgré la présence possible de nombreux autres paquets sur votre système.
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +---------------------------
```suggestion
## Ajout de tests automatiques
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Vous pouvez laisser le fichier `__init__.py` vide, il sert uniquement à marquer que le dossier est un package pour python. À l'intérieur du fichier `test_tartempion.py` vous pouvez écrire ceci:
```suggestion
Vous pouvez laisser le fichier `__init__.py` vide, il sert uniquement à indiquer que le dossier est un package pour python. À l'intérieur du fichier `test_tartempion.py` vous pouvez écrire ceci:
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Une fois le test écrit, assurez vous de vous positionner à la racine de votre projet dans votre terminal. Vous pouvez ensuite lancer les tests avec la commande `python3 -m unittest` (utilisez `py -m
```suggestion
Une fois le test écrit, assurez vous de vous positionner à la racine de votre projet dans votre terminal. Vous pouvez ensuite lancer les tests avec la commande `python3 -m unittest` (utilisez `py -m unittest` sur Windows, pensez à passer par votre environnement virtuel si vous en avez un). Vous devriez avoir un résultat comme suit:
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Vous pouvez ajouter autant de modules de tests et de classe que vous voulez. Il peut être judicieux de définir les tests dans des modules différents en fonction de la partie du code qu'ils testent.
```suggestion
Vous pouvez ajouter autant de modules de tests et de classes que vous voulez. Il peut être judicieux de définir les tests dans des modules différents en fonction de la partie du code qu'ils testent.
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +----------------------------------
```suggestion
## Création d'une archive installable
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +La première partie du fichier, `[project]`, défini l'ensemble des méta-données relatives à votre projet. Il existe en tout plus d'une vingtaine de méta-données différentes, nous avons décider de ne g
```suggestion
La première partie du fichier, `[project]`, défini l'ensemble des méta-données relatives à votre projet. Il existe en tout plus d'une vingtaine de méta-données différentes, nous avons décidé de ne garder que les plus essentielles d'entre elles ici. La liste complète est défini dans la PEP [621]. Pensez à changer les valeurs pour le nom, la description et les auteurs. Pensez aussi à déclarer vos dépendances, si vous en avez, pour qu'elles soient automatiquement installées avec votre projet.
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +**Important**, le champ `name` dans ce fichier n'est pas obligé d'être le même que le nom de votre dossier. Il est d'ailleurs conseillé d'ajouter votre pseudo ou un autre élément unique à la fin pour
```suggestion
**Important**, le champ `name` dans ce fichier n'est pas obligatoirement le même que le nom de votre dossier. Il est d'ailleurs conseillé d'ajouter votre pseudo ou un autre élément unique à la fin pour vous assurer qu'il sera unique sur internet. Dans cet exemple nous avons ajouté `_NaN` pour "Not a Name", ce blog.
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +La seconde partie du fichier, `[build-system]`, décrit quels outils seront utilisées pour créer les archives pour votre projet. Cette partie est obligatoire mais vous pouvez vous contenter de garder
```suggestion
La seconde partie du fichier, `[build-system]`, décrit quels outils seront utilisés pour créer les archives pour votre projet. Cette partie est obligatoire mais vous pouvez vous contenter de garder celle de l'exemple.
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Une fois le fichier `pyproject.toml` compléter, vous pouvez utiliser [build] pour créer une archive de votre fichier. Placez-vous à la racine de votre projet et lancer la commande `.env/bin/pyproject
```suggestion
Une fois le fichier `pyproject.toml` complété, vous pouvez utiliser [build] pour créer une archive de votre fichier. Placez-vous à la racine de votre projet et lancer la commande `.env/bin/pyproject-build` (`.env\Scripts\pyproject-build` sur Windows). La commande est très verbeuse, parmi toutes les lignes affichées vous devriez voir celles-ci:
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +### build
Build ?
je sais qu'il s'agit d'une commande mais un titre sans maj je trouve que ça fait chelou

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +La première archive au format `.tar.gz` ou `.zip` est une *distribution source*, elle est principalement à destination des développeurs. La seconde archive au format `.whl` est une *distribution whee
rofl pour la traduction de wheel x)

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +-----------------------
```suggestion
## Configuration de VSCode
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +*Vous avez besoin de cette étape si vous voulez que VSCode arrête de lever des erreurs pour des problèmes d'import et/ou pouvoir lancer votre projet directement depuis la console de VSCode.*
je suis pas certain que ça soit pertinent de parler de vscode/pycharm dans cet article, la configuration de son éditeur/IDE me semble être un sujet à part, mais bon

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +------------------------
```suggestion
## Configuration de PyCharm
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +----------------------
```suggestion
## Choix des technologies
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +<!-- Lazor: arrêtez de casser les couilles et utilisez Sublime Text avec un terminal. -->
subtile

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Tout au long de ce document, il n'a jamais été présenté qu'une seule approche, un seul choix. Il s'agit d'un choix assumé par la nécessité de dissimuler aux débutants toute la complexité réelle qui s
très bonne idée cette section

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Nous avons préféré présenter la structure à plat car elle est plus simple. La structure imbriquée n'est utile que lorsqu'un même projet se décline en plusieurs modules co-dépendants les uns des autre
```suggestion
Nous avons préféré présenter la structure à plat car elle est plus simple. La structure imbriquée n'est utile que lorsqu'un même projet se décline en plusieurs modules dépendants les uns des autres qui ne doivent pas partager un même *namespace*. Plutôt rare comme cas de figure.
```
"co-dependants" ou "dependants les uns des autres", il faut choisir

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Un autre avantage de la structure à plat est de pouvoir lancer le programme et les tests automatiques depuis la racine du projet sans installation. Avec la structure imbriquée, il est obligatoire de
```suggestion
Un autre avantage de la structure à plat est de pouvoir lancer le programme et les tests automatiques depuis la racine du projet sans installation. Avec la structure imbriquée, il est obligatoire de recourir à un paquet installé en mode éditable dans l'environnement virtuel courant pour lancer et tester l'application. Cependant cet avantage peut aussi s'avérer désavantageux lorsqu'il s'agit de créer un package, par exemple certains fichiers *pourraient* apparaître comme accessibles sans réellement l'être[^10].
```
un avantage désavantageux, hmm

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Il existe plusieurs logiciels capable de créer et de gérer des environnements virtuels parmi lesquels [venv], [virtualenv] et [pyenv-virtualenv]. Il existe aussi plusieurs logiciels de gestion de pro
```suggestion
Il existe plusieurs logiciels capables de créer et de gérer des environnements virtuels parmi lesquels [venv], [virtualenv] et [pyenv-virtualenv]. Il existe aussi plusieurs logiciels de gestion de projet python "tout-en-un" qui intègrent un environnement virtuel par défaut comme [hatch], [pdm] ou [poetry].
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Il existe plusieurs bibliothèques pour écrire et lancer des tests unitaires sur Python. On peut citer [unittest], [pytest], [nose], [ward] et [hammett]. Parmi tous ces bibliothèques, les deux plus ré
```suggestion
Il existe plusieurs bibliothèques pour écrire et lancer des tests unitaires sur Python. On peut citer [unittest], [pytest], [nose], [ward] et [hammett]. Parmi toutes ces bibliothèques, les deux plus répandues sont [unittest] et [pytest]. Malgré une plus grande préférence des gens pour [pytest] à [unittest], [unittest] reste utilisé par une majorité de projets et est disponible de base.
```
"malgré que" = bad

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Il a existé une époque entre 2018 et 2021 pendant laquelle les mises à jour de [setuptools] lagaient derrière ces nouveaux outils en terme de l'adoption des standards (PEP-[517]/[518]/[621]) et penda
```suggestion
Il a existé une époque entre 2018 et 2021 pendant laquelle les mises à jour de [setuptools] stagnaient derrière ces nouveaux outils en terme d'adoption des standards (PEP-[517]/[518]/[621]) et pendant laquelle il nous aurait été difficile de suivre la PyPA dans ses recommandations. Heureusement, la [version 61] de [setuptools] (avril 2021) a ajouté le support pour la PEP-[621] (*Storing project metadata in pyproject.toml*) et il est depuis lors raisonnable d'utiliser setuptools à nouveau.
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Nous avons utilisé setuptools dans cet article comme il est compatible avec les PEP [517] et [621], qu'il semble toujours être le seul outil capable de gérer des extensions écrites en C et qu'il est
```suggestion
Nous avons utilisé setuptools dans cet article car il est compatible avec les PEP [517] [621], il semble toujours être le seul outil capable de gérer des extensions écrites en C et il est toujours le seul outil recommandé[^11] par la PyPA.
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Parmi tous les éditeurs de texte et IDE disponibles pour Python, nous n'avons décidé de n'en documenter que deux, [VSCode] et [PyCharm]. Cette décision repose sur l'expérience des auteurs quant à la
```suggestion
Parmi tous les éditeurs de texte et IDE disponibles pour Python, nous avons décidé de n'en documenter que deux, [VSCode] et [PyCharm]. Cette décision repose sur l'expérience des auteurs quant à la fréquence des questions relatives à l'utilisation combinées des environnements virtuels et des éditeurs de texte/IDE, expérience qui a été confirmée par plusieurs sondages.
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Ces deux aspects, le bouton "run" et le linter, font qu'il est crucial de correctement configuré ces IDE pour qu'il utilise le bon environnement virtuel. Ne pas configurer d'environnement virtuel est
```suggestion
Ces deux aspects, le bouton "run" et le linter, font qu'il est crucial de correctement configurer ces IDE pour qu'ils utilisent le bon environnement virtuel. Ne pas configurer d'environnement virtuel est une source commune d'erreur chez les débutants qui se plaignent soit qu'ils n'arrivent pas à installer de bibliothèques soit que leur IDE ne reconnaît pas la bibliothèque qu'ils viennent d'installer. Les deux affirmations sont en fait la conséquence du même problème, la bibliothèque n'a pas été installée dans le même environnement virtuel que celui utilisé dans l'IDE.
```

2023-04-05 18:39 UTC, Equinox4 commented on langages/python/comment-structurer-un-projet-python.md
> +Il est rare de voir des questions de ce genre pour d'autres IDE, nous n'avons donc pas chercher à les documenter dans cet article. Nous ne les recommandons d'ailleurs pas plus que d'autres éditeur de
```suggestion
Il est rare de voir des questions de ce genre pour d'autres IDE, nous n'avons donc pas cherché à les documenter dans cet article. Nous ne les recommandons d'ailleurs pas plus que d'autres éditeur de texte / IDE.
```

2023-04-05 18:39 UTC, Equinox4 requested changes, later dismissed
Petite passe rapide concernant essentiellement l'orthographe.
Article très intéressant, certains passage mériteraient d'être un peu reformulés pour moins ressembler à du parler.

2023-04-05 22:39 UTC, Julien00859 reviewed
J'ai adopté l'ensemble de vos suggestions @Iltotore  @Equinox4 sauf à quelques endroits où j'ai expliqué ce que j'ai fait à la place. Je vous laisse relire et "resolve conversation" si vous êtes ok :)

2023-04-05 22:39 UTC, Julien00859 commented on langages/python/comment-structurer-un-projet-python.md
> +    Copyright (c) votre nom et prénom
Tu veux bien proposer un texte alternatif ?

2023-04-05 22:39 UTC, Julien00859 commented on langages/python/comment-structurer-un-projet-python.md
> +Si vous voulez plutôt rendre votre projet open-source, avec plus ou moins de conditions, vous pouvez copier/coller le texte d'une licence existante. Vous trouverez une liste de licence communes sur l
Tu veux bien proposer un texte alternatif ?

2023-04-05 22:39 UTC, Julien00859 commented on langages/python/comment-structurer-un-projet-python.md
> +Vous devez certainement lancer votre programme soit en faisant `python3 tartempion.py` depuis votre terminal soit en cliquant sur le bouton "run" tout en étant sur le fichier `tartempion.py` dans vot
je ne gardez pas cette suggestion, je pose un postulat ici "une application structurée de la sorte, vous la lancez de cette manière", le "devez" est comme le "lancez" ici. Tu as peut-être une autre suggestion ?

2023-04-05 22:39 UTC, Julien00859 commented on langages/python/comment-structurer-un-projet-python.md
> +Vous pouvez aussi lister les modules supplémentaires qui sont installés dans cet environnement virtuel en faisant `./.env/bin/pip list` (`.\.env\Scripts\` sur Windows), vous devriez constater que seu
j'ai opté pour "possible présence"

2023-04-05 22:39 UTC, Julien00859 commented on langages/python/comment-structurer-un-projet-python.md
> +La première archive au format `.tar.gz` ou `.zip` est une *distribution source*, elle est principalement à destination des développeurs. La seconde archive au format `.whl` est une *distribution whee
ahah pun intended :D

2023-04-05 22:39 UTC, Julien00859 commented on langages/python/comment-structurer-un-projet-python.md
> +*Vous avez besoin de cette étape si vous voulez que VSCode arrête de lever des erreurs pour des problèmes d'import et/ou pouvoir lancer votre projet directement depuis la console de VSCode.*
ce sont des questions vraiment récurrentes, typiquement le gars va installer une lib en global mais sans l'installer dans son environnement virtuel... il vient ensuite pleurer "pk il trouv pa la lib ? jlai instalé avec pip pourtant"

2023-04-05 22:39 UTC, Julien00859 commented on langages/python/comment-structurer-un-projet-python.md
> +<!-- Lazor: arrêtez de casser les couilles et utilisez Sublime Text avec un terminal. -->
bill

2023-04-05 22:39 UTC, Julien00859 commented on langages/python/comment-structurer-un-projet-python.md
> +<!-- Lazor: arrêtez de casser les couilles et utilisez Sublime Text avec un terminal. -->
en vrai j'attend que quelqu'un propose une PR pour la partie pycharm, je ne compte pas l'écrire moi-même

2023-04-05 22:39 UTC, Julien00859 commented on langages/python/comment-structurer-un-projet-python.md
> +Un autre avantage de la structure à plat est de pouvoir lancer le programme et les tests automatiques depuis la racine du projet sans installation. Avec la structure imbriquée, il est obligatoire de
j'ai reformulé

2023-04-05 22:39 UTC, Julien00859 commented on langages/python/comment-structurer-un-projet-python.md
> +Il existe plusieurs bibliothèques pour écrire et lancer des tests unitaires sur Python. On peut citer [unittest], [pytest], [nose], [ward] et [hammett]. Parmi tous ces bibliothèques, les deux plus ré
j'ai reformulé

2023-04-05 22:39 UTC, Julien00859 commented on langages/python/comment-structurer-un-projet-python.md
> +Nous avons utilisé setuptools dans cet article comme il est compatible avec les PEP [517] et [621], qu'il semble toujours être le seul outil capable de gérer des extensions écrites en C et qu'il est
j'ai répété *car* pour chaque élément

2023-04-06 18:21 UTC, Iltotore approved these changes

2023-04-07 21:30 UTC, Elanis approved these changes
Approbation du groupe en vocal

2023-04-07 21:31 UTC, merged