add: Programmer en Scala 3: Mutabilité et boucles
NotANameServer/Not-a-Hub pull request #65
Opened 2023-05-01 11:43 UTC by Iltotore

Quatrième chapitre de la série sur l'apprentissage du Scala 3 portant sur la mutabilité et les boucles. Les points suivants sont abordés:
- Mutabilité via `var`
- Boucle while
- Boucle for

Pour l'instant, la boucle for est uniquement utilisée pour répéter une action "n fois". J'en reparlerai de le prochain chapitre qui portera sur les structures de données courantes (List (ou Seq), Set, Map). Je ferai probablement avant ce chapitre un mini projet type "Juste Prix" avec correction pour permettre au lecteur de mettre en pratique ce qu'il a appris dans les chapitres d'avant.

2023-05-07 12:08 UTC, Equinox4 requested changes

2023-05-07 12:08 UTC, Equinox4 commented on langages/scala/programmer-en-scala-3-mutabilite-et-boucles.md
> +Nous pouvons le faire en Scala en utilisant un autre mot clé: `var`. À l'instar de `val`, `var` permet de déclarer une variable à la différence près que celle-ci peut-être changée.
```suggestion
Nous pouvons le faire en Scala en utilisant un autre mot clé: `var`. À l'instar de `val`, `var` permet de déclarer une variable à la différence près que la valeur de celle-ci peut-être changée.
```

2023-05-07 12:08 UTC, Equinox4 commented on langages/scala/programmer-en-scala-3-mutabilite-et-boucles.md
> +Dans le cas des boules de feu de Mario, nous pouvons faire le code suivant :
```suggestion
Dans le cas des boules de feu de Mario, nous pouvons écrire le code suivant :
```

2023-05-07 12:08 UTC, Equinox4 commented on langages/scala/programmer-en-scala-3-mutabilite-et-boucles.md
> +Dans le cas des boules de feu de Mario, nous pouvons faire le code suivant :
"faire" c'est un peu comme les div en html, à n'utiliser qu'en dernier recours 😄

2023-05-07 12:08 UTC, Equinox4 commented on langages/scala/programmer-en-scala-3-mutabilite-et-boucles.md
> +Nous verrons prochainement d'autres utilisations de la boucle `for` dans un prochain article ainsi qu'un projet pour mettre en œuvre les notions que nous avons précédemment vues.
"Nous verrons prochainement dans un prochain article"
à reformuler

2023-05-07 13:20 UTC, Iltotore commented on langages/scala/programmer-en-scala-3-mutabilite-et-boucles.md
> +Nous verrons prochainement d'autres utilisations de la boucle `for` dans un prochain article ainsi qu'un projet pour mettre en œuvre les notions que nous avons précédemment vues.
Oups j'ai oublié d'enlever le "prochainement"

2023-05-08 10:17 UTC, Equinox4 commented on langages/scala/programmer-en-scala-3-mutabilite-et-boucles.md
> +En anglais, "while" peut se traduire en "alors que"/"tant que". La boucle `while` répète une action tant qu'une condition (représentée par un booléen) est satisfaite.
la condition c'est plutôt une expression dont le résultat de l'évaluation sera un booléen, si on veut être précis.
Je le précise parce que plus loin on a pour exemple `restant > 0` et on pourrait se demander où se trouve le booléen (du point de vue d'un débutant).

2023-05-08 10:17 UTC, Equinox4 commented on langages/scala/programmer-en-scala-3-mutabilite-et-boucles.md
> +  val rebondActuel = i+1
```suggestion
  val rebondActuel = i + 1
```

2023-05-08 10:20 UTC, Equinox4 commented on langages/scala/programmer-en-scala-3-mutabilite-et-boucles.md
> +En anglais, "while" peut se traduire en "alors que"/"tant que". La boucle `while` répète une action tant qu'une condition (représentée par un booléen) est satisfaite.
cela dit, les conditions sont expliquées dans un précédent article donc en vrai ça passe

2023-05-08 12:17 UTC, Iltotore commented on langages/scala/programmer-en-scala-3-mutabilite-et-boucles.md
> +En anglais, "while" peut se traduire en "alors que"/"tant que". La boucle `while` répète une action tant qu'une condition (représentée par un booléen) est satisfaite.
> où se trouve le booléen (du point de vue d'un débutant).

Normalement ça a été couvert par le chapitre juste avant et qui parle des différents opérateurs booléens comme `>`

2023-05-08 18:51 UTC, Equinox4 commented on langages/scala/programmer-en-scala-3-mutabilite-et-boucles.md
> +En anglais, "while" peut se traduire en "alors que"/"tant que". La boucle `while` répète une action tant qu'une condition (représentée par un booléen) est satisfaite.
yep, j'ai vu après

2023-05-13 08:32 UTC, Elanis commented on langages/scala/programmer-en-scala-3-mutabilite-et-boucles.md
> +Nous avons vu précédemment un moyen de stocker des valeurs sous des noms grâce aux variables. Cependant, nous n'avons jusqu'à présent qu'utilisé des variables dites "immuables", que l'on ne peut modi
```suggestion
Nous avons vu précédemment un moyen de stocker des valeurs sous un nom grâce aux variables. Cependant, nous n'avons jusqu'à présent qu'utilisé des variables dites "immuables", que l'on ne peut modifier. Vous avez peut-être tenté de faire la chose suivante :
```

Ca me parrait moins bizarre comme ca 😄

2023-05-13 08:32 UTC, Elanis commented on langages/scala/programmer-en-scala-3-mutabilite-et-boucles.md
> +Ici, `restant` va prendre à la première itération (aka "tour de boucle") la valeur 5, puis 4 pour la seconde itération, puis 3, ... jusqu'à 1. `5 until 0` veut dire "de 5 jusqu'à 0 exclus"
```suggestion
Ici, `restant` va prendre à la première itération (tour de boucle) la valeur 5, puis 4 pour la seconde itération, puis 3, ... jusqu'à 1. `5 until 0` veut dire "de 5 jusqu'à 0 exclus"
```
Je suis aussi fada du "aka", mais j'éviterai de l'utiliser pour un public peut être pas habitué aux anglicismes dans le genre.

2023-05-13 11:30 UTC, Iltotore commented on langages/scala/programmer-en-scala-3-mutabilite-et-boucles.md
> +Nous avons vu précédemment un moyen de stocker des valeurs sous des noms grâce aux variables. Cependant, nous n'avons jusqu'à présent qu'utilisé des variables dites "immuables", que l'on ne peut modi
Et plus français 😅

2023-05-14 10:06 UTC, Elanis approved these changes

2023-05-14 19:05 UTC, Equinox4 approved these changes

2023-05-14 19:05 UTC, merged

2023-05-14 20:26 UTC, Julien00859 reviewed
I know the indexer is buggy but plz pay attention

2023-05-14 20:26 UTC, Julien00859 commented on index.md
> +* [Programmer en Python, quel IDE choisir](/langages/python/programmer-en-python-quel-ide-choisir) [<kbd>langages</kbd>](/langages) [<kbd>python</kbd>](/langages/python)
bad diff

2023-05-14 20:26 UTC, Julien00859 commented on langages/index.md
> +* [Programmer en Python, quel IDE choisir](/langages/python/programmer-en-python-quel-ide-choisir) [<kbd>langages</kbd>](/langages) [<kbd>python</kbd>](/langages/python)
bad diff