edit: ajout de liens entre articles
NotANameServer/Not-a-Hub pull request #66
Opened 2023-05-14 20:13 UTC by JeanCASPAR

J'ai ajouté des liens vers l'article précédent/suivant dans la série d'article Programmer en Scala 3, pour que ce soit plus facile à lire.

2023-05-18 02:26 UTC, Julien00859 requested changes

2023-05-18 02:26 UTC, Julien00859 commented on langages/scala/programmer-en-scala-3-booleens-et-conditions.md
> +*Précédemment : [Types et variables](./programmer-en-scala-3-types-et-variables.md)*
```suggestion
*Précédemment : [Types et variables](./programmer-en-scala-3-types-et-variables)*
```

lorsqu'on met le .md directement, ça force parfois le téléchargement de l'article
lorsqu'on met le .html parfois on a des mauvaises surprises

au final ne rien mettre comme extension c'est ce qui marche le mieux

2023-05-18 02:26 UTC, Julien00859 commented on langages/scala/programmer-en-scala-3-booleens-et-conditions.md
> +*Précédemment : [Types et variables](./programmer-en-scala-3-types-et-variables.md)*
faut corriger partout

2023-05-18 22:43 UTC, Julien00859 approved these changes
lgtm, waiting for @Iltotore or @TheElectronWill

2023-05-18 22:45 UTC, Equinox4 requested changes, later dismissed

2023-05-18 22:45 UTC, Equinox4 commented on langages/python/index.md
> -* [Programmer en Python, quel IDE choisir](/langages/python/programmer-en-python-quel-ide-choisir) [<kbd>langages</kbd>](/langages) [<kbd>python</kbd>](/langages/python)
bad index

2023-05-19 06:09 UTC, Iltotore approved these changes
Les articles précédents et suivants sont les bons.

2023-05-20 10:59 UTC, TheElectronWill commented
LGTM

2023-05-21 12:36 UTC, merged