new: how to cleanup git branches before a review
NotANameServer/Not-a-Hub pull request #73
Opened 2023-05-28 16:01 UTC by Julien00859

Using git on a daly basic, it is often hard to always commit meaningful commit messages. Often we just want to push a work in progress for the sake of having a backup on GitHub. In this new tutorial we explain how to best use git during the lifetime of a branch, whether it is during initial development, PR preparation or review feedback.

2023-05-28 17:52 UTC, JeanCASPAR commented on architecture/faire-des-commits-au-quotidient.md
> +Vous avez aussi commencé à travailler avec d'autres personnes et donc à faire ou à recevoir des *reviews* sur GitHub. Vous êtes donc tombé sur une branche avec des dizaines de commits, résultat de la
Pluriel avec vous
```suggestion
Vous avez aussi commencé à travailler avec d'autres personnes et donc à faire ou à recevoir des *reviews* sur GitHub. Vous êtes donc tombés sur une branche avec des dizaines de commits, résultat de la pratique de commit le travail effectué toutes les deux/trois heures, branche que vous vous retrouvez soudainement à review... Dur travail...
```

2023-05-28 17:56 UTC, JeanCASPAR commented on architecture/faire-des-commits-au-quotidient.md
> +Attention cependant, cette approche ne fonctionne pas si la branche contient plusieurs travaux indépendants, par exemple un petit correctif de bug en marge du travail principal. Imaginez la situation
Pluriel avec vous
```suggestion
Attention cependant, cette approche ne fonctionne pas si la branche contient plusieurs travaux indépendants, par exemple un petit correctif de bug en marge du travail principal. Imaginez la situation si dans quelques semaines vous êtes amenés à *revert* le commit en question, vous ré-introduiriez le bug qui avait été corrigé. Idéalement il aurait du y avoir deux commits séparés, pas possible d'utiliser *squash and merge* dans ce cas là.
```

2023-05-28 18:00 UTC, Equinox4 requested changes

2023-05-28 18:00 UTC, Equinox4 commented on architecture/faire-des-commits-au-quotidient.md
> +Vous avez aussi commencé à travailler avec d'autres personnes et donc à faire ou à recevoir des *reviews* sur GitHub. Vous êtes donc tombé sur une branche avec des dizaines de commits, résultat de la
un peu trop de "donc"

2023-05-28 18:00 UTC, Equinox4 commented on architecture/faire-des-commits-au-quotidient.md
> +Cette article vous explique comment réconcillier les deux, comment continuer à faire des petits commits incrémentaux pendant le développement, comment nettoyer sa branche juste avant d'ouvrir la pull
```suggestion
Cet article vous explique comment réconcilier les deux, comment continuer à faire des petits commits incrémentaux pendant le développement, comment nettoyer sa branche juste avant d'ouvrir la pull-request et comment continuer à commit dessus. En des termes plus techniques, cet article vous explique comment réécrire l'historique de vos branches.
```

2023-05-28 18:00 UTC, Equinox4 commented on architecture/faire-des-commits-au-quotidient.md
> +Attention cependant, cette approche ne fonctionne pas si la branche contient plusieurs travaux indépendants, par exemple un petit correctif de bug en marge du travail principal. Imaginez la situation
```suggestion
Attention cependant, cette approche ne fonctionne pas si la branche contient plusieurs travaux indépendants, par exemple un petit correctif de bug en marge du travail principal. Imaginez la situation si dans quelques semaines vous étiez amenés à *revert* le commit en question, vous ré-introduiriez le bug qui avait été corrigé. Idéalement il aurait dû y avoir deux commits séparés, pas possible d'utiliser *squash and merge* dans ce cas là.
```

2023-05-28 18:00 UTC, Equinox4 commented on architecture/faire-des-commits-au-quotidient.md
> +Une seconde solution est de décider de ne pas se tracasser de ses commits le temps du développement, de faire des petits commits type "wip" régulièrement et de les envoyer sur GitHub histoire d'avoir
```suggestion
Une seconde solution est de décider de ne pas se préoccuper de ses commits le temps du développement, de faire des petits commits type "wip" régulièrement et de les envoyer sur GitHub histoire d'avoir une copie quelque part. Ensuite au moment venu de proposer sa branche dans une PR, d'annuler uniquement les commits tout en gardant les fichiers modifiés sur le disque, ouvrant ainsi la possibilité de *refaire* des commits bien propre.
```

2023-05-28 18:00 UTC, Equinox4 commented on architecture/faire-des-commits-au-quotidient.md
> +Une fois la commande exécutée, vous pouvez recréer vos commits un à un cette fois en prenant le temps de rédiger des beaux messages et en séparant dans différents commits ce qui doit l'être.
```suggestion
Une fois la commande exécutée, vous pouvez recréer vos commits un à un cette fois en prenant le temps de rédiger de beaux messages et en séparant dans différents commits ce qui doit l'être.
```

2023-05-28 18:00 UTC, Equinox4 commented on architecture/faire-des-commits-au-quotidient.md
> +Utiliser `commit` avec l'option `--amend` permet de modifier le tout dernier commit. Vous n'avez donc qu'à faire vos modifications, les `git add` et ensuite `git commit --amend` pour intégrer ces mod
```suggestion
Utiliser `commit` avec l'option `--amend` permet de modifier le tout dernier commit. Vous n'avez donc qu'à faire vos modifications, les `git add` et ensuite `git commit --amend` pour intégrer ces modifications dans le dernier commit. Vous aurez aussi l'occasion de modifier le message de commit, très pratique pour corriger les fautes d'orthographe.
```

2023-05-28 18:00 UTC, Equinox4 commented on architecture/faire-des-commits-au-quotidient.md
> +Utiliser `commit` avec l'option `--fixup` permet de créer un nouveau commit qui pourra être intégré avec n'importe commit existant. Comme pour *amend*, vous commencez par faire vos modifications, les
```suggestion
Utiliser `commit` avec l'option `--fixup` permet de créer un nouveau commit qui pourra être intégré avec n'importe quel commit existant. Comme pour *amend*, vous commencez par faire vos modifications, les `git add` et ensuite `git commit --fixup numéro-du-commit`, où "numéro-du-commit" correspond au commit à modifier. Contrairement à *amend* qui modifie directement le commit, *fixup* crée un *nouveau* commit par dessus tous les autres et il reste encore une étape à faire pour l'intégrer au bon endroit.
```

2023-05-28 18:00 UTC, Equinox4 commented on architecture/faire-des-commits-au-quotidient.md
> +Git propose un outil pour réordonner des commits et les fusionner entre eux, cet outil s'appelle le *rebase interactif* et permet de traiter automatiquement les commits *fixup*. Typiquement vous alle
```suggestion
Git propose un outil pour réordonner des commits et les fusionner, cet outil s'appelle le *rebase interactif* et permet de traiter automatiquement les commits *fixup*. Typiquement vous allez utiliser la commande suivante: `git rebase -i --autosquash numéro-de-commit` où le numéro de commit correspond à un commit suffisamment loin dans le passé, vous pouvez mettre HEAD~10 (le 10e précédent commit) pour brasser large, vous pouvez aussi mettre le même commit que vous aviez mis dans l'étape de *reset* plus haut, c'est à dire le commit sur lequel votre branche est basée.
```
je n'aime pas trop l'utilisation du verbe "mettre", on doit pouvoir trouver quelque chose de plus élégant

2023-05-28 18:00 UTC, Equinox4 commented on architecture/faire-des-commits-au-quotidient.md
> +Pendant l'étape du *rebase*, une fenêtre s'est ouverte pour vous demander comment réordonner l'historique, avec l'option `--autosquash` les commits fixup ont déjà été déplacés au bon endroit et la bo
```suggestion
Pendant l'étape du *rebase*, une fenêtre s'est ouverte pour vous demander comment réordonner l'historique, avec l'option `--autosquash` les commits fixup ont déjà été déplacés au bon endroit et la bonne action a déjà été sélectionnée, vous pouvez donc simplement sauvegarder et quitter.
```

2023-05-28 18:00 UTC, Equinox4 commented on architecture/faire-des-commits-au-quotidient.md
> +Dans cet article nous avons identifié différentes situations communes du cycle de vie d'une branche. Nous avons vu qu'on pouvait très bien créer des petits commits "wip" incrémentaux le temps du déve
```suggestion
Dans cet article nous avons identifié différentes situations communes du cycle de vie d'une branche. Nous avons vu qu'on peut très bien créer des petits commits "wip" incrémentaux le temps du développement car il est parfaitement possible de tout nettoyer juste avant de proposer sa branche en pull-request. Nous avons aussi vu qu'une fois qu'un historique est nettoyé, qu'il est toujours possible de continuer à créer des petit commits "fixup" incrémentaux qui pourront être injectés au bon endroit dans l'historique le moment venu.
```

2023-05-28 19:30 UTC, Julien00859 commented on architecture/faire-des-commits-au-quotidient.md
> +Git propose un outil pour réordonner des commits et les fusionner entre eux, cet outil s'appelle le *rebase interactif* et permet de traiter automatiquement les commits *fixup*. Typiquement vous alle
j'ai écrit "écrire" à la place

2023-05-28 19:32 UTC, Julien00859 commented on architecture/faire-des-commits-au-quotidient.md
> +Vous avez aussi commencé à travailler avec d'autres personnes et donc à faire ou à recevoir des *reviews* sur GitHub. Vous êtes donc tombé sur une branche avec des dizaines de commits, résultat de la
j'en ai remplacé un par "ainsi"

2023-05-28 20:11 UTC, Equinox4 requested changes

2023-05-28 20:11 UTC, Equinox4 commented on architecture/faire-des-commits-au-quotidient.md
> +Une fois l'historique correctement réécrit, il sera nécessaire d'envoyer les changements sur GitHub avec `push`, GitHub vous empéchera d'envoyer vos modifications parce que l'historique des deux bran
```suggestion
Une fois l'historique correctement réécrit, il sera nécessaire d'envoyer les changements sur GitHub avec `push`, GitHub vous empêchera d'envoyer vos modifications parce que l'historique des deux branches (locale sur votre machine vs distante sur GitHub) n'est plus cohérent. C'est normal puisque l'historique vient d'être réécrit, dans cette situation il est donc normal d'utiliser `push` avec `--force-with-lease`.
```

2023-05-28 20:11 UTC, Equinox4 commented on architecture/faire-des-commits-au-quotidient.md
> +De tous ces commits, uniquement les trois premiers (`c66a677`, `6554ca8` et `bc92aa7`) font partie de notre branche, les deux derniers sont d'anciens commits de la branche master. Puisque nous voulon
```suggestion
De tous ces commits, uniquement les trois premiers (`c66a677`, `6554ca8` et `bc92aa7`) font partie de notre branche, les deux derniers sont d'anciens commits de la branche master. Puisque nous voulons annuler tous les commits de notre branche, nous voulons déplacer (*reset*) notre branche sur le 1er commit ne faisant par partie de notre travail, nous voulons donc la déplacer sur `d64706e edit: ajout de liens entre articles`.
```

2023-05-28 20:11 UTC, Equinox4 commented on architecture/faire-des-commits-au-quotidient.md
> +Git propose un outil pour réordonner des commits et les fusionner, cet outil s'appelle le *rebase interactif* et permet de traiter automatiquement les commits *fixup*. Typiquement vous allez utiliser
```suggestion
Git propose un outil pour réordonner des commits et les fusionner, cet outil s'appelle le *rebase interactif* et permet de traiter automatiquement les commits *fixup*. Typiquement vous allez utiliser la commande suivante: `git rebase -i --autosquash numéro-de-commit` où le numéro de commit correspond à un commit suffisamment loin dans le passé, vous pouvez écrire HEAD~10 (le 10ème précédent commit) pour brasser large, vous pouvez aussi mettre le même commit que vous aviez mis dans l'étape de *reset* plus haut, c'est à dire le commit sur lequel votre branche est basée.
```

2023-05-28 20:11 UTC, Equinox4 commented on architecture/faire-des-commits-au-quotidient.md
> +Dans cet article nous avons identifié différentes situations communes du cycle de vie d'une branche. Nous avons vu qu'on peut très bien créer des petits commits "wip" incrémentaux le temps du dévelop
```suggestion
Dans cet article nous avons identifié différentes situations communes du cycle de vie d'une branche. Nous avons vu qu'on peut très bien créer des petits commits "wip" incrémentaux le temps du développement car il est parfaitement possible de tout nettoyer juste avant de proposer sa branche en pull-request. Nous avons aussi vu qu'une fois qu'un historique est nettoyé, il est toujours possible de continuer à créer des petit commits "fixup" incrémentaux qui pourront être injectés au bon endroit dans l'historique le moment venu.
```

2023-05-28 20:38 UTC, Equinox4 approved these changes

2023-05-29 08:29 UTC, Elanis requested changes

2023-05-29 08:29 UTC, Elanis commented on architecture/faire-des-commits-au-quotidient.md
> +Faire des commits au quotidient
```suggestion
Faire des commits au quotidien
```

2023-05-29 08:29 UTC, Elanis commented on architecture/faire-des-commits-au-quotidient.md
> +Vous savez donc comment faire des beaux [messages de commit dans git] mais au moment de passer à la pratique vous êtes perdus. Vous aviez l'habitude de créer des nouveaux commits régulièrement, ne se
Pour moi, commit en fin de journée et régulièrement sont opposé donc la phrase me gène un peu

2023-05-29 08:29 UTC, Elanis commented on architecture/faire-des-commits-au-quotidient.md
> +Cet article vous explique comment réconcilier les deux, comment continuer à faire des petits commits incrémentaux pendant le développement, comment nettoyer sa branche juste avant d'ouvrir la pull-re
"avant d'ouvrir la pull-request"

D'experience (vécu avec mes élèves recemment), les gens ne savent pas toujours ce qu'est une pull request, ou appellent ca une merge request.

J'aurais bien remplacé par une formulation plus simple du genre "avant de demander une relecture" ou un truc dans le genre.

2023-05-29 08:29 UTC, Elanis commented on architecture/faire-des-commits-au-quotidient.md
> +Une première solution (très facile) est de faire fi de l'historique des commits dans la branche, vous vous dites qu'au final ce qui compte c'est ce qui arrivera sur la branche `main` pour la postérit
```suggestion
Une première solution (très facile) est de faire fi de l'historique des commits dans la branche, vous vous dites qu'au final ce qui compte c'est ce qui arrivera sur la branche de destination pour la postérité, que vous pouvez vous débrouiller pour votre review avec ce qui est écrit dans le message de la pull-request.
```
En git flow ce sera souvent dev/develop, et parfois main/master ou une autre branche de feature. Donc je pense que "branche de destination" est plus clair.

2023-05-29 08:29 UTC, Elanis commented on architecture/faire-des-commits-au-quotidient.md
> +Super facile donc ! Au moment d'ouvrir votre pull-request, vous pouvez prendre le temps d'écrire un bon titre et un bon message. Vos collègues reviewers seront contents parce qu'il y aura une bonne d
```suggestion
Super facile donc ! Au moment d'ouvrir votre pull-request, vous pouvez prendre le temps d'écrire un bon titre et un bon message. Vos collègues reviewers seront contents parce qu'il y aura une bonne description du travail, description qui se retrouvera aussi dans l'historique de la branche de destination une fois la PR mergée !
```
Same

2023-05-29 08:29 UTC, Elanis commented on architecture/faire-des-commits-au-quotidient.md
> +Attention, il est impératif que vous utilisiez `reset` **sans** les options `--hard` ou `--soft`. `--hard` aurait pour effet d'annuler toutes vos modifications sur disque, dans le cas présent vous vo
Peut être formater sous forme de liste ? Ca sera peut être plus digeste à lire je pense.
```suggestion
Attention, il est impératif que vous utilisiez `reset` **sans** les options `--hard` ou `--soft`:  
- `--hard` aurait pour effet d'annuler toutes vos modifications sur disque, dans le cas présent vous voulez justement conserver toutes ces modifications. 
- `--soft` aurait pour effet de recréer un seul commit sur base de tous les fichiers modifiés, dans le cas présent vous voulez potentiellement refaire plusieurs commits ou bien ne pas conserver certains fichiers. Il est donc important que vous utilisiez `reset` sans aucune de ces deux options.
```

2023-05-29 08:29 UTC, Elanis commented on architecture/faire-des-commits-au-quotidient.md
> +### Exemple
Je ne sais pas où exactement dans cette partie de texte, mais peut être parler du fait de stage des hunk/lines ?
Devoir commit partiellement des fichiers est quelque chose que je me retrouve à faire très souvent perso

2023-05-29 08:29 UTC, Elanis commented on architecture/faire-des-commits-au-quotidient.md
> +$ git reset d64706e
```suggestion
$ git reset d64706e # ou git reset HEAD~2
```
J'ai un doute si c'est 2 ou 3, mais il me semble bien que c'est 2. Et vu que cette notation est assez commune sur internet, peut être qu'en parler est pas une mauvaise idée

2023-05-29 08:29 UTC, Elanis commented on architecture/faire-des-commits-au-quotidient.md
> +Nous constatons comme attendu que l'historique de notre branche locale n'est plus cohérent avec celui de notre branche sur GitHub et il nous faut donc forcer GitHub à utiliser notre branche locale (l
Peut être ajouter une phrase pour indiquer que --force-with-lease est la manière safe de push force ? Histoire que les commandes en dessous soient explicites.

2023-05-29 08:29 UTC, Elanis commented on architecture/faire-des-commits-au-quotidient.md
> +Git propose un outil pour réordonner des commits et les fusionner, cet outil s'appelle le *rebase interactif* et permet de traiter automatiquement les commits *fixup*. Typiquement vous allez utiliser
Ajouter un titre ici pour le rebase interactif

2023-05-29 08:30 UTC, Elanis commented on architecture/faire-des-commits-au-quotidient.md
> +$ git reset d64706e
(Je vois que c'est fait plus bas, peut être pas forcement utile, à voir ce que tu en penses)

2023-05-29 10:40 UTC, Julien00859 commented on architecture/faire-des-commits-au-quotidient.md
> +Une première solution (très facile) est de faire fi de l'historique des commits dans la branche, vous vous dites qu'au final ce qui compte c'est ce qui arrivera sur la branche `main` pour la postérit
gitflow est déprécié

2023-05-29 10:41 UTC, Julien00859 commented on architecture/faire-des-commits-au-quotidient.md
> +$ git reset d64706e
Pour git-reset tu ne veux surtout pas jouer avec un HEAD~x parce que c'est juste trop facile de se tromper sur X et d'annuler un commit en trop

2023-05-29 10:46 UTC, Julien00859 commented on architecture/faire-des-commits-au-quotidient.md
> +Cet article vous explique comment réconcilier les deux, comment continuer à faire des petits commits incrémentaux pendant le développement, comment nettoyer sa branche juste avant d'ouvrir la pull-re
Je suis ok de changer "pull-request" en "pull/merge-request" mais je ne suis pas d'accord que de changer ça vers une formulation plus lourde. C'est plus important de mettre en place un cycle de review que de faire des historiques tout propre et normalement c'est correctement expliqué dans mon précédent billet sur git

2023-05-29 10:48 UTC, Julien00859 commented on architecture/faire-des-commits-au-quotidient.md
> +### Exemple
Alors en fait c'est quelque chose que nous autre on a appris "à la dur" avec `add/commit -p` mais qu'en fait mes étudiants sont hypers plus à l'aise que moi parce que l'intégration dans vscode/idea est vraiment géniale et ils le font déjà d'eux-mêmes. J'ai pas ressenti le besoin d'explicitement en parler dans le billet présent, je pourrais le faire mais je ne sais pas trop où... peut-être dans un prochain billet en la matière ?

2023-05-29 10:51 UTC, Julien00859 commented on architecture/faire-des-commits-au-quotidient.md
> +Nous constatons comme attendu que l'historique de notre branche locale n'est plus cohérent avec celui de notre branche sur GitHub et il nous faut donc forcer GitHub à utiliser notre branche locale (l
C'est expliqué plus haut, tu penses que je dois le répéter, peut-être dans une parenthèse ?

```suggestion
Nous constatons comme attendu que l'historique de notre branche locale n'est plus cohérent avec celui de notre branche sur GitHub et il nous faut donc forcer (avec `--force-with-lease` et non pas `--force`) GitHub à utiliser notre branche locale (le conseil de git qui voudrait qu'on `pull` est complètement idiot dans le cas présent).
```

Perso je trouve que ça allourdi le paragraphe, ça fait une deuxième parenthèse... ou alors...

```suggestion
Nous constatons comme attendu que l'historique de notre branche locale n'est plus cohérent avec celui de notre branche sur GitHub et il nous faut donc forcer (avec `--force-with-lease` qui est plus sur que `--force`) GitHub à utiliser notre branche locale. Notez que le conseil de git qui voudrait qu'on `pull` est complètement idiot dans le cas présent.
```

2023-05-29 10:53 UTC, Julien00859 commented on architecture/faire-des-commits-au-quotidient.md
> +Vous savez donc comment faire des beaux [messages de commit dans git] mais au moment de passer à la pratique vous êtes perdus. Vous aviez l'habitude de créer des nouveaux commits régulièrement, ne se
Pour moi toutes les deux/trois heures ou à la fin de la journée ça mène au même résultat: des commits pas propre dans l'historique. Si tu as une autre formulation je suis ok :p

2023-05-29 12:14 UTC, Julien00859 commented on architecture/faire-des-commits-au-quotidient.md
> +Attention, il est impératif que vous utilisiez `reset` **sans** les options `--hard` ou `--soft`. `--hard` aurait pour effet d'annuler toutes vos modifications sur disque, dans le cas présent vous vo
J'ai mis dans un commit à part pcq je ne suis pas sur du rendu

2023-05-29 12:16 UTC, Elanis commented on architecture/faire-des-commits-au-quotidien.md
> +Vous savez donc comment faire des beaux [messages de commit dans git] mais au moment de passer à la pratique vous êtes perdus. Vous aviez l'habitude de créer des nouveaux commits à interval régulier
```suggestion
Vous savez donc comment faire des beaux [messages de commit dans git] mais au moment de passer à la pratique vous êtes perdus. Vous aviez l'habitude de créer des nouveaux commits à intervalle régulier pour envoyer votre travail sur GitHub et ainsi avoir une copie de secours. Vos commits étaient courts, écrits à coup de `-m`, et décrivaient ce que vous aviez changé ces deux/trois dernières heures.
```

2023-05-29 12:40 UTC, Equinox4 requested changes

2023-05-29 12:40 UTC, Equinox4 commented on architecture/faire-des-commits-au-quotidien.md
> +Git propose aussi un outil pour réordonner des commits et les fusionner, cet outil s'appelle le *rebase interactif* et permet de traiter automatiquement les commits *fixup*. Typiquement vous allez ut
> vous pouvez aussi mettre le même commit que vous aviez mis 

la langue française est suffisamment riche pour qu'on utilise un verbe plus élégant que "mettre" ici

2023-05-29 12:40 UTC, Equinox4 commented on architecture/faire-des-commits-au-quotidien.md
> +$ git commit -a --fixup 7b99b92
l'option `-a` sort un peu de nul part

2023-05-29 13:27 UTC, Equinox4 approved these changes

2023-05-29 13:28 UTC, Elanis approved these changes

2023-05-29 13:55 UTC, merged