add: Les bases du dart
NotANameServer/Not-a-Hub pull request #87
Opened 2023-12-21 08:07 UTC by Rapougnac

Un petit article sur comment commencer le dart. Je couvre pas beaucoup de contenu (je trouve?), mais j'ai peur de trop partir dans tous les sens juste pour un premier article basique.

2023-12-22 23:59 UTC, westindev-lbr commented on langages/dart/les-bases-du-dart.md
> +Dart est un langage de programmation orienté object, est statiquement et fortement typé, c'est à dire que les types des variables sont connus à la compilation et qu'ils ne peuvent être changés. Il es
- Il est orienté **objet**  plutôt que 'object'
- Il faudrait aussi mentionner que bien qu'il soit statiquement typé, il supporte également l'inférence de type.
Le compilateur Dart peut inférer le type d'une variable à partir de sa valeur initiale ou du contexte dans lequel elle est utilisée.

2023-12-23 00:05 UTC, westindev-lbr commented on langages/dart/les-bases-du-dart.md
> +Celui recommandé par Dart est [VSCode](https://code.visualstudio.com/) avec [l'extension Dart Code](https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code) d'installée, cependant, si
rcensent -> qui les recensent

2023-12-23 00:21 UTC, westindev-lbr commented on langages/dart/les-bases-du-dart.md
> +Une fois Dart installé, nous pouvons ouvrir un terminal et executer `dart create myapp` pour initialiser un projet de base.
Avant d'en arriver là, je pense qu'il faut quand même introduire l'installation du [sdk Dart](https://dart.dev/get-dart)

2023-12-23 00:39 UTC, westindev-lbr commented on langages/dart/les-bases-du-dart.md
> +On remarquera plusieurs dossiers et fichiers qui on étés créés.
... qui ont été créés.
Suggestion de reformulation : Un nouveau répertoire au nom de votre projet est ainsi créé contenant les principaux dossiers et fichiers suivants :

2023-12-23 00:40 UTC, westindev-lbr commented on langages/dart/les-bases-du-dart.md
> +Nous pouvons maintenant éxecuter `dart run` afin de lancer notre programme fraîchement créé:
exécuter

2023-12-23 00:47 UTC, westindev-lbr commented on langages/dart/les-bases-du-dart.md
> +Maintenant que nous avons appris les rudiments, on peut à présent se rendre dans le fichier situé dans `bin/`, il porte le même nom que ce qu'on a nommé plus tôt, en l'occurence, `myapp.dart`.
Suggestion reformulation : Nous pouvons maintenant nous diriger vers le fichier situé dans le répertoire` bin/`. Ce fichier porte le nom que nous avons choisi précédemment, dans notre cas `myapp.dart`.

2023-12-23 01:01 UTC, westindev-lbr commented on langages/dart/les-bases-du-dart.md
> +title: "Les bases du Dart"
Peut-être renommer le titre de ton article :
Les bases de Dart : Introduction

¯\_(ツ)_/¯

2023-12-23 01:16 UTC, Rapougnac commented on langages/dart/les-bases-du-dart.md
> +Dart est un langage de programmation orienté object, est statiquement et fortement typé, c'est à dire que les types des variables sont connus à la compilation et qu'ils ne peuvent être changés. Il es
Oups, my bad j'ai écrit trop vite, je fix demain.

Et sinon, pour l'inférence, je sais pas tellement s'il est vraiment nécessaire de le mentionner ? La majorité des languages modernes la supporte, après ça ne coûte rien d'ajouter un aparté.

2023-12-23 01:18 UTC, Rapougnac commented on langages/dart/les-bases-du-dart.md
> +Une fois Dart installé, nous pouvons ouvrir un terminal et executer `dart create myapp` pour initialiser un projet de base.
J'avais fait une section, mais n'étant pas sûre si elle était pertinente je l'ai laissée de côté.

2023-12-23 01:19 UTC, Rapougnac commented on langages/dart/les-bases-du-dart.md
> +title: "Les bases du Dart"
Bonne idée, je savais pas quel titre choisir pour quelque chose en plusieurs parties

2024-02-12 18:16 UTC, Equinox4 requested changes
Je pense que l'article peut être intéressant pour introduire le langage auprès des débutants, cependant je ne sais pas s'il est nécessaire d'en faire une suite de plusieurs articles. On pourrait imo largement aborder la syntaxe directement dans un section dédiée de cet article.

2024-02-12 18:16 UTC, Equinox4 commented on langages/dart/les-bases-du-dart.md
> +Dart est un langage de programmation orienté object, est statiquement et fortement typé, c'est à dire que les types des variables sont connus à la compilation et qu'ils ne peuvent être changés. Il es
`le développement de serveurs.`
c'est à dire ?
\+ utilisation du mot "développer" et de ses dérivés 3 fois dans la même phrase, ça fait un peu redondant

2024-02-12 18:16 UTC, Equinox4 commented on langages/dart/les-bases-du-dart.md
> +<!-- TODO: Regarder l'étape d'installation? -->
TODO
aucune PR ne sera merge avec des TODO dedans :p

2024-02-12 18:16 UTC, Equinox4 commented on langages/dart/les-bases-du-dart.md
> +<!-- TODO: Regarder l'étape d'installation? -->
TODO
aucune PR ne sera merge avec des TODO dedans :p

2024-02-12 18:16 UTC, Equinox4 commented on langages/dart/les-bases-du-dart.md
> +<!-- ## Installation -->
pareil pour les commentaires non essentiels

2024-02-12 18:16 UTC, Equinox4 commented on langages/dart/les-bases-du-dart.md
> +Celui recommandé par Dart est [VSCode](https://code.visualstudio.com/) avec [l'extension Dart Code](https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code) d'installée, cependant, si
```suggestion
Celui recommandé par Dart est [VSCode](https://code.visualstudio.com/) avec [l'extension Dart Code](https://marketplace.visualstudio.com/items?itemName=Dart-Code.dart-code) d'installée, cependant, si cela ne vous convient pas, il y a une liste non-exhaustive qui les recensent [ici](https://dart.dev/tools#ides-and-editors).
```

2024-02-12 18:16 UTC, Equinox4 commented on langages/dart/les-bases-du-dart.md
> +Nous pouvons maintenant éxecuter `dart run` afin de lancer notre programme fraîchement créé:
```suggestion
Nous pouvons maintenant exécuter `dart run` afin de lancer notre programme fraîchement créé:
```

2024-11-25 15:45 UTC, closed without merging